### ISSUE TITLE
Goobi/ITM packaged using Docker

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#1023]

**Comment by sepastian** [comment]
Hello, what is the status of packaging Goobi for Docker?

I'm working at the University of Passau, we are also requiring a dockerized version of Goobi.

I have experience using Docker, I have packaged various applications; however, I'm new to Goobi.

Is there any way we can collaborate on this?

**Comment by jtweed** [comment]
Hi @sepastian, thanks for reaching out on this. I'd love for our work here to be of use to you.

We're actually working with Intranda on this and it's them who are creating the Docker container. We will mention it to them and see if releasing the container they have created for us publicly is an option.

It might not be at this stage, as there are closed source parts of Goobi that we are paying for and I'm not sure how they've split up the containers for the initial phase of work.

**Comment by sepastian** [comment]
Hi @jtweed, thanks for the update, I will keep an eye on this!
