### ISSUE TITLE
List the contributor codes

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/platform#1033]

**Comment by kenoir** [comment]
This is blocked until I understand:

- To which collections does that apply?
- Which codes map to which category?
- Which field from the Miro dump relates to category code?

**Comment by kenoir** [comment]
Pinging @jtweed @pollecuttn

**Comment by jtweed** [comment]
L/V/M/F:
* The rules from Christy
* Override by lists of individual image IDs

A/B/N:
* If the contributor code is in the specified list -> library & api
* If it isn't -> cold store
* Lists already supplied for B and N, A is TBA

AS/FP:
* cold store

D/S/W:
* Don't know, no rules available yet

C:
* handled separately by the photography workflow (already done)
