### ISSUE TITLE
Give Digital Production team read only access to editorial photography masters

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#1056]

**Comment by kenoir** [comment]
@jtweed by what means? Is this via S3? Have we already done this?

**Comment by jtweed** [comment]
IAM user with access to the S3 console was my assumption. Let’s talk about this today.

**Comment by kenoir** [comment]
This is probably a quick win as we've got a template for this.

**Comment by alexwlchan** [comment]
What this means:

* Holly and Rioghnach also need admin access to the client transfer bucket
* All four need read-only access to wc-editorial-photography

**Comment by kenoir** [comment]
Awaiting Keybase account creation.
