### ISSUE TITLE
Sort Miro images for Wellcome Image Awards

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#1058]
Miro images that are Wellcome Image Awards winners are going to be separately organised in Tandem Vault to give staff easy browsing and access to previous winners.

To do this we should:

* Create another path for these images (or re-use the Tandem Vault one if we can treat them differently on import into Tandem Vault)
* Match images based on the `image_award` field - note that this should match both "Biomedical Image Awards" and "Wellcome Image Awards"

Images that match this rule should still be matched by other rules as appropriate.

**Comment by alexwlchan** [comment]
I’d like to work on this one, if nobody minds. I don’t really know the current core of the image sorter that well.
