### ISSUE TITLE
Expose image credit information in the Catalogue API

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#1082]
Required for https://github.com/wellcometrust/wellcomecollection.org/issues/1707

**Comment by jtweed** [comment]
One thing to note on this. When we did the corporate photography, we worked out a list of "Wellcome-ish" credits that all got transformed to "Wellcome".

We'll need to do something similar here, transforming all "Wellcome-ish" credit lines to "Wellcome Collection".

**Comment by pollecuttn** [comment]
@jtweed Credit is for attribution, yes?
Is / could this be different from copyright?
cc @silveroliver

**Comment by jtweed** [comment]
Copyright as displayed doesn't have to be a legal entity, so we're fine to use credit lines for this if that's what they are. Most will be some form of Wellcome though.

Copyright is also separate from Creator, which we may have separate at some point where it makes sense.

So, my proposal: let's add a `copyright` property on Location that sits alongside 'licence'. It should be the credit line on the image. If that's not there, it should be taken from the contributor.
