### ISSUE TITLE
Expose Wellcome Image Awards field from MIRO in the API

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/platform#1100]
From @jennpb:
Would it be possible to expose this MIRO field in the API?
Usage History > Wellcome Exhibitions > Exhibitions > e.g. Wellcome Image Awards 2012

It doesn’t have to be visible by 6 November, but it’d be nice if it could be by the end of the quarter.

**Comment by pollecuttn** [comment]
From @jennpb:
"We agreed that for the time being we would concatenate Description + image award string. 

Here are two examples: 

https://wellcomecollection.org/works/c53mxsvq?query=A0001337 
Description
Photograph of a mare's (female horse) uterus with the fetus removed but still attached by the fetal membranes and umbilical cord. The vast blood supply can be seen on the inner surface of the uterus. Wellcome Image Awards 2015 Overall Winner.


https://wellcomecollection.org/works/yh8syjeu?query=B0001014 
Description
A high resolution magnetic resonance imaging (HRMRI) scan of a miscarried 20-week old human foetus, showing the head and a cross-section of the brain. This technique uses a magnetic field to induce the hydrogen nuclei in tissues to absorb and emit radio waves, producing an image which allows internal structures to be seen without disturbing the actual specimen. Biomedical Image Awards 1998.


The pattern for all awards should be:
Biomedical Image Awards 1997
Biomedical Image Awards 1998
Biomedical Image Awards 1999
Biomedical Image Awards 2000
Biomedical Image Awards 2001
Biomedical Image Awards 2002
Biomedical Image Awards 2003
Biomedical Image Awards 2004
Biomedical Image Awards 2005
Biomedical Image Awards 2006
Wellcome Image Awards 2008 
Wellcome Image Awards 2009
Wellcome Image Awards 2010
Wellcome Image Awards 2011
Wellcome Image Awards 2012 
Wellcome Image Awards 2012 Overall Winner
Wellcome Image Awards 2013
Wellcome Image Awards 2013 Overall Winner
Wellcome Image Awards 2014
Wellcome Image Awards 2014 Overall Winner
Wellcome Image Awards 2015
Wellcome Image Awards 2015 Overall Winner
Wellcome Image Awards 2016
Wellcome Image Awards 2016 Overall Winner
Wellcome Image Awards 2016, Julie Dorrington Award Winner
Wellcome Image Awards 2017
Wellcome Image Awards 2017 Overall Winner
Wellcome Image Awards 2017, Julie Dorrington Award Winner

Is there any other information you need from me? Any thoughts on when we might be able to add awards/commendations to the model, and how we will remember to extract these?"

@jtweed

**Comment by alexwlchan** [comment]
These fields are full of junk! I’ll pipe through what we’ve got, but there’s a bunch of other information we’ll end up discarding.

```
{
 ("Tibet's Secret Temple: Body, Mind and Meditation in Tantric Buddhism", None): 5,
 ('Award of Excellence', None): 10,
 ('Bedlam: The Asylum and Beyond, Wellcome Collection', None): 18,
 ('Can Graphic Design Save Your Life Wellcome Collection', None): 1,
 ('Death, Wellcome Collection', None): 2,
 ('Dirt, Wellcome Collection', None): 47,
 ('Electricity: The spark of life, Wellcome Collection', None): 28,
 ('Exquisite Bodies, Wellcome Collection', None): 20,
 ('Forensics: The Anatomy of Crime, Wellcome Collection', None): 48,
 ('Heart Exhibition, Wellcome Collection', None): 57,
 ('High Society, Wellcome Collection', None): 29,
 ('Identity, Wellcome Collection', None): 20,
 ('Institute of Medical Illustrators Wellcome Award', None): 1,
 ('Making Nature, Wellcome Collection', None): 16,
 ('Medicine Man Catalogue', None): 730,
 ('Medicine Man Exhibition British Museum', None): 1203,
 ('Medicine Man, Wellcome Collection', None): 883,
 ('Reading Room', None): 63,
 ('Satellites, Wellcome Collection', None): 1,
 ('Skin, Wellcome Collection', None): 68,
 ('Sleeping and Dreaming, Wellcome Collection', None): 14,
 ('States of Mind, Wellcome Collection', None): 1,
 ('States of Mind: Tracing the Edges of Consciousness, Wellcome Collection', None): 12,
 ('Superhuman, Wellcome Collection', None): 31,
 ('Tabiyat: Medicine and Healing in India', None): 46,
 ('The Institute of Sexology, Wellcome Collection', None): 47,
 ('The Phantom Museum, Publication', None): 136,
 ('This Is A Voice, Wellcome Collection', None): 47,
 ('War and Medicine, Wellcome Collection', None): 34,
 ('Wellcome Collection, miscellaneous', None): 4,
 ('Biomedical Image Awards', '1997'): 7,
 ('Biomedical Image Awards', '1998'): 16,
 ('Biomedical Image Awards', '1999'): 12,
 ('Biomedical Image Awards', '2001'): 15,
 ('Biomedical Image Awards', '2002'): 13,
 ('Biomedical Image Awards', '2005'): 10,
 ('Biomedical Image Awards', '2006'): 16,
 ('Wellcome Image Awards', '2008'): 11,
 ('Wellcome Image Awards', '2009'): 5,
 ('Wellcome Image Awards', '2011'): 10,
 ('Wellcome Image Awards', '2012'): 6,
 ('Wellcome Image Awards', '2014'): 11,
 ('Wellcome Image Awards', '2015'): 15,
 ('Wellcome Image Awards', '2016'): 15,
 ('Wellcome Image Awards', '2017'): 18,
 ('WIA Overall Winner', '2015'): 1,
 ('WIA Overall Winner', '2016'): 1,
 (None, None): 4
}
```

**Comment by jennpb** [comment]
The non-Wellcome Image Award categories could be interesting once we can model them properly (e.g. This image was featured in High Society).
