### ISSUE TITLE
Some images are being rejected for malformed INNOPAC ID

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#1124]
We have a bunch of transformer failures of the form:

```
Expected 8-digit INNOPAC ID or nothing, got Some(113183382)
```

This is affecting images in the L and M collections. Three distinct failure modes:

* [ ] `b01234567` or `B01234567`, where there's a leading B
* [ ] `.b01234567`, where there's a leading `.`
* [x] `150056628`, where we have nine digits

Additional stuff:

* [ ] I’d also like to get a test in that `b1033192x` is treated correctly (the `x` is a check-digit).
* [x] L0035411 has `L 35411` in that field, which feels like nonsense.

And to finish off:

* [ ] Reindex the L and M collections

**Comment by alexwlchan** [comment]
```
L0001138EA	113183382
L0001138EB	113183382
L0035213	150056628
```

**Comment by alexwlchan** [comment]
To be clear, these are the values in the `image_innopac_id` field.

**Comment by pollecuttn** [comment]
Can't find any of those innopac IDs in Sierra.

L0035213	
Short desc: Plan of Newcastle Infirmary with proposed  alterations
Description of image content: Plan of the Newcastle-upon-Tyne Infirmary c.1852.
From a kw search in Sierra of the short description this might be b15005628 which has the title in Sierra "Report of the Deputation of the Building Committee of the Newcastle-upon-Tyne Infirmary :|bbeing the result of their inspection of several of the London and provincial hospitals /|c[Peregrine George Ellison [and others]."

**Comment by pollecuttn** [comment]
L0001138EA 
Illustrated London News: b1318338

**Comment by alexwlchan** [comment]
I’ve edited the JSON files in S3 for the really problematic ones, and the transformer will just strip off leading b-prefixes (which is okay, as it knows that it’s transforming to b-numbers anyway).

**Comment by alexwlchan** [comment]
Once the build goes green, we should merge the patch, deploy a new transformer, and reindex the L and M collections.

**Comment by pollecuttn** [comment]
FYI @kenoir @alicefuzier
