### ISSUE TITLE
Version image collections bucket

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#1130]
As the new image collections bucket is the master store of this collection going forward, we need to enable versioning and version lifecycle management on the bucket.

Let's delete non-current versions after 30 days, like the editorial photography bucket.

**Comment by alexwlchan** [comment]
This is already done: https://github.com/wellcometrust/platform/blob/master/miro_preprocessor/s3.tf#L44-L54

**Comment by alexwlchan** [comment]
This is already done:

https://github.com/wellcometrust/platform/blob/master/miro_preprocessor/s3.tf#L44-L54
