### ISSUE TITLE
No title on some works

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/platform#1131]
Not sure if title is mandatory (is it?), but we were getting 500 errors here:
https://wellcomecollection.org/works/jcegqq8b

From not receiving a title here:
https://api.wellcomecollection.org/catalogue/v1/works/jcegqq8b

We've updated our app to handle no titles, but feels a bit weird.

Other refs:
https://wellcomeimages.org/indexplus/image/V0030717.html
http://search.wellcomelibrary.org/iii/encore/record/C__Rb1568966?lang=eng

**Comment by jamesgorrie** [comment]
Another:
https://wellcomecollection.org/works/asb89949

**Comment by pollecuttn** [comment]
Pinging @jtweed to prioritise this.

**Comment by jtweed** [comment]
This is a library item, with a valid link to Sierra. So it'll be fixed when we're taking the catalogue data from Sierra.

We could exclude for now, if we make sure to remember to change back later on when we have Sierra data.

What do you think @jennpb?

**Comment by jennpb** [comment]
Funnily, in the results list it shows a very enticing 'Coming soon...'
![image](https://user-images.githubusercontent.com/1446139/32054160-6bea449e-ba55-11e7-88c4-e076bfb8d1fe.png)

Given that you'd have to be a really motivated researcher to find these items, the worst that will happen from a user point of view is that people stumble across it in results and be either moderately amused or will ask for more info. 

I don't know how big a problem this is. I'd say if it's less than 1000 images, we won't worry about it for now.

**Comment by jtweed** [comment]
There are 110,594 works in the index, 110,464 of which have a title. So there are only 130 images that don't have a title -> wontfix pending Sierra data.

The "Coming soon..." is being added in the front end, it's not in the API response.
