### ISSUE TITLE
Should we consider parent child relathionship when sorting Miro images into decisions?

### ISSUE THREAD

**Issue by alicefuzier** [wellcometrust/platform#1135]
I was checking the miro ids for which we failed to copy the master assets in the s3 bucket. To do that I wrote a script that associates a miro id with s3 keys that have a prefix matching the id, but that are ambiguous according to the copy master asset lambda rules (as explained here #1081). 

I noticed that some of them are like this one:
```
"L0000031": [
    "Wellcome_Images_Archive/L Images/L0000000/L0000031EA-LH-CS.jp2"
  ]
```
`L0000031` is a miro id that was sorted into the catalogue api by the image sorter (which means it has license, title, etc), but it has no image in miro.
`L0000031EA` is a miro id that was sorted in cold store by the image sorter. 

As I remember from the editorial photography work, sometimes images in miro don't have an actual image because they represent a parent id that serves as a way of grouping related images together and storing their shared metadata. For editorial photography images, we embedded some image metadata from the parent miro id when the actual image metadata was lacking ( can't quite find out how we decided that a miro id was a parent of another one). 

Should we do something similar when processing all miro images and take parent children relationship into account in the image sorter? If that were the case for the above example, `L0000031EA` could potentially be going to catalogue api instead, so I wonder: are we sending to many things to cold store because we ignore parent id metadata?

**Comment by pollecuttn** [comment]
Pinging @jtweed

**Comment by jtweed** [comment]
No, these are indeed separate images, so we should let it fail.
