### ISSUE TITLE
Miro special copyright info

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/platform#1172]
Provide a lookup for the now unavailable "special copyright info".

- [ ] Add text to images in Tandem Vault explaining the existence of special copyright info
- [x] Provide a spreadsheet for the Digitisation Team with all the special copyright info we have

**Comment by alexwlchan** [comment]
There's a spreadsheet in the Miro data bucket which provides a Miro ID <-> Copyright info lookup for all the images we've sent to Tandem Vault.

**Comment by alexwlchan** [comment]
Christy says this is showing up correctly, so closing.

**Comment by alexwlchan** [comment]
Reopening until I’ve given Christy the spreadsheet!

**Comment by alexwlchan** [comment]
Okay, sent!
