### ISSUE TITLE
Miro contributor lookup to Tandem Vault does not normalise source code

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/platform#1173]
So where `image_source_code` is lowercase the lookup fails.

**Comment by alexwlchan** [comment]
How many are actually broken?

**Comment by alexwlchan** [comment]
It looks like the only issue we can sensibly fix is lowercase-to-uppercase, so let's just do that.

**Comment by alexwlchan** [comment]
```

**Comment by alexwlchan** [comment]
L, M and V will be re-run by #1172, so I’ll fix the B and N instances by hand.
