### ISSUE TITLE
Sierra Item merger

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/platform#1195]
Merge Item records into a dynamo table providing the entry point into the ingest pipeline.

Needs to do the consistent read, conditional update shuffle.

Shares a dynamo table with the Sierra Bib merger (https://github.com/wellcometrust/platform/issues/1196).

Depends: https://github.com/wellcometrust/platform/issues/1194

**Comment by alexwlchan** [comment]
I’m working on the model code – creating a SierraItemRecord class, and a method mergeItemRecord which adds it to a MergedSierraRecord.

**Comment by alexwlchan** [comment]
mmmm but how do we fan out the updates

more work and thinking required
