### ISSUE TITLE
Sierra Bib merger

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/platform#1196]
Merge Item records into a dynamo table providing the entry point into the ingest pipeline.

Needs to do the consistent read, conditional update shuffle.

Shares a dynamo table with the Sierra Item merger (https://github.com/wellcometrust/platform/issues/1195).

Depends: https://github.com/wellcometrust/platform/issues/1194

**Comment by alexwlchan** [comment]
Closed by #1232.
