### ISSUE TITLE
Missing Ls in Tandem Vault

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#1197]
Some recent Ls were missed for upload into Tandem Vault. The master images were correctly sorted into tandem_vault_master, but the derivatives were not uploaded to Tandem Vault as they had not been synced to S3 before running the pipeline.

I synced the derivatives and re-ran the pipeline for all L images. There were 946 new L derivatives, but only around 340 made it into Tandem Vault. I don't know how many of those should have gone to Tandem Vault, but I think it should have been all or almost all of them.

The images that were originally reported as missing from Tandem Vault are still missing. They are L0089491, L0089493, L0089517 and L0089530.

We need to look at why the pipeline has stalled and ensure that all missing L derivatives are correctly uploaded to Tandem Vault.

**Comment by alexwlchan** [comment]
I had a poke around yesterday; it looks like the xml_to_json task is getting stopped early. If you look at the JSON files, their timestamps aren’t consistent with the recent runs.

**Comment by alexwlchan** [comment]
All four listed images are now in TV, and I haven't seen any other complaints – closing.
