### ISSUE TITLE
Deleting a record from dynamo tables crashes our apps

### ISSUE THREAD

**Issue by alicefuzier** [wellcometrust/platform#1281]
Deleting a record from the SierraData_bibs and SierraData_Merged tables causes TryBackoffTerminalFailures downstream (sierra_bib_merger and sierra_transformer)

**Comment by alicefuzier** [comment]
Still TODO

- [ ] Fix transformer
- [ ] Fix ingestor (in progress in #1318)

**Comment by kenoir** [comment]
Closing as fixed.
