### ISSUE TITLE
Reduce the number of transient 500 errors from Loris

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#1311]
This is not unusual for a Sunday:

![screen shot 2017-12-18 at 08 12 08](https://user-images.githubusercontent.com/301220/34095899-2e27fd14-e3cb-11e7-9404-19a3d4ebf838.png)

where the error is some sort of connection error from S3 – either a timeout, or a chunked decode error, or something else. (Details in #924.)

I wonder if we’re hitting S3 limits – especially if we request for the same image many times, as we would when tiling. Loris’s internal cache behaviour is a little simplistic here – it always refreshes the cached file on disk (!?). We ran with diskless Loris briefly, but that’s hitting the wrong problem. We should try to reduce our S3 requests.

Two thoughts on how we might do this:

* Implement full-fledged ETag support in Loris. I’ve put an initial suggestion in https://github.com/loris-imageserver/loris/issues/281
* Take advantage of the fact that S3 ETags are super simple – just the MD5 of the source file – and monkey-patch our Loris to fit, rather than doing a complete ETag implementation

I think the first would be more useful, especially as we won’t do it until after New Year’s so we can take our time.

Questions for @alicefuzier and @kenoir:

- Do you agree with what I’ve written? If so, which fix would you prefer? (One of you will be doing it!)
- Do you know if there’s a CloudWatch metric for S3 reads? It would be good to track what, if any, difference this makes.
- Would you be okay turning down the CloudWatch alarms, so a single error is non-critical, until we get this resolved?

**Comment by jtweed** [comment]
S3 ETags are not always just an MD5 of the file, it depends how the file was uploaded:

http://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html

**Comment by alexwlchan** [comment]
Blergh. Guess we’re doing it properly then!

**Comment by alicefuzier** [comment]
I think I might be missing something here as I'm not too familiar with Loris, but why would Loris be making many requests to S3 to the same file?

My understanding was that Loris uses two types of caches: 
- The resolver cache where the s3 originals are stored sharded based on the s3 key
- An internal filesystem cache where it stores intermediate files resulting from resizing, cropping, rotating and so on.

I thought Loris policy of always refreshing the file was on the second cache (and I also thought that is configurable anyway, so we could just change the config if that's a problem, but correct me if I'm wrong). I thought that the resolver cache was only cleaned by the cache cleaner based on the age and size of files and that, If files were not deleted, Loris would use them. So, when tiling, I'd have imagined that we retrieve the original once, store it in the resolver cache and then generate all the derivative from that. Am I wrong?

I think we might need to revise the size of the resolver cache. I remember setting it to 160gb 'cause that was the size our old efs volume had reached and, as it wasn't growing anymore, I set the ebs size as that. However, that was back when we only had V images, so probably an increase in the cache size would increase overall Loris performance.

**Comment by alexwlchan** [comment]
Blergh, I should not write tickets before I’ve had breakfast.

I think you’re right Alice – I thought Loris was refreshing the resolver cache on every request, and upon looking at the code I seem to have misremembered.

Expanding the EBS volume might help, as we’d have more resolver cache hits.

**Comment by alexwlchan** [comment]
Resolved by #1633.
