### ISSUE TITLE
Images served through Loris should preserve the DPI of the original image

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#1346]

**Comment by pollecuttn** [comment]
Also have the DPI metadata available because currently it looks like images are 96dpi when they're more like 300+ dpi.

**Comment by jtweed** [comment]
WONTFIX. DPI is a measure of print resolution, not image resolution.

We won't be doing anything to perpetuate the misunderstanding that exists around this. Let's use the opportunity to educate instead.
