### ISSUE TITLE
Investigate using AWS Certificate Manager for wellcomeimages.org

### ISSUE THREAD

**Issue by wellingk** [wellcometrust/platform#1372]
**Issue**
We currently have a blanked SSL that covers multiple domains in GeoTrust.  This cert is up for renewal on 15th Feb.  The cost per SAN is circa £90, and there are currently two SANs for wellcomeimages.org and www.wellcomeimages.org.  I am trying to get as many SANs as possible into AWS Certificate Manager as its free!  Please can you look at the possibility of this for the wellcomeimages domain, and implement if possible?

Thanks

**Comment by jtweed** [comment]
Hi Kate, that domain is managed by @jennpb's team. Re-assigning.

**Comment by jennpb** [comment]
@jamesgorrie @gestchild @davidpmccormick Do we need to retain SSL certs for wellcomeimages.org domains?

**Comment by jamesgorrie** [comment]
We have a cert in ACM which handles this which cost $0.

**Comment by jennpb** [comment]
Thank you! Closing this as a non-issue.
