### ISSUE TITLE
Scheduled snapshots from Elasticsearch to S3

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#1397]
We also need to make sure we suppress visible records using the same query as the API.

Depends:
- #1668 
- #1663
- #1659
- #1661
- #1660

**Comment by alexwlchan** [comment]
The current code is here: https://github.com/wellcometrust/dockerfiles/tree/master/elasticdump

It was meant to run as a standalone task; we'll probably want to change it to be passed config directly if it's being run on a schedule.

**Comment by jtweed** [comment]
When someone picks this up, I'd like to pair on it to learn a bit a how Terraform and ECS services work.

**Comment by jtweed** [comment]
I would like us to set an approach here that we can use for all downloadable datasets, not just the Catalogue. We already have examples of other datasets we would like to make available both as an API and a downloadable dataset, eg. the Medical Officer of Health reports.

My proposal is therefore that we create a new subdomain for all downloadable datasets, that mirrors the structure for public APIs. The URL pattern should be:

`https://data.wellcomecollection.org/{api}/{version}/{type}.{format}`

This would be mapped to a public S3 bucket called `s3://wellcomecollection-public-data`.

If we use this to make data dumps available that don't have an associated API, the pattern would be:

`https://data.wellcomecollection.org/{dataset}/{type}.{format}`

Files should be gzipped, so the Catalogue API works would be available at:

`https://data.wellcomecollection.org/catalogue/v1/works.json.gz`

Outstanding questions:

- Do we need to date version the dumps? eg. `/catalogue/20180306-works.json.gz` or `/catalogue/20180306/works.json.gz`
- If so, should we always additionally provide the latest without a date in the filename?
- Is it weird using the API version like this? It provides a contract about the format of the data.

**Comment by kenoir** [comment]
The API version is useful as it implies major format changes. 

We need to decide if we are happy to make date snapshots available, as we are likely to want to remove things from old snapshots (based on say author requests) and I don't think we want to deal with having to redact old snapshots.

**Comment by alexwlchan** [comment]
> Do we need to date version the dumps? eg. /catalogue/20180306-works.json.gz or /catalogue/20180306/works.json.gz

I think so – and then dated data sets are immutable. If you download the 20180306 data set, you always get either:

* A 200 OK and the same data you would have got the previous day; or
* A 410 Gone if we've had to redact the data

Since the API doesn't make the guarantee of immutability, and it feels like that's one of the features/reasons we'd have the snapshots.

> If so, should we always additionally provide the latest without a date in the filename?

Only as a 302 Redirect, if at all.

> Is it weird using the API version like this? It’s there to provide a contract about the format of the data.

No, for the reason you suggest.

**Comment by jtweed** [comment]
Actually, @kenoir makes a very good point about redactions. I think for that reason we can only realistically make the current snapshot available, updated daily.

So it would be pushed to:

`s3://wellcomecollection-public-data/catalogue/v1/works.json.gz`

And served from:

`https://data.wellcomecollection.org/catalogue/v1/works.json.gz`
