### ISSUE TITLE
Implement rules for merging single-page Miro and Sierra works

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#1408]
When matching Miro and Sierra records for merging, we should base the decision only on data from Sierra. This is because the Sierra data is canonical and can be updated, whereas the Miro data cannot.

The rules are as follows:

* Sierra work of type `Picture` or `Digital images`
* Sierra has a Miro ID that can be extracted from 962
* There is only one Miro ID in 962 (there can be multiple, if so do not merge any of them)

Where there a decision to merge, the Sierra work should be used as the base work, with the following data copied from Miro:

* the digital location from the Miro item added to the Sierra item
* the source identifiers (excluding `sierra-system-number`) from the Miro work added to the Sierra work
* the source identifiers (excluding `sierra-system-number`) from the Miro item added to the Sierra item

No other data should be taken from the Miro work.

**Comment by alexwlchan** [comment]
There's an additional rule here:

* Only if the Sierra record has a single item (so we know where to put the location)
