### ISSUE TITLE
Shard data in source data bucket

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#1512]
- [x] New records written by the VHS are sharded (#1540)
- [x] Existing records are re-sharded (#1545)

**Comment by jtweed** [comment]
Presumably makes sense to rename this bucket to the new scheme as part of doing this.

**Comment by alexwlchan** [comment]
@jtweed I‘m not opposed to renaming the bucket, but let's do one change at a time. 😄

**Comment by alexwlchan** [comment]
The existing records have been copied into new shards; I still have to clean up the old shards.

**Comment by alexwlchan** [comment]
All the existing records have been resharded correctly.

👌
