### ISSUE TITLE
Example JSON structure for creators and contributions.

### ISSUE THREAD

**Issue by silveroliver** [wellcometrust/platform#1528]

**Comment by silveroliver** [comment]
Example:

{
  "id": "watu9tbc",
  "type": "Work",
  "workType": {
    "id": "digital-images",
    "type": "WorkType",
    "label": "Digital Images"
  },
  "creators": [
    {
      "label": "Jacobs, Philip P. (Philip Peter), 1879-1940.",
      "type": "Person",
      "identifiers": [
        {
          "value": "2005016805",
          "type": "Identifier",
          "identifierScheme": "lcsh"
        }
      ]
    }
  ],
  "contributors": [
    {
      "type": "Contribution",
      "agents": {
        "id": "a24s7qf3",
        "name": "Jacobs, Philip P. (Philip Peter), 1879-1940.",
        "type": "Person",
        "identifiers": [
          {
            "value": "2005016805",
            "type": "Identifier",
            "identifierScheme": "lcsh"
          }
        ]
      },
      "contributionType": [
        {
          "contributionType": "editor",
          "label": "Editor",
          "type": "ContributionType"
        }
      ]
    }
  ]
}

**Comment by silveroliver** [comment]
Still need to straighten out what we are doing with names

**Comment by alexwlchan** [comment]
This looks fine to me, but @jtweed should have a look as well. :-)

**Comment by jtweed** [comment]
Couple of comments:

- `agents` should be `agent` if there's only one (which I think there is)
- `contributionType` should probably be called `role` if there can be multiple (which I think there might be)
- we then probably want a `ContributionRole` type

**Comment by silveroliver** [comment]
@jtweed updated based on a discussion today. Reluctant to go role as we use that for a organisation role at the moment. Maybe we can review that. Thoughts on the edited version above.

**Comment by silveroliver** [comment]
Need to include title as well...

{
  "id": "watu9tbc",
  "type": "Work",
  "workType": {
    "id": "digital-images",
    "type": "WorkType",
    "label": "Digital Images"
  },
  "creators": [
    {
      "label": "Jacobs, Philip P. (Philip Peter), 1879-1940.",
      "type": "Person",
      "identifiers": [
        {
          "value": "2005016805",
          "type": "Identifier",
          "identifierScheme": "lcsh"
        }
      ]
    }
  ],
  "contributors": [
    {
      "type": "Contributor",
      "agent": {
        "id": "a24s7qf3",
        "name": "Jacobs, Philip P. (Philip Peter), 1879-1940.",
        "type": "Person",
        "identifiers": [
          {
            "value": "2005016805",
            "type": "Identifier",
            "identifierScheme": "lcsh"
          }
        ]
      },
      "contributions": [
        {
          "contribution": "editor",
          "label": "Editor",
          "type": "Contribution"
        } ,
      "titles": [
        {
          "label": "translation of War and Peace",
          "type": "Title"
        } ,
      ]
    }
  ]
}

**Comment by silveroliver** [comment]
@jtweed can you look at title as well. It basically relates the contribution to another work which their contribution is significant. It might be a park this for now bit of the model.

Examples we have been given include:
Abridged and adapted by the translator:
a 700 1   Niebuhr, Carsten,|d1733-1815.|tReisebeschreibung nach Arabien und
          andern umliegenden Ländern.|0n  84239435
a 700 1   Niebuhr, Carsten,|d1733-1815.|tBeschreibung von Arabien.|0n  84239433

"Based on Mr Foote's Other Leg; Comedy, Tragedy and Murder in Georgian London by Ian Kelly.":
a 700 1   |iDramatization of (work):|aKelly, Ian,|d1966-|tMr Foote's other
          leg.|0n 2004002376

**Comment by jtweed** [comment]
Yeah that feels closer, but I agree let's talk about the title thing when you're next in. Is there any link through to the actual work or is just text? If so, should it really be a type?

One thing I noticed on the above, a` Person` should be the same whether on `creators` or `agent`, so we should be consistent on `label` vs `name`.

**Comment by silveroliver** [comment]
@jtweed updated example above addressing moving to calling a contribution type a role. Consistent use of name and titles (like Madam, Countess, confusing label?). Moving away from the generic label. That seem reasonable?

**Comment by silveroliver** [comment]
Personally think we can park title in relation to a contributor and a work

**Comment by jtweed** [comment]
Yes, one question. Is `titles` deliberately plural?

**Comment by silveroliver** [comment]
Yes but not sure I like it (clashes with title for a work). Its a repeatable field so I will update the example to reflect that.

**Comment by silveroliver** [comment]
Changed titles to prefix. Plural? It is a repeatable field.
