### ISSUE TITLE
Ingestor pay attention to version

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/platform#1564]
At present the Ingestor has no notion of version and so could write updates to ES in the wrong order.

Follows on from https://github.com/wellcometrust/platform/issues/1563, in using the work version and conditionally updating Elasticsearch (it is likely we will need to use external versioning in ES: https://www.elastic.co/blog/elasticsearch-versioning-support).

**Comment by alexwlchan** [comment]
Duplicate of #1425?

**Comment by kenoir** [comment]
^ closing as dupe.
