### ISSUE TITLE
Matcher service acceptance criteria

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/platform#1566]
Write some acceptance criteria "three amigos" style with @jtweed and @rgladwell.

We want some clear human readable test cases that cover the expected graph changes, JSON output examples for each case, and consideration that updates may come out of order.

**Comment by kenoir** [comment]
![giphy 6](https://user-images.githubusercontent.com/953792/36384087-0aa98866-1586-11e8-8b4b-b084a673a44e.gif)

**Comment by alexwlchan** [comment]
In terms of graph changes, I think the bare minimum we want to cover is:

Adding a single node, multiple nodes

![graph1](https://user-images.githubusercontent.com/301220/36791908-e9fda5c2-1c90-11e8-9251-28d4514c8d12.png)

Joining multiple graphs

![graph2](https://user-images.githubusercontent.com/301220/36791917-f070b372-1c90-11e8-8415-e4d199b130ea.png)

Detaching single nodes

![graph3](https://user-images.githubusercontent.com/301220/36791924-f696cc32-1c90-11e8-970f-e54a9c7d679c.png)

Detaching larger graphs

![graph4](https://user-images.githubusercontent.com/301220/36791935-fed26488-1c90-11e8-9bd3-98d4780979e3.png)

Adding and detaching graphs in the same update

![graph5](https://user-images.githubusercontent.com/301220/36791939-02b3ef9a-1c91-11e8-9878-eb1ac2cdb834.png)

But we should property-based test this code, as there will be edge cases we'll get wrong!

**Comment by kenoir** [comment]
Related: https://github.com/wellcometrust/platform/pull/1613

**Comment by kenoir** [comment]
Closing for now, thought he content is still useful.
