### ISSUE TITLE
Mutability of cancellable in TryBackoff could be source of bugs

### ISSUE THREAD

**Issue by rgladwell** [wellcometrust/platform#1606]
Mutability of the `maybeCancellable` private field in `TryBackoff` could be source of bugs:

https://github.com/wellcometrust/platform/blob/fc0566b7f4b466db76b703b9991945dad1805e96/common/src/main/scala/uk/ac/wellcome/utils/TryBackoff.scala#L56

For instance, if the `run` function is called more than once on the same instance of `TryBackoff` the previous `maybeCancellable` will be overwritten and the previously started scheduler will become uncancellable.

This maybe related to issues I'm having running the tests from within a SBT REPL session.

**Comment by rgladwell** [comment]
@kenoir Taking a look at the code, it looks as though a temporary fix would look something like this:

```scala
      if (shouldReschedule) {
        val waitTime = timeToWaitOnAttempt(attempt)
        val cancellable = system.scheduler.scheduleOnce(waitTime milliseconds)(
          run(f, system, attempt = numberOfAttempts))
        cancelRun()
        maybeCancellable = Some(cancellable)
      }
```

Although this above fix maybe susceptible to threading errors, for examnple if two threads call `run` at the same time and `maybeCancellable` is overwritten by one thread before it can be cancelled by the other.

We're actually starting multiple schedulers when we use `TryBackoff` as it recursively calls its own `run` method, so it lookas as if we might be overwriting `maybeCancellable` all the time without cancelling it.

**Comment by kenoir** [comment]
> So it look as as if we might be overwriting maybeCancellable all the time without cancelling it.

Eep!

I was thinking something like:

```scala
    if(!maybeCancellable.isEmpty) {
      throw new RuntimeException(
        "Cannot run, process already running."
      )
    }
```

In the `run` method might highlight the issue further.

**Comment by rgladwell** [comment]
So after reviewing the `TryBackoff` code with @kenoir it looks as though the the actor/thread reading messages off the SQS queue is not shutting down even after `cancelRun`, **if a `GracefulFailureException` is thrown.**

After discussion, writing your own retry/backoff code is really hard and we are consdering removing the custom code for this from `platform` and replacing it with a more established library like [retry](https://github.com/softwaremill/retry) or [scala-retry](https://github.com/hipjim/scala-retry).

Before we proceed we wanted @alexwlchan and @alicefuzier's input, please? Thoughts?

**Comment by alexwlchan** [comment]
> After discussion, writing your own retry/backoff code is really hard and we are consdering removing the custom code for this from platform and replacing it with a more established library like retry or scala-retry.

Yes, do that.

If memory serves, the current TryBackoff code is on its third rewrite (by us) at least. Get rid of it!
