### ISSUE TITLE
Remove the "visible" field from DisplayWork

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#1619]
If something gets as far as being a DisplayWork, it surely must be visible!

**Comment by kenoir** [comment]
👍

**Comment by alexwlchan** [comment]
Mmm. So in fact we convert Work to DisplayWork inside the WorksService, after it's been retrieved from Elasticsearch, but before we decide to 410 it.

This feels icky to me – WorksService is a weird mixture of internal logic (interacting with Elasticsearch and Works) and display logic. It feels like WorkService should just return a Work, and it's up to the caller to decide how to use it.
