### ISSUE TITLE
Is MARC field 260 subfield $c (publication date) repeatable?

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#1620]
Pulling out a TODO #1599.

See https://github.com/wellcometrust/platform/pull/1599/files#diff-98e5e1eb54a097b178c6b358fcf4ca6bR8 – I made an educated guess about whether we'd see it more than once, and if so, how to handle it.

Qs for @silveroliver (or possibly the librarians):

* Can a MARC record have more than one instance of field 260 subfield $c?
* If so, how should we join multiple instances for our publicationDate field?

**Comment by pollecuttn** [comment]
In MARC, the 260|c is repeatable (R): http://www.loc.gov/marc/bibliographic/bd260.html

**Comment by alexwlchan** [comment]
So then the notes on $c say:

> Only one subfield $c may be recorded in multiple publishing statements of a record.

**Comment by wilfox** [comment]
Hope this helps - see attached document.
[260 subfield c.docx](https://github.com/wellcometrust/platform/files/1816050/260.subfield.c.docx)
