### ISSUE TITLE
The title rules in the ontology omit subfield c.

### ISSUE THREAD

**Issue by wilfox** [wellcometrust/platform#1625]
Subfield c is in this library record: http://libsys.wellcomelibrary.org/record=b1078659
It is presented as part of the title (field 245) is this correct?

**Comment by wilfox** [comment]
@jtweed @silveroliver

**Comment by silveroliver** [comment]
We are intending to split up the different parts of title. In fact subfield c it could be argued is a duplication of the creator field. We are staying with the naive implementation of title and implementing a fuller version in the next quarter.

For reference:
![marc title](https://user-images.githubusercontent.com/3657777/37401597-7afdb9be-2780-11e8-8c05-0746ade16481.png)
