### ISSUE TITLE
Reference data/work types/journals

### ISSUE THREAD

**Issue by wilfox** [wellcometrust/platform#1662]
The letter j looks like its been used twice to code for journals and e-journals.

![reference data journals](https://user-images.githubusercontent.com/36954333/37289074-b7ab9cea-2600-11e8-9372-5c34979785e6.JPG)

For material types Sierra uses d for journals and j for e-journals.
I can't see a d in the Reference Data list.

![sierra material types](https://user-images.githubusercontent.com/36954333/37289084-c105f380-2600-11e8-816a-661ed33c7c14.jpg)

Apologies if this was done intentionally - Currently I understand Journals to be our physical printed journal collections and e-journals are the electronic journals we subscribe to.

**Comment by pollecuttn** [comment]
@wilfox Where does the first image come from?

**Comment by pollecuttn** [comment]
@wilfox Oh - is it from https://github.com/wellcometrust/platform/blob/master/ontologies/Reference%20data/work-types.csv ?

Looks like a mistake and Journals should be 'd' per Sierra. Might be worth checking with Silver.

**Comment by wilfox** [comment]
Yes that's right from Reference data work-types - will check with Silver.

**Comment by kenoir** [comment]
Closing as 💀
