### ISSUE TITLE
Fix the Sierra lettering transformation

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#1673]
As discussed in this morning's domain modelling session:

Currently we look for 216 ind 16, then populate from fixed field "lettering". Two problems:

* We don't care about the value of the 1st indicator
* There is no "lettering" fixed field!

We should look for 216, 2nd ind 6, then populate from subfield $a.

**Comment by silveroliver** [comment]
Small correction 246 I think in this case '
