### ISSUE TITLE
Model for populating 650 - subjects

### ISSUE THREAD

**Issue by silveroliver** [wellcometrust/platform#1744]

**Comment by silveroliver** [comment]
Our use of subject was inpart inspired by Library of Congress. Though note ComplexSubject is not from Bibframe but is from another LC spec called MADS for representing authority records (acknowledging holes in SKOS in its ability to handle post-coordination).

http://www.loc.gov/standards/mads/rdf/v1.html#ComplexSubject

**Comment by silveroliver** [comment]
Example:
{
  "subjects": [
    {
      "label": "Tuberculosis - prevention & control -- Paris -- 1850 -- bibliography.",
      "type": "Subject",
      "concept": {
        "id": "hd2891f",
        "label": "Tuberculosis",
        "type": "Concept",
        "identifiers": [
          {
            "type": "Identifier",
            "identifierScheme": "mesh",
            "value": "D014376Q000517"
          }
        ]
      },
      "places": [
        {
          "label": "Paris",
          "type": "Place"
        }
      ],
      "periods": [
        {
          "label": "1850",
          "type": "Period"
        }
      ],
      "topics": [
        {
          "label": "prevention & control",
          "type": "Concept"
        }
      ],
      "genres": [
        {
          "label": "bibliography",
          "type": "Form"
        }
      ]
    },
    {
      "label": "Paris.",
      "type": "Subject",
      "concept": {
        "id": "hd2891f",
        "label": "Paris",
        "type": "Place",
        "identifiers": [
          {
            "type": "Identifier",
            "identifierScheme": "lcsh",
            "value": "sh014376Q000517"
          }
        ]
      }
    },
    {
      "label": "1820.",
      "type": "Subject",
      "concept": {
        "id": "hd2891f",
        "label": "1820",
        "type": "Period"
      }
    }
  ]
}

**Comment by silveroliver** [comment]
Looking for alternatives to "topics".

This work is about Tuberculosis and...

"topics" : "prevention & control"  or
"generalDivisions": "prevention & control"  or
"generalQualifiers": "prevention & control" 
"generalConcept": "prevention & control" 
"generalSubjects": "prevention & control"
"furtherQualifications": "prevention & control" 
"qualifers" : "prevention & control" 
"divisions" : "prevention & control" 
"descriptors" : "prevention & control"

**Comment by jtweed** [comment]
The more I think about this, the more I'm coming round to calling `concept` `primaryConcept` and `topics` `secondaryConcepts`. In an attempt to describe both the relationship from `Subject` and between the concept and general devisions.

**Comment by wilfox** [comment]
I’ve been looking at mads/skos and how Oslo Public Library deal with 650.
Oslo public library don’t catalogue anymore using marc records/use minimal marc records:

https://summit2017.lodlam.net/2017/04/12/oslo-public-library/

https://github.com/digibib/ls.ext/wiki/System-components-overview

Use of broader/narrower concepts looks popular… I am attempting to write some code using a narrower topic concept…

Mads example:
<authority>
<topic authority="lcsh">Computer programming</topic>
</authority>
<related type="broader">
<topic>Computers</topic>
</related>
<related type="narrower">
<topic>Programming languages</topic>
</related>
<related type="other">
<topic>Systems Analysis</topic>
</related>
</mads>

Oslo library example:
<http://data.deichman.no/subject/sjakk> a skos:Concept ;          (Main topical term: Chess)
skos:narrower <http://data.deichman.no/subject/x16878200> ;    (Chess – Periodicals)
skos:narrower <http://data.deichman.no/subject/x12784600> ;    (Chess – Endgame studies)
skos:narrower <http://data.deichman.no/subject/x12961800> ;    (Chess – Problems)
skos:narrower <http://data.deichman.no/subject/x15398200> .    (Chess – History)

Tania Williams
Library Assistant
Wellcome Library
Wellcome Trust
Gibbs Building
215 Euston Road
London NW1 2BE, UK
T +44 (0)20 7611 8500
F +44 (0)20 7611 8369
E t.williams@wellcome.ac.uk<mailto:t.williams@wellcome.ac.uk>
http://wellcomelibrary.org<http://wellcomelibrary.org/>

**Comment by silveroliver** [comment]
{
  "subjects": [
    {
      "label": "Tuberculosis - prevention & control -- Paris -- 1850 -- bibliography.",
      "type": "Subject",
      "primaryConcept": {
        "id": "hd2891f",
        "label": "Tuberculosis",
        "type": "Concept",
        "identifiers": [
          {
            "type": "Identifier",
            "identifierScheme": "mesh",
            "value": "D014376Q000517"
          }
        ]
      },
      "places": [
        {
          "label": "Paris",
          "type": "Place"
        }
      ],
      "periods": [
        {
          "label": "1850",
          "type": "Period"
        }
      ],
      "secoundaryConcepts": [
        {
          "label": "prevention & control",
          "type": "Concept"
        }
      ],
      "genres": [
        {
          "label": "bibliography",
          "type": "Form"
        }
      ]
    },
    {
      "label": "Paris.",
      "type": "Subject",
      "concept": {
        "id": "hd2891f",
        "label": "Paris",
        "type": "Place",
        "identifiers": [
          {
            "type": "Identifier",
            "identifierScheme": "lcsh",
            "value": "sh014376Q000517"
          }
        ]
      }
    },
    {
      "label": "1820.",
      "type": "Subject",
      "concept": {
        "id": "hd2891f",
        "label": "1820",
        "type": "Period"
      }
    }
  ]
}

**Comment by wilfox** [comment]
Thought I'd carry on and throw this into the mix  - I've made some new terminology suggestions often more than one for each term...

1. For all bibliographic records use "marcTag": "650".
2. If more than one subfield is populated. Populate platform "label" with concatenated subfields v, x, y, z in order, seperated by a double hyphen ' -- ' and type as "WholeConcept" or "EntireConcept" or "FullConcept".
3. If only "a" subfield is populated type as "MainConcept" or  "MainSubject"   or "MainTerm" or "MainTopic".
4. Populate platform "concept" "label" with subfield "a".
5. When this concept has associated identifiers populate "authority" with  value form subfield 0 and identity scheme from second indicator (0=lcsh   2=mesh) or if indicator 7 look at subfield 2 and populate  "authorityScheme".
6. For each subfield, for subfields v,x,y,z populate "related" with a "label", type "NarrowerConcept"  or "NarrowerTerm" (except subfield "y" type as "Period", "z" as "Place" and "v" as "Format") and populate "relatedType" with v=form-subdivision, x=general-subdivision, y=chronological-subdivsion,  z=geographic-subdivision.

"subjects": 
[                           
* {                            
* "label": "Tuberculosis - prevention & control.",                            * "type": "WholeConcept",                            
* "concept": {                            
* "id": "hd2891f",                            
* "label": "Tuberculosis",                            
* "type": "MainConcept",                            
* "identifiers": [                            
* {                            
* "type": "Authority",                            
* "AuthorityScheme": "mesh",                            
* "value": "D014376Q000517"                            
* }                            
* ],                            
* "related": [                            
* {                            
*"relatedType": "general-subdivision",                            
* "label": "prevention & control",                            
* "type": "NarrowerConcept"     
*     
* "relatedType": "geographic-subdivision.",     
*"label": "Paris",     
* "type": "Place"    
* 
*  "relatedType": "chronological-subdivision",     
* "label": "1850",     
* "type": "Period"    
*     
* "relatedType": "form-subdivision",     
* "label": "Bibliography",     
* "type": "Format"

**Comment by wilfox** [comment]
![image](https://user-images.githubusercontent.com/36954333/38315653-d18d23a4-3820-11e8-857a-a1935cb305f8.png)
