### ISSUE TITLE
We're exceeding SNS maximum message size

### ISSUE THREAD

**Issue by alicefuzier** [wellcometrust/platform#1776]
The id minter failed to send a message to SNS: ```com.amazonaws.services.sns.model.InvalidParameterException: Invalid parameter: Message too long (Service: AmazonSNS; Status Code: 400; Error Code: InvalidParameter; Request ID: 713d2d98-8ce1-5131-bd64-7ea6461406f5)```
It happened for bib record `b2043277x`, which does seem to have lots of items. As we add things to our transformations, we will exceed the limit earlier in the pipeline, so we need to decide how we address that.

- [x] Shared model
- [x] Pointer writer
- [x] Pointer reader

Move applications to use new messaging libraries:

- [x] `transformer` -> `id_minter` (#1944)
- [x] `id_minter` -> `ingestor`

**Comment by alexwlchan** [comment]
S3 Pointers for Queue Resizing?
