### ISSUE TITLE
Determine rules for matching physical and digital bibs

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#1779]

**Comment by wilfox** [comment]
[BOOK WITH MIRO IMAGES ATTACHED.xlsx](https://github.com/wellcometrust/platform/files/1927513/BOOK.WITH.MIRO.IMAGES.ATTACHED.xlsx)

**Comment by wilfox** [comment]
The document I uploaded was meant to demonstrate that the safest way to match as far as I can see  is by Author and Title and its variants.
If a Sierra bib record has a MIRO image attached to it then marctag 962 will be populated e.g.:
[cid:image002.png@01D3D7ED.C0A0C8E0]
Once you have all bib records with a populated 962 field then you can run Author and Title/Variant title matches against the image api and the bib records ?


Tania Williams
Library Assistant
Wellcome Library
Wellcome Trust
Gibbs Building
215 Euston Road
London NW1 2BE, UK
T +44 (0)20 7611 8500
F +44 (0)20 7611 8369
E t.williams@wellcome.ac.uk<mailto:t.williams@wellcome.ac.uk>
http://wellcomelibrary.org<http://wellcomelibrary.org/>

**Comment by jtweed** [comment]
This isn't about Miro and Sierra, this is about digitised bibs and matching them with their physical counterparts.

**Comment by wilfox** [comment]
Rules for matching E Book bibs with their Print book counterparts:

Use the contents of "Marctag":"776 w" from all "materialType" "e-book" bib records.
If the contents of subfield w contains the MARC organisation code (UkLW) in parentheses ignore this part of the code and use the remainder of the code, which starts with the letter b, to search for an exact match against "materialType" "Books" bibliographic record numbers. An exact match will identify the print counterpart to the E-book

Example:

(UkLW)b21414440 ignore (UkLW) and use the remainder of the code: b21414440 to search for an exact match against other bibliographic record numbers.

If the contents of subfield w contains the MARC organisation code (OCoLC) in parentheses use the entire code, including the code in parentheses and search for an exact match against the contents of "Marctag" : "035" in all "materialType" "Books" bibliographic records.  An exact match will identify the print counterpart to the E-book.

Example:

(OCoLC)14322288 use the entire code: (OCoLC)14322288 to search for an exact match against "Marctag" : "035" in other bibliographic records.
