### ISSUE TITLE
Decide how to quantify image similarity

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#1833]
### mapping the problem
- [x] find complex edge cases and determine scenarios where we want to return an exact match, and where we just want a similarity score. 
---
### working with work metadata
- [x] simple CNN text classifier
- [x] multi-modal CNN text classifier
- [x] word2vec and doc2vec on corpus

### working with raw images
- [x] simple similarity measures (keypoint, histogram, SSIM)
- [x] embedding with pre-trained network (eg inception, VGG)

**Comment by harrisonpim** [comment]
Deep ranking task moved to separate issue (#1957)
