### ISSUE TITLE
Notify ECR pushes in Slack

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/platform#1890]
(From retros)
This was done and immediately turned off because they were noisy.

Improvement suggestion: rather than a message for every Travis-initiated push, collect them all at the end.

**Comment by alexwlchan** [comment]
One thing the increased visibility is doing is exposing bugs in our Travis logic. For example, this should not be a thing:

> travis_ci has published a new dynamo_to_sns ZIP to S3.
> Git branch: HEAD (HEAD)
> Commit message: 'Merge pull request #1886 from wellcometrust/move-cloudfront-bucket'

Diff in https://github.com/wellcometrust/platform/pull/1886/files

**Comment by alexwlchan** [comment]
I’m going to close this now – I think they’ve got a bit more under control, especially now we don’t print the branch name and we’re a bit more careful about what we push, and when.
