### ISSUE TITLE
Broken derivatives

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/platform#1913]
These are showing up as grey boxes on https://wellcomecollection.org/works?page=2&query=herbal
Image of deer and fox: ujv54h5u
Title not found: tvmw57ht

**Comment by jtweed** [comment]
@harrisonpim Can you add finding all the grey box derivatives that have made it through to your analysis and list for the production team?

**Comment by alexwlchan** [comment]
![screen shot 2018-04-19 at 07 46 08](https://user-images.githubusercontent.com/301220/38975453-caf7955c-43a5-11e8-9114-8b2b44c7ce31.png)

**Comment by alexwlchan** [comment]
This probably isn’t the optimal way to do it, but I wanted to see if I could find it just using file sizes.

I picked <10KB as a heuristic for broken, and discovered we have some really small (but valid!) images – I assumed everything we kept was pretty big, but apparently not. Then I put in a request to Loris to see if they grey box.

I found six broken derivatives in the Catalogue API:

* L0013218EA.jpg
* L0013218EB.jpg
* L0019974.jpg
* L0029218.jpg
* L0029221.jpg
* M0008616.jpg

All six seem to be broken in assets-workingstorage, so they haven’t been mangled by the pipeline. I wonder if there are more broken derivatives there? Slightly more fiddly to inspect them, cos you have to go via the S3 APIs to access the files.

@harrisonpim Are you looking at just images from the Catalogue API, or the entire set of Miro derivatives?

Jupyter notebook and PDF output attached.

[find_broken_jpegs.ipynb.zip](https://github.com/wellcometrust/platform/files/1926938/find_broken_jpegs.ipynb.zip)
[find_broken_jpegs.pdf](https://github.com/wellcometrust/platform/files/1926939/find_broken_jpegs.pdf)

**Comment by kenoir** [comment]
I am guessing it is possible (though unlikely) that they were mangled in the copy between buckets.

**Comment by harrisonpim** [comment]
A (hopefully) very thorough approach to searching for bad/broken images has returned the same list as those found by Alex. Reassuring to see that two separate methods have returned the same set of results. 

Complete list of borked images on `/works` [here](
https://wellcomecollection.org/works?query=%27L0013218EA%27%2C+%27L0013218EB%27%2C+%27L0029218%27%2C+%27L0029221%27%2C+%27L0019974%27%2C+%27M0008616%27)

If anyone's interested, the approach used is roughly laid out below. Finds broken images by checking whether all pixel values in image are the same. If so, image displays as a uniform grey box.
```python
bad_image_ids = []

file_stream = BytesIO()
for url in tqdm(df['thumbnail_url']):
    image = Image.open(BytesIO(requests.get(url).content))
    image = img_to_array(image)
    if len(np.unique(image)) == 1:
        print('FOUND A BAD IMAGE:\t', url)
        bad_image_ids.append(url)
```

**Comment by pollecuttn** [comment]
@jtweed Were you going to recreate the derivatives for these six? If so can you reopen this ticket and track that here or open a new issue for it so it doesn't get forgotten.
