### ISSUE TITLE
Think about how to handle non backwards compatible changes in our internal model

### ISSUE THREAD

**Issue by alicefuzier** [wellcometrust/platform#198]
When we modify our internal model, we have to make sure that either:
- the changes are backwards compatible (ie. the items indexed in elasticsearch with the old model are also compliant with the new one
- or if not, we have to devise a strategy for rolling out changes that does not break the functionality for external users

As an example, if we have a model change that is not backwards compatible we run into a few issues:
- items already indexed in elasticsearch need to be reindexed 
- while items are being reindexed, old items in the old model cannot be deleted, as the api can only be switched to the new model once everything has been reindexed
- while we reindex items in the old model and in the new model cannot be mixed in the same datasource as the api will not be able to deal with both

**Comment by jamesgorrie** [comment]
I imagine this would have something to do with versioning to.

e.g.

__v1.0.0:__
```JSON
{ "name": "Monkeys in the jungle" }
```

__v1.1.0:__
```JSON
{ "name": "Monkeys in the jungle", "description": "They are spotted vervet monkeys in raincoats" }
```

__v1.1.1:__
```JSON
{ "name": "Monkeys in the jungle", "description": "They are spotted vervet monkeys in raincoats" }
```
Same but more performant

__v1.2.0:__
```JSON
{ "title": "Monkeys in the jungle", "name": "Monkeys in the jungle", "description": "They are spotted vervet monkeys in raincoats" }
```
Same but more performant


__v2.0.0:__
```JSON
{ "title": "Monkeys in the jungle", "description": "They are spotted vervet monkeys in raincoats" }
```

**Comment by alicefuzier** [comment]
Maybe? Don't know enough about elasticsearch to know what options it provides. If it has versioning that could be an option, I suppose?

**Comment by alexwlchan** [comment]
So judicious use of Elasticsearch will definitely help us here. I’ll need to review my notes, but there are tools for doing entire index transformation in such a way that it’s seamless to the end-user.

In practice, I think we do something like:

* Freeze updates to the existing Elasticsearch index
* Ingest everything into a new, empty index – either with Elasticsearch or by running the ingestor over the entire data set
* Point the API at the new index
* Delete the old index
* Point the ingestor to the new index, and unblock any updates that have been queued

This may play into when we choose to take updates – e.g. the Calm adapter runs for about 20 minutes at 7am on weekdays, so there aren’t any Calm changes during working hours.

**Comment by alexwlchan** [comment]
> If it has versioning that could be an option, I suppose?

Not per se, but you can get versioning either with:

* A user-defined metadata field, or
* An index swaperoo as described above

**Comment by alexwlchan** [comment]
We essentially ended up using the model above, with the additional cherry of a staging API that lets us preview the API with the new model while we’re still reindexing, and then flipping to the new index is just a matter of updating some ALB records.

This might get harder when we’re drawing from multiple sources, but for now I think this is done.
