### ISSUE TITLE
Return JSON error responses

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#213]
Details TBC, as part of the design guidelines.

**Comment by alexwlchan** [comment]
https://api.wellcomecollection.org/catalogue/v0/works?includes=foo

**Comment by alexwlchan** [comment]
Current model:

```json
{
    "type": "Error",
    "errorType": "http",
    "httpStatus": 404,
    "description": "Work xyzzy was not found"
}
```

We’ll need to do errors for, at least:

- 404 you looked up a bad work in Elasticsearch
- 400 you paged too far off the end, or 400 bad parameters (re-wrapping the Finatra responses)
- 500 Server error

**Comment by alexwlchan** [comment]
We also need to get the new Error type in the Swagger docs, where currently it doesn't appear.

**Comment by alexwlchan** [comment]
New Error type is in the Swagger docs, waiting on @kenoir for a deployment and publish to Stoplight.

**Comment by alexwlchan** [comment]
API docs are now in Stoplight, so closing as done.
