### ISSUE TITLE
Changes to location model 

### ISSUE THREAD

**Issue by silveroliver** [wellcometrust/platform#2131]
To be consistent with other type properties we need to make a change to the locationType.

Tasks:
Example JSON
Changes to transformation doc
Changes to model
Changes to model diagram

**Comment by silveroliver** [comment]
example json:

`   "locationType": {
        "id" : "sicon" ,
        "label" : "Iconographic Collection" , 
        "type" : "LocationType" 
  }`

**Comment by silveroliver** [comment]
Example json:

   "locationType": {
         "id" : "sicon" ,
         "label" : "Iconographic Collection" , 
         "type" : "LocationType" 
     }

**Comment by silveroliver** [comment]
Model, diagram and transform rule changed.
https://github.com/wellcometrust/platform/pull/2133

**Comment by alexwlchan** [comment]
Closed by #2133 and #2193.
