### ISSUE TITLE
Change to license type

### ISSUE THREAD

**Issue by silveroliver** [wellcometrust/platform#2132]
To be consistent with other type properties we need to make a change to the licenseType.

Tasks:
Example JSON
Changes to transformation doc
Changes to model
Changes to model diagram

**Comment by silveroliver** [comment]
Example json:

"licenseType": {
             "id" : "cc-by" ,
            "label" : "CC-BY" ,
           "type" : "LicenseType"
          } ,

**Comment by silveroliver** [comment]
Need to agree what the label and id look like for license type.

**Comment by jtweed** [comment]
So looking at this one, I'm not sure it's correct. It would leave license with no other properties.

I think in this case, there's no need for a license type and potentially what's currently in `licenseType` should be in `id` (though lowercased, I think we mistakenly made it uppercase before).

**Comment by silveroliver** [comment]
Becomes:
          "license": {
            "id": "CC-BY",
            "type": "License",
            "label": "Attribution 4.0 International (CC BY 4.0)",
            "url": "http://creativecommons.org/licenses/by/4.0/"
          }

**Comment by alexwlchan** [comment]
Closed by #2133 and #2150.
