### ISSUE TITLE
How to handle a second indicator " " for production function?

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#2281]
Spun out from #2252.

We use the second indicator of [MARC tag 264](https://www.loc.gov/marc/bibliographic/bd264.html) to decide the production function of a production event. The spec tells us how to handle 0–4, but some records have an empty space (` `) in this field. The transformer throws this as an error, because it doesn't know what to do.

What should we put for the production function?

**Comment by silveroliver** [comment]
Ignore. It is a production with unknown function.
