### ISSUE TITLE
Subjects being cut off in API

### ISSUE THREAD

**Issue by silveroliver** [wellcometrust/platform#2310]
This record shows the correct subjects for this work:
https://search.wellcomelibrary.org/iii/encore/record/C__Rb1174240?lang=eng&marcData=Y

650  0 Plants, Edible|xJava (Indonesia)|0sh 85102891 

In the API call for this:
https://api.wellcomecollection.org/catalogue/v2/works/ah28bwrz

It appears to be cutting off the end of Indonesia and the closing bracket. 

I haven't checked if this is an issue with the Sierra XML.

**Comment by alexwlchan** [comment]
This is the relevant blob of JSON from the Sierra API:

```json
        {
          "fieldTag": "d",
          "ind1": " ",
          "ind2": "0",
          "marcTag": "650",
          "subfields": [
            {
              "content": "Plants, Edible",
              "tag": "a"
            },
            {
              "content": "Java (Indonesia)",
              "tag": "x"
            },
            {
              "content": "sh 85102891",
              "tag": "0"
            }
          ]
        },
```

Doesn’t look like it’s being cut off there…

**Comment by pollecuttn** [comment]
There's two very similar records https://wellcomecollection.org/works/ah28bwrz and https://wellcomecollection.org/works/j357tpex which both point to http://search.wellcomelibrary.org/iii/encore/record/C__Rb1174240.

Subjects are only cut off in https://wellcomecollection.org/works/ah28bwrz

**Comment by alexwlchan** [comment]
Ah – the source identifier for ah28bwrz is a Miro identifier. Here's the relevant snippet of Miro JSON:

```json
    "image_keywords_unauth": [
      "SCIENTIFIC ILLUSTRATIONS",
      "CHROMOLITHOGRAPHS",
      "BOTANY - JAVA (INDONESIA)",
      "ISLAND FLORA",
      "PLANTS, EDIBLE - JAVA (INDONES",
      "PLANTS, USEFUL - JAVA (INDONES",
      "TROPICAL FRUIT"
    ],
```

This will be fixed when we merge Miro/Sierra records in a way that's compatible with V0042695, but there's nothing more we can do for now. We already know Miro subjects are a bit wonky, so I'm going to close this specific ticket.
