### ISSUE TITLE
Do we need to tweak the logic for subject transformations?

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#2332]
Looking at #2311, I think we might need to tweak the handling of MARC tag 610 in subjects. I’ve highlighted the relevant sentences:

```diff
-For "610" with sub-field "a" and "e" follow with x,y,v and z seperated by a dash.
+For "610" with sub-field "a", "b","c", "d" and "e" follow with x,y,v and z seperated by a dash.
```

Next time Silver is in the office, we should clarify this change and implement it if necessary.

**Comment by silveroliver** [comment]
This relates to providing more context when specifying a person. If you have a Jon Smith a date helps you know which one. It applies to both 610 (subject) but also contributors 100.

**Comment by kenoir** [comment]
Closing as 💀
