### ISSUE TITLE
Check that we are doing the right thing with images with GUS contributor code

### ISSUE THREAD

**Issue by alicefuzier** [wellcometrust/platform#2357]
There are 23  images with GUS contributor code that at some point ended up in the API.
* 9 of these we were asked to remove by Hannah:
```
B0009891
B0009897
B0009886
B0009893
B0009887
B0009895
B0009884
B0009890
B0009888
```
* Another 14 were in the API until #2212 was merged, which prevents all images with GUS contributor code to appear in the API:
```
B0009883
B0009885
B0009889
B0009892
B0009894
B0009896
B0010007
B0010008
B0010009
B0010010
B0010011
B0010012
B0010013
B0010014
```
I seem to understand that Hannah request came directly from the contributor who asked to remove the top 9, but not the others. 
Where has the decision to not show all GUS images come from? Is that the correct behaviour?

**Comment by alexwlchan** [comment]
I’ve asked Hannah to dig out Karen’s original email, so hopefully we'll get some answers that way.

**Comment by alexwlchan** [comment]
Looking at the original emails, we should have excluded just those nine records. 🙈

I’ll fix.
