### ISSUE TITLE
Perfect reindexes, with no failures

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#2361]

**Comment by alexwlchan** [comment]
### 10th July

The reindexer ran slowly because DynamoDB didn't scale up correctly.

20 records went to the reindexer DLQ. 347 records weren't indexed into Elasticsearch.

**Comment by alexwlchan** [comment]
### 11th July

We preset the DynamoDB capacity on the SourceData and recorder tables to the max, and disabled autoscaling. The reindexer ran much faster, and no new records ended up on the DLQ.

876 records went to the ingestor DLQ. 29 records went to the merger DLQ. 79 records weren't indexed into Elasticsearch.

**Comment by alexwlchan** [comment]
### 11th July (take 2)

DynamoDB was similarly preset to max capacity.

I’m reducing the max instances on the ingestor to 10 (see 88b9f2b).
