### ISSUE TITLE
modify input data and pre-processing for DeViSE model

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#2392]
- [x] obtain full-size imagenet
- [x] train model on full-size imagenet
- [x] preprocess wellcome data for training
- [x] *train existing model on additional wellcome images and metadata*
- [x] test on wellcome dataset
---
- [x] try training and testing on _only_ wellcome data
---
- [ ] train on [wikimedia images](https://commons.wikimedia.org/wiki/Category:Images) and their captions/metadata

**Comment by harrisonpim** [comment]
instead of training on the complete 1.5 TB of imagenet, it makes more sense to use a wide array of classes with a smaller number of images per class. for this, the validation sets of the ILSVRC are perfect candidates. 1000 classes, 50 images per class, http://www.image-net.org/challenges/LSVRC/
