### ISSUE TITLE
get distribution of book lengths (# pages) from METS

### ISSUE THREAD

**Issue by harrisonpim** [wellcometrust/platform#2536]

**Comment by pollecuttn** [comment]
Including average number of pages. This is for Jenn/Experience team to get an idea of what an 'average' book will look like if all the thumbnails are on a page.

**Comment by harrisonpim** [comment]
mean: 150.2
median: 47.7
max: 7705
<img width="1036" alt="screen shot 2018-08-13 at 11 12 00" src="https://user-images.githubusercontent.com/11006680/44026196-291b98fa-9eea-11e8-9870-644d4d8b61b9.png">

**Comment by pollecuttn** [comment]
@jennpb Harrison has got the mean and median averages from METS files.
