### ISSUE TITLE
Add MARC 610 subjects from Sierra

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#2556]
```
first indicator 0
-----------------
Concept [-- Concept ]-- Place -- Period
a       [-- b       ]-- c     -- d

first indicator 1 or 2
----------------------
Organisation [-- Concept ]-- Place -- Period
a b          [-- b       ]-- c       -- d
```

**Comment by silveroliver** [comment]
Proposal:

      /* Populate wwork:subjects organisation. Rules:
   * 
   * 1. For all bibliographic records use "marcTag": "610".
   * 2. Populate platform "label" from "610" concatenated with subfields a", "b", "c", "d", "e"  type as "Subject".
   * 3. Populate platform "concepts" "label" with subfield "a" and "b" type as "Organisation"
   * 4. If subfield 0 contains a value use it to populate "identifiers". For orgnisations the "identifierType" will be lc-names.
   *
   *
   *
   *
   *{
   *  "subjects": [
   *    {
   *      "label": "Wellcome Trust, sponsor.",
   *      "type": "Subject",
   *      "concepts": [
   *        {
   *          "id": "hd2891f",
   *          "label": "Wellcome Trust.",
   *          "type": "Organisation",
   *          "identifiers" : [
   *              {
   *              "indentifierType":
   *                 {
   *                 "id" : "lc-names" ,
   *                 "label" : "Library Of Congress Names" ,
   *                    "type" : "IdentifierType"
   *              } ,
   *              "value": "n81290903210",
   *              "type": "Identifier"
   *              }
   *        ] 
   *        }
   *      ]
   *    }
   *  ]
   *}
   */

**Comment by alexwlchan** [comment]
This is live! Example here:

https://search.wellcomelibrary.org/iii/encore/record/C__Rb1128518?marcData=Y&lang=eng
https://api.wellcomecollection.org/catalogue/v2/works/ecdebckk?include=identifiers,subjects
