### ISSUE TITLE
Storage service MVP

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/platform#2634]
In order to make the storage service available to clients for testing we need to ensure it can run an a bag ingest end to end with documented interfaces and error handling.

**Comment by jtweed** [comment]
TODO:

# Storage service testing

## API

### Common

- Should be on api.wellcomecollection.org, over SSL
- Should it really be going through Cloudfront?
- Should have a base path of `/storage/v1`, not `/prod/storage/v1`
- Swagger should be available at `/storage/v1/swagger.json`
- Context should be available at `/storage/v1/context.json`
- Errors should use same model as the Catalogue API
- We need to agree a plan for authentication

### Ingests

- POST should not return a response body
- POST should require `type`, `ingestType` and `uploadUrl` to be present
- Validation on `type` and `ingestType` (only support `create` for now)
- Incorrect serialisation of `uploadUrl` (also check `callbackUrl`)
- Change `createdAt` to `createdDate`
- Change `modifiedAt` to `lastModifiedDate`
- Valid `id`s for `IngestResult` are `success` and `failure`
- Add `description`containing any overall ingest status or error message
- Remove detailed `events` for now, we can add as an enhancement later
- Add a link to the bag that was affected by the ingest (property name TBD)

### Bags

- Serialisation shouldn’t create objects with values
- Generate an `id` for the bag, don’t use the source identifier
- Implement `source` to show the source of the bag
- Implement `identifiers` to include the external IDs supplied with the bag
- Suggestion: change `Manifest` to `FileManifest` to differentiate it from IIIF manifest
- Implement `tagManifest`
- Add `description` from bag info
- Add `size` from bag info
- Remove `version`, we can add as an enhancement later
- Suggestion: remove `locations` and replace with `archiveUrl`, `replicaUrl` and `accessUrl`

## S3

### Common

- Namespace by content type, i.e. `digitised` for digitised content from Goobi (note, we will have other types from Goobi)
- Shard using the same scheme as VHS
- Consider moving buckets to separate storage account

### Archive

- Change bucket name to `wellcomecollection-storage-archive`
- Lifecycle objects to Glacier storage

### Access

- Store access copy in bucket called `wellcomecollection-storage-access`

**Comment by alexwlchan** [comment]
Several things are ticked here which don't seem to be done – e.g. “Change createdAt to createdDate”. The Progress model still uses "createdAt" and "updatedAt".

Or is there something else I'm missing?

**Comment by kenoir** [comment]
Closing as subsumed by other tickets.

*Note*: Worth a check by @jtweed to check we haven't missed anything.
