### ISSUE TITLE
Matcher failures during indexing

### ISSUE THREAD

**Issue by mklander** [wellcometrust/platform#2644]
The matcher is failing to add some records during indexing, leaving them on the DLQ.

- [x] add additional logging

**Comment by mklander** [comment]
Additional logging indicates the problem is caused by works at a previously matched version being submitted with changed data.  All those I have seen want to remove the stored data:

`15:58:11.490 [main-actor-system-akka.actor.default-dispatcher-2] WARN u.a.wellcome.messaging.sqs.SQSStream - Graceful failure: update failed, work:sierra-system-number/b29333714 v2 already exists with different content! update-ids:Set() != existing-ids:Set(sierra-system-number/b12831487)`

  This is likely caused by the reindex now no longer incrementing the version number.

**Comment by alexwlchan** [comment]
We solved this by requiring an empty pipeline before you run a reindex.
