### ISSUE TITLE
Any unwanted assumptions in relationship between METS files and storage manifests?

### ISSUE THREAD

**Issue by tomcrane** [wellcometrust/platform#2648]
Scenario: given an identifier (e.g., `b12345678`), I want to make something that requires that identifier's METS file(s) and the contents of other files linked from the METS (such as METS-ALTO).

One instance of this scenario is creating an IIIF Manifest, given an identifier and the storage service API.

We need to make sure we know what assumptions we're making about how this will be consumed.

```
"files": [
    {
      "type": "File",
      "checksum": "a20eee40d609a0abeaf126bc7d50364921cc42ffacee3bf20b8d1c9b9c425d6f",
      "path": "data/b24923333.xml"      // << How do I know this is the METS file? Convention?
    },
    {..},
    {..},
    {
      "type": "File",
      "checksum": "17c0147413b0ba8099b000fc91f8bc4e67ce4f7d69fb5c2be632dfedb84aa502",
      "path": "data/alto/b24923333_001.xml"    
//     ^^^^ can I always infer this from METS? - xlink:href="alto/b24923333_001.xml"
    }
]
....

....
"locations": [
  {..},
  {..},
  {
    // how do I know I should get files from this location and not the others?
    // (what marks this as the access bucket? locationType.id?)
    "type": "DigitalLocation",
    "locationType": {
      "id": "aws-s3-standard-ia",
      "label": "AWS S3 Standard IA",
      "type": "LocationType"
    },
    "url": "s3://accessbucket/digitised/b24923333/"  // gives me the root
  }
]
```

Process:

1. Fetch the storage manifest for the given identifier.
2. Identify the METS entry in the storage manifest. How? Convention that the METS will have the path data/{identifier}.xml?
3. Fetch the METS file from S3 by concatenating the bucket url with the path (how do I know which bucket url to pick?)
4. Process the METS file, following links and fetching further files (e.g., manifestations, ALTO). 
I'm walking the METS XML structure, not the storage manifest. Links in the METS are relative to the current file. Can I assume that I know the S3 path of any file from its relative METS link, because that layout has been preserved in the bag? If I can't assume this, I need to find the path in the storage manifest. But then, what do I search for, besides path?

**Comment by kenoir** [comment]
Closing as 💀
