### ISSUE TITLE
Clean up our approach to config

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#2785]

**Comment by kenoir** [comment]
Closing as dupe of https://github.com/wellcometrust/platform/issues/2964 & https://github.com/wellcometrust/platform/issues/2968

**Comment by alexwlchan** [comment]
Re-opening and re-scoping to cover the config cleanups.

**Comment by alexwlchan** [comment]
Ah, it’s actually a dupe of #2967.
