### ISSUE TITLE
Architecture options for reporting pipeline

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#2818]
Extend existing reporting pipeline RFC.

See: https://github.com/wellcometrust/platform/tree/master/docs/rfcs/005-reporting_pipeline

**Comment by harrisonpim** [comment]
### work to do
- create dummy pipeline
- reindexer must publish to a particular topic
- create ES cluster
---
- easy reindexes
- queue visibility
- publish lambdas (platform build system)
- ES cluster (elastic cloud account)
