### ISSUE TITLE
Reporting transforms for Miro data

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#2823]

**Comment by harrisonpim** [comment]
## Empty fields
- all_psoft_export
- image_biomed_close_up
- image_corp_commissioned_by
- image_corp_contact_details
- image_corp_institution
- image_corp_keywords
- image_corp_photographer_freelance
- image_corp_purpose
- image_corp_shoot_sheet_number
- image_funding_type
- image_iap_invalid
- image_icd_note
- image_phys_notes
- image_source
- image_tech_manipulated_date
- image_tech_manipulated_date_from
- image_tech_manipulated_date_to
- image_web_img_filename
- image_web_img_size

## Sparse fields
- all_web_export
- image_batch_update_error
- image_dup_quantity
- image_int_default
- image_tech_file_format (all but 9 are TIFF, the others are blank)
- image_tech_manipulated_by
- image_wow_image

## Redundant fields, in which only one value exists and exists in every row
- _type
- _score
- _index
- all_draft
- image_iap_image_no (matches `_id` in all (?) cases)
- image_no_calc (matches `_id` in all (?) cases)

## Other stuff which we might want to update
- DD/MM/YYYY --> ISO date format for better alphabetrical sorting 
- Possibly unify some column values? image_cll has 'Early Printed Books' and 'EPB' values, for example, which might be an easy fix

**Comment by harrisonpim** [comment]
This has now ballooned into a much larger issue - getting all 360,000 records into a single VHS table which can be consumed by multiple pipelines and filtered safely) is going to take some work. The basic reporting transforms are in place though, so we can close this ticket and come back to it when the VHS, reindexer, and catalogue pipeline transformer have been reworked
