### ISSUE TITLE
Support Archivematica retrievals from storage service

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#2837]

**Comment by helenst** [comment]
Archivematica stores the bag external identifier and space ID when it sends a package to the storage service. It can retrieve details of the bag via the `GET /bags/<space-id>/<external-id>` endpoint, including its various storage locations. The "warm primary" copy on AWS S3 IA should be the one that is downloaded. This will need to be done through direct access to the bucket, so the Archivematica storage service will need permission to get objects from this bucket.

See https://github.com/wellcometrust/platform/tree/master/docs/rfcs/002-archival_storage
