### ISSUE TITLE
Miro-Sierra merger isn't copying across the iiif-image location

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#2928]
I discovered this when adding the image locationType filters, because the number of works with a iiif-image location is wrong.

Example:

* The V1 work for V0050621 has ID `kxmhfg3b` and a iiif-image location. See:

    https://api.wellcomecollection.org/catalogue/v1/works/kxmhfg3b?includes=identifiers,items

* Getting `kxmhfg3b` from the V2 API gives you a redirect to `zyfja4rd`

    ```console
    $ curl -v "https://api.wellcomecollection.org/catalogue/v2/works/kxmhfg3b"
    < HTTP/1.1 302 Found
    < Location: /catalogue/v2/works/zyfja4rd
    ```

* The V2 work `kxmhfg3b` has the V0050621 Miro identifier, but no iiid-image location. See:

    https://api.wellcomecollection.org/catalogue/v2/works/zyfja4rd?include=identifiers,items

**Comment by jtweed** [comment]
Closing as not a bug. It has correctly taken the digitised image that came through the digitisation workflow.

**Comment by alexwlchan** [comment]
Working As Designed, I just didn't realise this is how the merger was meant to work. :P
