### ISSUE TITLE
Changes to merging rules for digitised Sierra/Miro works

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#2994]
We have a slight issue with the Sierra data...

Miro works that have been matched to digitised Sierra works do not have thumbnails, which means they cannot be displayed in search results.

To fix this properly, we should add a thumbnail that points to DLCS for these. However, we can't do this until we migrate to the new storage service as DLCS uses the GUIDs from Preservica, which we do not have without ingesting the METS data...

So my proposal for now, which we will back out when we are able to do so in a few months:

* Miro locations should be copied across when merging to digitised Sierra works, not the Sierra location
* Miro thumbnails should be copied across when merging to Sierra digitised works

**Comment by tomcrane** [comment]
If you have a b number for the work, I could very easily add an endpoint to the DDS that redirects to the thumbnail on the DLCS - e.g., /service/thumb/b12345678.jpg

The DDS knows the Preservica GUID of the first image of any digitised b number, it uses it for a very similar purpose, to add thumbnails to manifests in IIIF Collections, e.g., https://wellcomelibrary.org/service/collections/genres/Clippings/

**Comment by tomcrane** [comment]
(or proxies it)
