### ISSUE TITLE
Subjects/genres/contributors normalisation

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3046]
For all data sources, on `Person`, `Organisation`, `Agent`, `Concept`, `Place`, `Period`, `Subject` and `Genre`:

* Remove trailing punctuation from `label` 

For Miro, on `Concept`, `Subject` and `Genre`:

* Normalise `label` to sentence case

**Comment by mklander** [comment]
Is punctuation to include just full stops and commas?  What about abbreviations and contractions, for example: `...` `&Co.` `B.C.` `etc.`

**Comment by jtweed** [comment]
on person remove trailing `.`
on period remove trailing `.`
on place remove trailing ` :`
on concept remove trailing `.`

**Comment by mklander** [comment]
Objects can be created, such as Organisation/Subject/Genre as a compound of multiple Marc/Miro fields.  In these cases which rules should apply to each part of the compound label?

For example 610 bib data creates an Organisation with a label from MarcSubfields a & b.

A Miro subject label is created from multiple keywords from `image_keywords` and/or `image_keywords_unauth`.

**Comment by jtweed** [comment]
I think for Organisation, we should combine and then remove trailing punctuation from the combined label.

For subjects, we should normalise each part, then combine.

**Comment by jtweed** [comment]
Nothing for Sierra, sentence case for Miro
