### ISSUE TITLE
Run Dockerfile builds in Travis

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/platform#3065]
For all necessary archivematica services.

**Comment by alexwlchan** [comment]
Travis is now building the images (so it’ll fail a pull request if we push an unbuildable image).

Getting it to publish them is tricker:

* The archivematica repo is set up to publish with an assumed role, not direct credentials
* The users we have set up so far get every role, which we don't want to do for Travis
* Creating a new role just for Travis in platform-private seems like it should work, but I'm having issues getting that to work alongside my own platform-admin role

A quick job, he said…

**Comment by alexwlchan** [comment]
There's a terraform-modules patch here: https://github.com/wellcometrust/terraform-modules/pull/145

And actually applying it to the account here: https://github.com/wellcometrust/platform-private/pull/40

I think I’ve created the role; now I need to create a user who only has access to that role.

**Comment by alexwlchan** [comment]
And this works!
