### ISSUE TITLE
Add ISBNs from Sierra

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3151]
Team #dotorg have asked us to add ISBNs from Sierra.

These come from MARC `020`, subfield `$a` and should be added as identifiers with type:

- id: `isbn`
- label `International Standard Book Number`

---

New transformation checklist:

- [x] Make code change (#3337)
- [x] Deploy new transformer
- [x] Start a reindex
- [x] Check the reindex completed
- [ ] Update the production API index

**Comment by pollecuttn** [comment]
@jennpb

**Comment by alexwlchan** [comment]
Reindex ran; three Sierra records landed on a DLQ:

* 24/3087342/7444adcf3b7d4e047f7310a6ed1ebd352252128116a2c645d7bf8efb8e13c448
* 27/3076072/eb22c3f548ade1641f58e911e15aacead945d02e0bd91805831cd7ec4f819de4
* 91/3086019/91d6fb6bdb6fb66058c91d983540f34cf96684b7a383e8bca752f5bce14d0d1a

I don’t think these are related to the ISBN stuff; I’m also not going to divert from Archivematica to investigate further.

**Comment by alexwlchan** [comment]
I had a look at the MARC – two are records that have a 260 and a 264 field, the third is a test record that looks like it should be suppressed. I’ve flagged both to Branwen for fixing.

**Comment by alexwlchan** [comment]
As such, I think this is ready to go, but I’m not about to make an API change at 5pm on a Friday!
