### ISSUE TITLE
copy `_id` field to `id` field

### ISSUE THREAD

**Issue by harrisonpim** [wellcometrust/platform#3155]
from Christy
> In the Kabana search tool, if a record is in the repository "miro_inventory" should it by definition also be in the repository "miro"? Because I can find this L number in miro_inventory, but not in miro (I'm trying to see what additional rights information might be in the original miro record" L0071807.

The record does exist, but is only reachable by searching for `_id:L0071807`. We think this is because the `_id` field isn't used in the standard ES search, so records which don't store the miro id elsewhere won't appear, unless that `_id` field is specified by the user.

Creating a copy of the `_id` field in a new `id` field will expose it to the search, allowing people to retrieve records for items with the id alone

**Comment by jtweed** [comment]
How does this sit with image_no_calc? Surely we should just make sure that is always populated?
