### ISSUE TITLE
Archivematica support for OpenID Connect Authentication

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3261]
In order to authenticate with Azure AD as a modern "enterprise application" Archivematica should support [OpenID Connect (OIDC)](https://en.wikipedia.org/wiki/OpenID_Connect).

This will enable us to add Archivematica as a registered app with Azure AD as part of SSO at Wellcome.

Dashboard tasks:
- [x] Integrate custom backend to authenticate OIDC users
- [x] Map OIDC token attributes to email, first and last name and username fields on new user object
- [x] Make field mapping configurable
- [x] Ensure API key is generated for newly created user
- [x] Allow app to receive settings as env vars
- [x] Update Terraform to set env vars
- [x] Ensure logout works
- [x] Prevent editing of user details (since these are set by external data from OIDC)
- [x] Set up as conditional authentication backend, similar to Shibboleth and LDAP
- [x] Ensure custom backend is fully tested
- [x] Either create fork or override token handling so that 'alg' is optional in response (this was fixed in a later version of `mozilla-django-oidc` that we can't use because of Django version)
- [x] Add link to oidc login from main login page

Storage service tasks:
- [x] Integrate custom backend to authenticate OIDC users
- [x] Map OIDC token attributes to email, first and last name and username fields on new user object
- [x] Make field mapping configurable
- [x] Ensure API key is generated for newly created user
- [x] Allow app to receive settings as env vars
- [x] Update Terraform to set env vars
- [x] Ensure logout works
- [x] Prevent editing of user details (since these are set by external data from OIDC)
- [x] Set up as conditional authentication backend, similar to Shibboleth and LDAP
- [x] Ensure custom backend is fully tested
- [x] Either create fork or override token handling so that 'alg' is optional in response (this was fixed in a later version of `mozilla-django-oidc` that we can't use because of Django version)
- [x] Add link to oidc login from main login page

**Comment by helenst** [comment]
Support for LDAP authentication is built in to Archivematica.

To use this, we will need some information:

* LDAP Server URI (e.g. "ldap://ldap.example.com") and port number - it will need to be accessible from the dashboard and storage service on that port.

Authentication details for an account which is able to search the LDAP server:
* Bind DN (e.g. "cn=authorized-user,dc=example,dc=com")
* Bind password

For user lookup during login:
* Base DN (e.g. "dc=example,dc=com") in which users can be searched
* Names of fields for:
  - unique username (what the user would type in to a login form)
  - first name
  - last name
  - email address

**Comment by helenst** [comment]
There are various OpenID-connect libs for Django but Archivematica runs on an old (1.8) version of Django so this could be a limitation.

https://pypi.org/project/django-auth-oidc/ says in its docs that it supports Django 1.8+ but its requirements specify `>=2.0.0`

https://github.com/mozilla/mozilla-django-oidc requires `>=1.11`

**Comment by helenst** [comment]
https://github.com/rohe/pyoidc won't help us out as it's python 3 only

There are a couple of others (found on https://djangopackages.org/grids/g/oidc/) that are older - possibly too old. Or it may be worth trying to run an older version of one of the above libs, to make it a bit easier to upgrade when Archivematica eventually moves to a new Django version.

**Comment by helenst** [comment]
I am working with `mozilla-django-oidc==1.0.0` for now, which is the last release before Django 1.8 support was dropped. There have been one or two fixes to that lib since that version which we might need, so forking is probably a good idea.

Currently I have most of the authentication flow working, it's failing on the last step (`user_info` call) I think due to some tokens being in the wrong format. Am investigating this.

**Comment by helenst** [comment]
@jtweed Do we want this for the Archivematica storage service as well as the Dashboard? (Implementation should be pretty similar)
