### ISSUE TITLE
Move subject IDs to subject

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3265]
Based on a misunderstanding of LC names and LCSH, we are currently adding the ID on subject fields to the first concept in the concepts list.

This is sometimes the case, but sometimes the ID is of a ComplexSubject in LC that is made of the separate concepts in the list, each of which then have their own IDs.

We can't fully solve this until we bring in LC names and LCSH, so in the meantime, let's move the ID from the first concept to the subject itself.

---

New transformation checklist:

- [x] Make code change (#3352)
- [x] Deploy new transformer
- [x] Start a reindex
- [x] Check the reindex completed
- [x] Update the production API index

**Comment by alexwlchan** [comment]
This is turning into a much more involved patch than I originally realised. 🤯

**Comment by jamesgorrie** [comment]
Just to be clear, we'll be moving from:
```JSON
{
	"subjects": [{
			"label": "Human skeleton.",
			"concepts": [{
				"id": "vegjfgd8",
				"label": "Human skeleton.",
				"type": "Concept"
			}],
			"type": "Subject"
		},
		{
			"label": "Anatomical specimens.",
			"concepts": [{
				"id": "k43gjbuy",
				"label": "Anatomical specimens.",
				"type": "Concept"
			}],
			"type": "Subject"
		},
		{
			"label": "Anatomy, Pathological.",
			"concepts": [{
				"id": "yx7v4jrq",
				"label": "Anatomy, Pathological.",
				"type": "Concept"
			}],
			"type": "Subject"
		}
	]
}
```

to 

```JSON
{
	"subjects": [{
			"label": "Human skeleton.",
		 	"id": "vegjfgd8",
			"concepts": [{
				"id": "vegjfgd8",
				"label": "Human skeleton.",
				"type": "Concept"
			}],
			"type": "Subject"
		},
		{
			"label": "Anatomical specimens.",
                         "id": "k43gjbuy",
			"concepts": [{
				"label": "Anatomical specimens.",
				"type": "Concept"
			}],
			"type": "Subject"
		},
		{
			"label": "Anatomy, Pathological.",
                         "id": "yx7v4jrq",
			"concepts": [{
				"label": "Anatomy, Pathological.",
				"type": "Concept"
			}],
			"type": "Subject"
		}
	]
}
```

Looking at it - I am assuming those are our IDs?

**Comment by alexwlchan** [comment]
@jamesgorrie Yes.

The door is open for "id" to reappear on Concept at some point, but once this is applied you won't see an identified Concept in a subject for a while.
