### ISSUE TITLE
Complete 100% bagging without error

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3322]
In order to ensure that we are prepared for a 100% clean run  (and what that means)  we should:

- [x] Deploy latest services to prod (deploy latest images - @alexwlchan can assist)
- [x] Ensure the production environment is "cleaned up":
  - Make METS up to date (@jtweed can assist)
  - Clear prod dynamo tables (delete all rows - @alexwlchan can assist):
    - arn:aws:dynamodb:eu-west-1:975596993436:table/storage-migration-status
    - arn:aws:dynamodb:eu-west-1:975596993436:table/storage-ingests
    - arn:aws:dynamodb:eu-west-1:975596993436:table/vhs-storage-manifests
  - Clear prod S3 buckets (delete all objects - @alexwlchan can assist):
    - arn:aws:s3:::wellcomecollection-vhs-storage-manifests
    - arn:aws:s3:::wellcomecollection-storage-bagger-errors
    - arn:aws:s3:::wellcomecollection-storage-bagger-drop
    - arn:aws:s3:::wellcomecollection-storage-ingests
    - arn:aws:s3:::wellcomecollection-storage-access
    - arn:aws:s3:::wellcomecollection-storage-archive 
  - Populate `storage-migration-status` table
    - Run `./migtool.sh ensure-population`  (@alexwlchan / @mklander  can assist)
- [ ] Bag a known range: `./queue_for_bagging.sh x/1 bag`
- [ ] Review errors in dashboard for that range: `http://wt-havana:88/Dash/Migration/`
- [ ] Work with Christie and @tomcrane to discover root cause of issue and how production team can resolve.

** All data errors should fit into known classed and be recorded for resolution by production team **

**Comment by alexwlchan** [comment]
Bucket clearance in progress, but it’ll take a while…

**Comment by alexwlchan** [comment]
We've run `5/`, `6/`, `7/`, `8/` and `9/`, and the errors are being reviewed. `4/` is up next.

**Comment by pollecuttn** [comment]
Alex: I’m populating the dashboard with `4/`
And sending `3/` into the queue

**Comment by pollecuttn** [comment]
@alexwlchan @mklander are `1/`, `2/`, `0/` still to be run? Would there be a `x/` as well?
