### ISSUE TITLE
Library Site (DDS/DLCS) Synchronisation

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3324]
In order that we migrate all content to be available to the library site in a timely fashion we need to:

- [x] Ensure DLCS in AWS is scaled up to process entire queue ASAP (by 17/10/19)
- [x] Add as many DDS WorkflowProcessors as is efficient to on-prem infra.
- [x] Complete migration checks https://github.com/wellcometrust/platform/issues/3328
- [x] Plan Goobi switch on for 21st October.
- [x] ~Plan prod DDS/DLCS app to UAT database  switchover for 23rd October.~
- [x] Determine schedule for prod DDS/DLCS app to UAT database releasing with regard to library SSO issues.
- [x] Determine schedule for UAT to prod DDS database migration.
- [x] Resolve outstanding issues where necessary: https://github.com/wellcometrust/platform/issues/3957

**Comment by pollecuttn** [comment]
Tue 29: switchover to using UAT/storage service
Check wellcomelibrary.org and wellcomecollection.org
Wed: 30 tell Intranda we want to flip 
Thu 31: tell Goobi to switch 
Mon 4:
