### ISSUE TITLE
Get a histogram of the number of images in each iiif-presentation manifest we surface

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#3370]
The #dotorg team would like a breakdown of the number of images per IIIF Presentation manifest we present in the Catalogue API.

The naive approach would be to go through an API dump, then fetch the ~238k manifests individually – but I suspect there’s a faster way using the reporting pipeline.

**Comment by jamesgorrie** [comment]
We've decided that expert knowledge on the catalogue and assumptions based on that would be fine.
Happy for this to be closed.

**Comment by harrisonpim** [comment]
here's the histogram, if you still want it! 

![histogram](https://user-images.githubusercontent.com/11006680/51844955-702ca880-230e-11e9-8916-ecdc39746e59.png)

Also have a branch containing the script which generates it in `/works_analysis`
