### ISSUE TITLE
POST to Wellcome storage service with pointer to S3 file

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/platform#3385]

**Comment by helenst** [comment]
The first problem encountered when trying to do this is that by default Archivematica generates AIPs in 7z/bzip2 format, which is not supported by the Wellcome Storage Service.

Two possible approaches:
1. Adapt the Storage Service to accept .7z files (or another format natively supported by Archivematica)
2. Adapt Archivematica to support zip files which the Storage Service back end (using java.util.zip.ZipFile) is able to accept.

Archivematica has the following options for AIP compression:
* 7zip with bzip2
* 7zip with lzma
* 7zip without compression
* Uncompressed 
* Parallel bzip2

To add support for other compression methods would require a data migration to add the option to the workflow, and code in the `compress_aip` method to invoke the compression command. `gzip` is already available in the MCP Client container where the compression would run, but `zip` is not.

**Comment by kenoir** [comment]
I think we'd prefer to make Archivematica compatible is possible. What does "Uncompressed" do?

**Comment by helenst** [comment]
It means no command is run during that step - so it remains as a directory.

**Comment by helenst** [comment]
Tasks:
- [ ] Support compressing AIPs with zip/deflate
- [ ] Add `unzip` command to container so `atool` can decompress during verify AIP step
- [ ] Add missing fields to bag-info.txt: `external-identifier`, `source-organisation`, `bagging-date`

**Comment by helenst** [comment]
We need to determine which of the missing fields we need to add to the bag info file. The bag spec doesn't require any of them, but the storage service does.

As far as I can tell, the [bagit-java](https://github.com/LibraryOfCongress/bagit-java) tool currently used by the archivematica pipeline to generate AIPs, doesn't appear to support specifying these fields, although it does support supplying an externally generated bag-info file.

[bagit-python](https://github.com/LibraryOfCongress/bagit-python) does, and could be used as a replacement although may require a little manipulation of directories to get it to generate in the same directory structure as the original tool.

If we need to add any extra fields to the bag info file (regardless of which ones they are) this will need to be addressed.

**Comment by helenst** [comment]
AM issue for external identifiers: https://github.com/archivematica/Issues/issues/492

**Comment by helenst** [comment]
AM issue for zip/definate: https://github.com/archivematica/Issues/issues/493

**Comment by helenst** [comment]
AM PR for zip/deflate: https://github.com/artefactual/archivematica/pull/1346

**Comment by helenst** [comment]
The completion of this task is blocked on a couple of issues in the storage service:
1. making `Source-Organization` optional (https://github.com/wellcometrust/platform/pull/3427)
2. supporting the bag existing inside a top level directory within the zip file. (https://github.com/wellcometrust/platform/pull/3434)

I modified an AM-generated zip to prevent the storage service erroring on these two issues and posted it to see if any more issues came up, and it went through. Once those are fixed, it should be possible to upload a bag from the AM workflow into the storage service and then continue with https://github.com/wellcometrust/platform/issues/3386

**Comment by helenst** [comment]
AM PR for external identifiers: https://github.com/artefactual/archivematica/pull/1347
