### ISSUE TITLE
Store bag ID against the package

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/platform#3386]

**Comment by helenst** [comment]
This involves setting up an API endpoint that the Wellcome storage service can notify when it has a successful or failed result for the ingest. On success, the bag ID is extracted and written to the `Package` object.

A couple of things to note here:

1. The Wellcome storage service doesn't currently retry the callback if it failed. It's possible the callback will be missed, e.g. if Archivematica is temporarily unvailable. So if the callback hasn't been requested after a little while (say a minute) we check the ingest URL to see whether the ingest is complete and the callback was attempted. If it was, we use the result from the ingest body. This isn't ideal but is better than waiting forever for the result.

2. The callback endpoint requires authenticatoin. The AM storage service supports authentication via API key, which can be included in an Authorization header or as a URL parameter. Using a URL parameter means the callback can be set up with no modification, however it means the API key is more exposed, e.g. in logs or in the ingest JSON. Sending it as a header would be better in that regard but would likely also require extra work on the Wellcome storage service to support this.

3. Just storing the bag ID for now. May be useful to also store the ingest ID.

I've made a first pass at an implementation of this on the `wellcome-storage-service` branch but it still needs a few refinements.
