### ISSUE TITLE
Bag validation incorrectly failing

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3397]
Bag transfer validation is failing when Archivematica doesn't like certain characters in a filename. It looks like it's comparing a changed filename with the manifest, which means it thinks the affected file is not in the manifest, when it actually is.

Example:

```
Job: SAHNS_2460
Task: ab079eea-5fb0-4bf2-89ca-bea577a10ee1

Result is false.
(error) Payload file data/The Big 30 Archive/Big 30 website stories/Big 30 Website ? Challenging Stereotypes ? Short ? Transcript.docx not found in any payload manifest.
Complete results written to /SAHNS_2460-35d9213b-4623-4b1f-bb49-d16bb56087b9-verifyvalid-20190201-17:27:15.txt
Result is false.
(error) Payload file data/The Big 30 Archive/Big 30 website stories/Big 30 Website ? Challenging Stereotypes ? Short ? Transcript.docx not found in any payload manifest.
Complete results written to /SAHNS_2460-35d9213b-4623-4b1f-bb49-d16bb56087b9-verifycomplete-20190201-17:27:23.txt
Result is true.
Passed test: %s ['/usr/share/bagit/bin/bag', 'verifypayloadmanifests', '/var/archivematica/sharedDirectory/currentlyProcessing/SAHNS_2460-35d9213b-4623-4b1f-bb49-d16bb56087b9/']
Payload-Oxum matches.
Passed test: %s ['/usr/share/bagit/bin/bag', 'checkpayloadoxum', '/var/archivematica/sharedDirectory/currentlyProcessing/SAHNS_2460-35d9213b-4623-4b1f-bb49-d16bb56087b9/']
Result is true.
Passed test: %s ['/usr/share/bagit/bin/bag', 'verifytagmanifests', '/var/archivematica/sharedDirectory/currentlyProcessing/SAHNS_2460-35d9213b-4623-4b1f-bb49-d16bb56087b9/']

Failed test: %s ['/usr/share/bagit/bin/bag', 'verifyvalid', '/var/archivematica/sharedDirectory/currentlyProcessing/SAHNS_2460-35d9213b-4623-4b1f-bb49-d16bb56087b9/']
Failed test: %s ['/usr/share/bagit/bin/bag', 'verifycomplete', '/var/archivematica/sharedDirectory/currentlyProcessing/SAHNS_2460-35d9213b-4623-4b1f-bb49-d16bb56087b9/']
Failed bagit compliance. Not restructuring.
```

**Comment by helenst** [comment]
What was the original filename? I'm struggling to reproduce this locally, it might be that I'm not getting the right kind of filename to trigger the bug. I can see the failure on the deployed archivematica instance but not access the original bag and see the filename / manifest.

**Comment by pollecuttn** [comment]
Not sure if @jtweed has seen this

**Comment by helenst** [comment]
Having got hold of the original zip file and created a smaller bag including the file in question (with original name), I'm still unable to reproduce on my local setup (even when rolling back to AM 1.8). I'm going to take a closer look at the commands that it's running to see if I can spot any difference.

**Comment by helenst** [comment]
The smaller bag fails at the same point on deployed archivematica. This means:
(a) we have a smaller file with which to reproduce this failure rather than the full 23GB original
(b) the same file is failing on deployed version but succeeding locally, even when the local version is rolled back to 1.8 (same as deployed).

It may be some difference between the two environments that is causing this.

**Comment by helenst** [comment]
After poking around on the AWS docker containers and comparing to my local one, there appears to be a difference in the way 7z extracts those filenames:

`Big 30 Website ? Challenging Stereotypes ? Short ? Transcript.docx` on AWS docker container, vs `Big 30 Website – Challenging Stereotypes – Short – Transcript.docx`

7z on AWS gives the following configuration details:
```
7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=C,Utf16=off,HugeFiles=on,64 bits,2 CPUs Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (406F1),ASM,AES-NI)
```

vs. on local docker container:

```
7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,1 CPU Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (806EA),ASM,AES-NI)
```

The difference being in the locale and UTF-16 settings.

(Note that I'm using Artefactual's compose environment locally)

**Comment by helenst** [comment]
Locale needs to be set on the mcp-client container by installing the `locale` package and running a `locale-gen` command. I tried this temporarily on the AWS container and it works.

The supplied MCPClient docker file (which is brought into the compose environment) does this.

`https://github.com/artefactual/archivematica/blob/e240825332b76f3cc50b66646921fd9b1ab84d4b/src/MCPClient-base.Dockerfile#L19`

The current deployment to AWS installs packages using apt, and that install process does not appear to run these steps.

**Comment by helenst** [comment]
It's possible #3396 is related to this too.

**Comment by helenst** [comment]
(It is.)

Also seems to be similar to https://github.com/archivematica/Issues/issues/506 / https://github.com/artefactual-labs/am-packbuild/pull/218 - it looks like locale setup is being included in the installation of the standard AM packages so should also be considered in https://github.com/wellcometrust/platform/issues/3465

**Comment by helenst** [comment]
I've re-run the original transfer on deployed Archivematica and it succeeds.
