### ISSUE TITLE
Strange identify file format failures

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3398]
Seeing a couple of strange file format identification failures.

First, claiming a PRONOM id doesn't exist (when it does):

```
Job: SAACT_2433
Task: 67dbbe03-7f00-444d-a036-5f868bcb44a3

IDCommand UUID: 75290b14-2931-455f-bdde-3b4b3f8b7f15
File: (0b245643-c3d9-4649-8ef2-71218ac2a93c) /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/selectFormatIDToolTransfer/SAACT_2433-c4d39e9e-9d9f-4bb4-98a7-1ef6b153f5bc/objects/Thumbs.db
Command output: fmt/111

Error: No FPR format record found for PUID fmt/111
```

Second, no idea:

```
Job: SANCT_2367
Task: 00293fdd-3014-4cad-9451-1b68ac84300a

IDCommand UUID: 75290b14-2931-455f-bdde-3b4b3f8b7f15
File: (fdc7fc77-cf68-4ab8-ae1d-75fb9c100f7b) /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/selectFormatIDToolTransfer/SANCT_2367-06a28446-7530-4f85-b41e-6aa9402aa679/objects/[REDACTED]/conversation_1_17.1.12-edit-copy_data/e00/d00/e0000cea.au

Error: IDCommand with UUID 75290b14-2931-455f-bdde-3b4b3f8b7f15 exited non-zero.

```

**Comment by helenst** [comment]
`Thumbs.db` is being identified by siegfried as PRONOM format `fmt/111` which is "OLE2 Compound Document Format"

In the `import_pronom_ids` command this is intentionally excluded from the fpr database tables with the following comment:

> Many Windows file formats that aren't otherwise IDed will be identified as this. We choose not to import this one ID in order to allow Archivematica to recognize those files as unidentified instead of returning something misleading.

It might be worth noting that by default Archivematica ignores/removes Thumbs.db for a non-bagged transfer.

**Comment by helenst** [comment]
For the second one, running siegfried manually against that file:

```
matches  :
  - ns      : 'pronom'
    id      : 'UNKNOWN'
    format  : 
    version : 
    mime    : 
    basis   : 
    warning : 'no match; possibilities based on extension are x-fmt/139'
```

**Comment by helenst** [comment]
The wrapper script around siegfried reports this as a return status of 1. So it's saying that it can't identify that file type.

**Comment by helenst** [comment]
I've made a fix so that the stderr output from the identification command makes it into the job output.

**Comment by helenst** [comment]
@jtweed I've identified what's going on here and made the error output visible in the second case. Are you happy with this, or do you think there is work to be done (either now or later on) around the actual identification of those files?

**Comment by jtweed** [comment]
Thanks, happy to close this. Archivematica removing fmt/111 explains it.
