### ISSUE TITLE
Bag replicator is putting messages on the DLQ that seem to complete successfully

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#3458]
As of right now, there are eight messages on the bag replicator DLQ (a couple of duplicate IDs). At a casual glance, the bag replicator has successfully copied all the objects for each bag (the numbers are correct, at least), so it’s not clear why it’s failed.

```
   12273 b2146201x_access.txt
   12273 b2146201x_archive.txt
   11638 b2150751x_access.txt
   11638 b2150751x_archive.txt
   11232 b2475092x_access.txt
   11232 b2475092x_archive.txt
   62700 b2475772x_access.txt
   62700 b2475772x_archive.txt
      18 b24962648_access.txt
      18 b24962648_archive.txt
   10806 b2877212x_access.txt
   10806 b2877212x_archive.txt
```

If it wasn't for b24962648, I’d wonder if we’re just timing out the messages? Not sure why that  particular bag fell over.

**Comment by pollecuttn** [comment]
@alexwlchan Can this be closed?

**Comment by alexwlchan** [comment]
@pollecuttn I want to leave it a few more days and check it doesn't crop up; it's a transient issue so hard to know for sure if/when it's fixed!
