### ISSUE TITLE
Redirect on catalogue API going to localhost:8888

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/platform#3470]
James noticed that https://api.wellcomecollection.org/catalogue/v2/works/m66pav3d should redirect to https://api.wellcomecollection.org/catalogue/v2/works/pusr37n3.

Instead it is redirecting to https://localhost:8888/catalogue/v2/works/pusr37n3

**Comment by alexwlchan** [comment]
Fixed in https://github.com/wellcometrust/catalogue/pull/17, needs deployment

**Comment by alexwlchan** [comment]
I've deployed this to stage and it's 500'ing; I'll dig into it more later.

**Comment by alexwlchan** [comment]
I have a newer fix for this in https://github.com/wellcometrust/catalogue/pull/20, and it’s deployed to live.

**Comment by pollecuttn** [comment]
@alexwlchan So can this be closed now?

**Comment by alexwlchan** [comment]
@pollecuttn Not until the code is reviewed and merged.
