### ISSUE TITLE
Modify the storage manifest to return "locations", not "accessLocation" and "archiveLocations"

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#3475]
See #3414, #3451. We should update the services to reflect the new formats!

**Comment by alexwlchan** [comment]
I think this needs coordinating with DLCS and DDS? So I wonder if we should do this in two parts:

* Add `"locations"` but don't remove the old fields
* Remove the old fields after DDS is using the new ones

**Comment by tomcrane** [comment]
I can update that pretty quickly and get it deployed - maybe switch next Thursday when I'm in?
