### ISSUE TITLE
S3 storage should use task role credentials

### ISSUE THREAD

**Issue by helenst** [wellcometrust/platform#3486]
Currently (on local development setup) a user role is being used for authentication to upload to the S3 bucket.

In order to set up the storage provider on a deployed version, we will need to use a task role. This will need write access to the relevant S3 bucket.

**Comment by helenst** [comment]
The task role will be used by `archivematica-storage-service` and needs to be able to write to the `wellcomecollection-storage-ingests` bucket.

**Comment by helenst** [comment]
This is set up - #3491 is blocking it from being tested

**Comment by helenst** [comment]
On a rare success case of the problem in #3491 I was able to test this out and it gives `botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied`.

Running a python session on the docker container yields the same thing so this can be tested. Yet boto also insists it is using the storage service task role and things look set up correctly. May be doing the wrong thing with boto?

**Comment by alexwlchan** [comment]
gnargh

Okay, this is probably a weirdness in the way IAM permissions work (the first rule of IAM is that you'll never get it right first time). It might be worth adding a line to the IAM policy document:

```diff
data "aws_iam_policy_document" "storage_service_aws_permissions" {
   statement {
     actions = [
       "s3:PutObject",
     ]

      resources = [
       "arn:aws:s3:::wellcomecollection-storage-ingests/",
+      "arn:aws:s3:::wellcomecollection-storage-ingests/*",
     ]
   }
 }
```

which gives permission to all the objects in the bucket, not just the bucket itself.

**Comment by helenst** [comment]
I've tried this out manually but it doesn't seem to help. It sounds like it should be there anyway so I'll add it into the Terraform config. Thanks!

**Comment by alexwlchan** [comment]
@helenst What exactly are you trying to do with boto3? Do you have a snippet you're testing with?

**Comment by helenst** [comment]
@alexwlchan I'm using this:

```python
import boto3
from StringIO import StringIO

s3 = boto3.resource('s3', region_name='eu-west-1')
bucket = s3.Bucket('wellcomecollection-storage-ingests')
test_file = StringIO('test file')
bucket.upload_fileobj(test_file, '/archivematica/aips/test1')
```

(Which works locally when I have all my credentials set up)

But I get this when running within the Docker container for storage service:
> botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

If I do
```python
sts = boto3.client('sts')
sts.get_caller_identity()
```

then it shows the correct task role in the response, so it looks as if the credentials are being picked up at least.

**Comment by alexwlchan** [comment]
Hmm, that's odd.

When I've stopped mucking around in Terraform, it might be worth changing the permission to `Put*`? There are lots of possible IAM permissions for S3, and maybe we need something more than just `s3:PutObject`? https://docs.aws.amazon.com/AmazonS3/latest/dev/using-with-s3-actions.html

This issue suggests `s3:PutObjectAcl` would be fruitful: https://github.com/aws/aws-cli/issues/813

**Comment by alexwlchan** [comment]
So despite giving the task role what appear to be blanket permissions in S3, it's still failing. Curious.

**Comment by alexwlchan** [comment]
…oh. This bucket is in another account! That’s why we can’t grant permissions to it.
