### ISSUE TITLE
Fix METS.xml failure on production

### ISSUE THREAD

**Issue by helenst** [wellcometrust/platform#3491]
Currently the step "Generate METS.xml" is failing during creation of the AIP. This is a blocker to demoing Archivematica feeding AIPs into Wellcome storage service because it prevents Archivematica from getting that far.

The errors it reports are

```
No uuid for file: " %SIPDirectory%objects/metadata/transfers/PPTHW_2466-183c5ec8-8cb8-4257-bf28-393d5284c2c0/directory_tree.txt "
No uuid for file: " %SIPDirectory%objects/metadata/transfers/PPTHW_2466-183c5ec8-8cb8-4257-bf28-393d5284c2c0/manifest-md5.txt "
/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/PPTHW_2466-1dcf19a6-f91c-47ab-bd95-14b710cb40ea/metadata doesn't exist
```

It doesn't seem to happen locally.

**Comment by alexwlchan** [comment]
See https://archivematica.wellcomecollection.org/tasks/3aeadef2-f150-412c-860d-6f8d735738fb/

**Comment by alexwlchan** [comment]
@helenst I’ve discovered a line in the local `docker-compose.yml` that isn’t in our ECS task definition, for the storage-service task:

```yml
DJANGO_SETTINGS_MODULE = "storage_service.settings.local"
```

That’s the default set in the Dockerfile for the storage-service task, so I don’t think that can be the issue? I’ve checked all the other environment variables and they seem fine.

The other thing to note is that your local task is probably running an older version of the nailgun server. Can you reproduce if you use the newer server? (Image in `dockerfiles/fits_ngserver` in the am-infra repo.)

**Comment by alexwlchan** [comment]
Ooh. And our local setup will have the old version of Elasticsearch too.

**Comment by helenst** [comment]
@alexwlchan Thanks, I'll check those things. I did find that there were some migrations on production for the MCP database that hadn't been run. These were definitely contributing to some earlier substitution errors in identifying file format of metadata (which are the kind of error which allow Archivematica to continue rather than failing the ingest). I've run the migrations and restarted some services, however the earlier errors seem to be intermittent now rather than happening all the time so I'm wondering if I didn't restart everything I needed to and there's still some old code running somewhere. Whether this will affect the original problem here I'm unsure but it sounds possibly related. I'm on the move right now but I'll check a couple of things once I get home in an hour or so and have access to the deployed version. I've also added in some extra logging so will do a redeploy at some point.

**Comment by alexwlchan** [comment]
@helenst Looking at it while more awake, I want to double check the `DJANGO_SETTINGS_MODULE` variable in all our tasks.

I'm also going to add a bit of logging at startup so it's easier for us to see what version of the code we're running.

**Comment by helenst** [comment]
I think this is fixed after a redeploy (i.e. I think running the migrations did the trick). I'll keep an eye on it while testing #3487 but hopefully this can be closed.

**Comment by helenst** [comment]
There is also an intermittent failure of identifying the file format of metadata files:

https://archivematica.wellcomecollection.org/tasks/31de7c11-8a9c-499e-ad26-be5092d2f870/

```
Module identifyFileFormat_v0.0

"%IDCommand%" "/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/PPTHW_2466-1fa4a78e-b0b6-4ed2-b5bc-309ec0d22567/objects/metadata/transfers/PPTHW_2466-b31072f3-ba8e-4ca5-8256-176a6229f4ac/directory_tree.txt" "c235e765-8163-4648-a026-2872e7a3f685"

Standard streams
Standard output (stdout)

IDCommand UUID: %IDCommand%
File: (c235e765-8163-4648-a026-2872e7a3f685) /var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/PPTHW_2466-1fa4a78e-b0b6-4ed2-b5bc-309ec0d22567/objects/metadata/transfers/PPTHW_2466-b31072f3-ba8e-4ca5-8256-176a6229f4ac/directory_tree.txt

Standard error (stderr)

IDCommand with UUID %IDCommand% does not exist.
```

**Comment by helenst** [comment]
It looks as if the substitution of the `%IDCommand%` variable is failing. The value corresponds to the selected file identification command, and MCPServer gets this from a `UnitVariable` object. This is written to the database by the MCPClient script identify_file_format.py. I am suspecting some kind of race condition but have added some logging to try and clarify what's going on. These are the same files that are causing problems later on in the METS.xml so it may well be related.

**Comment by helenst** [comment]
Might be more intermittent than originally thought - I've seen it succeed a couple of times. But still fails most of the time.

**Comment by helenst** [comment]
This is very likely to have the same cause as #3510 and #3511 since it is caused by files not being assigned UUIDs earlier on in the process.
