### ISSUE TITLE
Directory creation error during "Move submission documentation into objects directory"

### ISSUE THREAD

**Issue by helenst** [wellcometrust/platform#3509]
I'm not sure whether this is an intermittent failure because it's not always being run (possibly dependent on whether other failures happen?)

Example:

https://archivematica.wellcomecollection.org/tasks/65490159-268a-477d-9e69-64685b7e8806/

>Error("Destination path '/var/archivematica/sharedDirectory/watchedDirectories/workFlowDecisions/metadataReminder/PPTHW_2466-1fa4a78e-b0b6-4ed2-b5bc-309ec0d22567/objects/submissionDocumentation/transfer-PPTHW_2466-b31072f3-ba8e-4ca5-8256-176a6229f4ac' already exists",)

**Comment by alexwlchan** [comment]
Looking at this particular error, I'm pretty sure it's not actually an error we care about, but a spurious result. Specifically, we have something like this:

```
src
├── foo.txt
└── directory
    └── file.txt

dst
└── directory
    └── file.txt
```

The current `move_or_merge` script tries to copy `src` into `dst`, but gets upset when it finds the already-extant directory. I'm going to edit the script to be more robust, and a bit more strict.

**Comment by helenst** [comment]
Just noticed that the "Process submission documentation" steps seem to repeat themselves sometimes (i.e. after Remove files without linking information, it goes back to Copy Transfer submission documentation). (and that's when this fails, as it tries to create the directory that already exists). I wonder why that happens.

**Comment by helenst** [comment]
Continuing my line of thought of "why is it running this step for a second time" - looking through workflow.json it doesn't seem like a valid workflow path. "Remove files without linking information" upon success should only invoke "Copy transfers metadata and logs" - there's nothing telling it to cycle back to "Copy transfer submission documentation".

**Comment by helenst** [comment]
Having combed through the MCP server logs, I think I know why, sort of. Archivematica actually succeeds that section of the workflow and continues further, all the way to the "Generate AIP METS?" section where it presents the user with a choice of whether to document empty directories. (I had it set to pause at that point so I could examine some other stuff mid workflow before it gets to #3491) 

While waiting for the user input, Archivematica gets redeployed / things get restarted so the ingest doesn't complete. However, the task gets picked back up after the new deploy. I don't know why it does this, or why it chooses to do so at that point (possibly something in a watched directory), but it jumps back into the "process transfer submission documentation step again", hence trying to recreate that directory and failing. And the history of that task is rewritten to look as if it failed at that point.

It seems to me this is a case of (for now at least) accepting that weird stuff will happen if AM is redeployed while ingests are in progress, and possibly investigating further when there is more time? Improving move_or_merge might still be worthwhile - I don't know if there are other places that use it too?

**Comment by jtweed** [comment]
Closing to tidy up the backlog. Will reopen as a new issue if we see it again with our actual workflow.
