### ISSUE TITLE
Intermittent failure of Identify file format during Process submission documentation

### ISSUE THREAD

**Issue by helenst** [wellcometrust/platform#3510]
Example of failure:

https://archivematica.wellcomecollection.org/tasks/57541765-bc89-42e7-aed3-0de5f7f356fd/

```
File matching query does not exist.Traceback (most recent call last):
  File "/src/MCPClient/lib/job.py", line 102, in JobContext
    yield
  File "/src/MCPClient/lib/clientScripts/identify_file_format.py", line 174, in call
    job.set_status(main(job, args.idcommand, args.file_path, args.file_uuid, args.disable_reidentify))
  File "/src/MCPClient/lib/clientScripts/identify_file_format.py", line 109, in main
    file_ = File.objects.get(uuid=file_uuid)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: File matching query does not exist.
```

Example of success:
https://archivematica.wellcomecollection.org/tasks/9c53b9e8-28f4-4ab8-bd0d-4ccea53f6409/
(Blank output, I don't know if this is OK ?)

**Comment by helenst** [comment]
This is also a failure to insert a UUID into the identify command, as with #3508 (although a different parameter) so perhaps related after all?

**Comment by helenst** [comment]
So far I've tracked this back to the "Assign file UUIDs to submission documentation" step and the `linkTaskManagerFiles` module in MCPServer that runs this on each file that's relevant (which here should only be the METS.xml). It's not picking up on the METS.xml file most of the time - when it checks the filesystem (`unit.reloadFileList()`) sometimes it's there and sometimes it's not.

Given that it is expected to be in the `objects` directory, and the previous step is "Move submission documentation into objects directory", I'm wondering if there are filesystem sync issues here. MCPClient performs the move step, and it's MCP Server which has to pick up on the change that was made.

If the shared filesystem is causing issues here, it may well be doing so elsewhere. (And based on investigations here I am pretty sure #3511 has the same cause)

**Comment by alexwlchan** [comment]
Ugh. A shared filesystem sync issue seems totally plausible.

If we clustered the MCP client and MCP server tasks so they always ran on the same instance, do you think that would resolve the issue?

**Comment by helenst** [comment]
I introduced a 5 second delay before `linkTaskManagerFiles.reloadFileList` - this stopped the issue from happening. I also didn't observe #3508 or #3511. @alexwlchan is trying out putting everything into one big instance to see if this is an alternative.

**Comment by helenst** [comment]
Running everything on one instance also appears to fix this. I'm going to close this and open an Archivematica issue.
