### ISSUE TITLE
Archivematica needs to send tar.gz, not .zip

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#3526]
Archivematica can create an AIP and upload it to an ingests bucket for the storage service, but when the storage service tries to unpack it, it finds a ZIP, which it doesn't know how to open.

Archivematica should be able to send tar.gz files instead.

(Or if it can already do so, Helen should show me how!)

**Comment by helenst** [comment]
This has been done in https://github.com/wellcometrust/archivematica/pull/6 (it can be selected as an option in the compression method step)
