### ISSUE TITLE
Submit pull requests to core Archivematica

### ISSUE THREAD

**Issue by helenst** [wellcometrust/platform#3535]
There are various modifications in the wellcome-storage-service branches which are not yet integrated into Archivematica. We need to be contributing these back to prevent divergence from the core code. This ticket is intended to keep track of those changes as they go in.

- [x] [Use pip-tools to manage requirements](https://github.com/archivematica/Issues/issues/634) (this is quite high priority since it creates a lot of conflicts when rebasing!) | [PR for Archivematica](https://github.com/artefactual/archivematica/pull/1418) | [PR for Storage Service](https://github.com/artefactual/archivematica-storage-service/pull/455)
- [x] Improvements to file sanitization - picked up by Artefactual and included in PR https://github.com/artefactual/archivematica/pull/1401/files
- [x] [Record stderr from file identification command](PR: https://github.com/artefactual/archivematica/pull/1419)
- [x] [Make move_or_merge more robust](PR: https://github.com/artefactual/archivematica/pull/1420)
- [x] [Improvements to s3 plugin](PR: https://github.com/artefactual/archivematica-storage-service/pull/459)
- [x] [zip/deflate compression of AIP](PR: https://github.com/artefactual/archivematica/pull/1346) (note that we don't actually need this any more ourselves but it's still potentially useful as an Archivematica feature!)
- [x] [gzip compression of AIP](PR: https://github.com/artefactual/archivematica/pull/1412)
- [x] [Create METS continue on error](PR: https://github.com/artefactual/archivematica/pull/1396)
- [x] [Support zipfile transfers](PR: https://github.com/artefactual/archivematica/pull/1413)
- [x] **Merged**: ~~[Write external identifier to bag-info.txt](https://github.com/artefactual/archivematica/pull/1347)~~

**Comment by alexwlchan** [comment]
The improvements to file sanitisation have been picked up by Artefactual: https://github.com/artefactual/archivematica/pull/1401

**Comment by kenoir** [comment]
@helenst this is fantastic 👏

**Comment by helenst** [comment]
Removed [Improvements to travis build](https://github.com/wellcometrust/archivematica/pull/1) from this list because it is specific to the way Wellcome builds and publishes its own Archivematica images - it shouldn't be necessary once all changes are merged and we can use core Archivematica images again.

**Comment by helenst** [comment]
Removed [zip/deflate compression of AIP](https://github.com/artefactual/archivematica/pull/1346) from the list since we no longer need this ourselves, and it's not necessarily useful to have in Archivematica right now.
