### ISSUE TITLE
Use 089 in addition to 962 for Miro/Sierra merging

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3545]
Currently we take Miro IDs from MARC 962 in the Sierra data, then use this as the basis for merging Miro and Sierra works. We can increase the number of merged works by about 20% by also looking in 089 for merge candidates.

- We should only take Miro IDs from 089 when there is a single value in 089
- We need to check the value in 089 is a Miro ID and not a text description
- We need to remove the space from the Miro ID in 089 and zero pad the number to the same length as other Miro IDs
- This means we should now merge if there is a single ID in 089 or 962
- All existing merging rules should still apply

**Comment by alexwlchan** [comment]
What if there’s a Miro ID in both 089 and in 962, and they differ? Does this ever happen? If so, which wins?

**Comment by jtweed** [comment]
Shouldn't do, but I think CI want to standardise on 089. @amme2?

**Comment by amme2** [comment]
Can you easily check to see how often this occurs and send me some examples? I anticipate 089 will be easier for longer-term use as all it requires is a MIRO identifier, not a full URL (which you then have to parse to extract the number that we started with in the first place).

**Comment by alexwlchan** [comment]
The right answer for now might just be “it shouldn’t happen, bubble it up as an error if it does, deal with it if/when it occurs”.

The comparable scenario is the use of 260/264 for production fields. CI are standardising on 264, but there are some records with a 260, and sometimes we get records with both. If we get them both, we try to detect and handle “obvious” cases, but eventually we bubble it up as an error.

See: https://github.com/wellcometrust/catalogue/blob/master/pipeline/transformer/transformer_sierra/src/main/scala/uk/ac/wellcome/platform/transformer/sierra/transformers/SierraProduction.scala

**Comment by amme2** [comment]
On a related note, if we are using 089 to make retrospective merges, do you want the input format to be e.g. V 34567 with a space and no leading zeros, or could you test for this separately so that we can also input full 8-character references e.g. V00034567 (which might be easier to explain to the CI team)?

**Comment by amme2** [comment]
@alexwlchan T

> The right answer for now might just be “it shouldn’t happen, bubble it up as an error if it does, deal with it if/when it occurs”.
> 
> The comparable scenario is the use of 260/264 for production fields. CI are standardising on 264, but there are some records with a 260, and sometimes we get records with both. If we get them both, we try to detect and handle “obvious” cases, but eventually we bubble it up as an error.
> 
> See: https://github.com/wellcometrust/catalogue/blob/master/pipeline/transformer/transformer_sierra/src/main/scala/uk/ac/wellcome/platform/transformer/sierra/transformers/SierraProduction.scala

That sounds fine. Thank you.

**Comment by alexwlchan** [comment]
@amme2

> do you want the input format to be e.g. V 34567 with a space and no leading zeros, or could you test for this separately so that we can also input full 8-character references e.g. V00034567

We can handle full 8-character references (that’s what we look for in the Wellcome Images URLs).

Personally that’s what I prefer; it keeps the code a little simpler if we don’t have to unpack the ID and zero pad it.

**Comment by amme2** [comment]
@alexwlchan unfortunately you're going to have to unpack the ID and add zeros anyway, as all the records where 089 is currently populated use the version without leading zeros. But I'm thinking when we edit Sierra records from this point forwards, we might prefer to use the 8-character version. (although I am now feeling guilty for distracting you from the main point here!)

**Comment by jamesgorrie** [comment]
Comment from @amme2 on Slack, keeping it here to stop it getting lost in the firehose:

> R and L here simply stand for 'right' and 'left'. See the examples on wiki commons above - V0011253ER is simply the right hand image of the (terrible quality!) V0011253. They should appear in pairs in 962 and 089 (not 082, incidentally), with usually, as Jonathan says, the more specific id appearing in 962. The Sierra record for the wiki examples is b11602892. If there's really a record with a completely different number in 962 and 089, that's odd - if you can give me an actual example, I'll investigate.

> E is just an introductory sort of character to the trailing one which identifies which work is which when they were photographed on the same piece of film.
L = left, R = right, T = top, B = bottom, TR = top right etc.
You'll occasionally come across F as well, used when 2 works were photographed separately (e.g. because they were on the recto and verso of the same sheet) but were to be displayed as one. F is usually followed by A or B e.g V0031759FA and V0031759FB.

**Comment by mklander** [comment]
In terms of merging, if marc 962 has a single item we merge that, if 962 is empty look in marc 089 and if there is a single item in 089 merge that.  That should be about 14 thousands records.  Items with more than one item in 962 are not merged and we don't consider 089.
