### ISSUE TITLE
Ongoing collection of quantitative data on search sessions

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3569]
- [x] Setup a structure for the mappings in the reporting API for search events
- [x] Setup naming conventions for events sent through
- [x] Use λ to process / cleanse segment data
- [x] Start collecting the position 
- ~Get catalogue λs into a universal type state~ This works for now, I wonder if it might be pulled out of reporting, and put somewhere else. It might be best to wait for another implementation before abstracting it out.

**Comment by jamesgorrie** [comment]
I could open another issue, or start the conversation here, but here's what I was thinking re: structure of tracking logs:

The shape of the client event is:
```
{
  service: string,
  name: string,
  data: Object
}
```

Currently we have two services with the following events:
* `search`
  * `Search` : someone made a search. Has properties:  `query`, `page`, `workType`, `_queryType`
  * `Select Result` : someone chose a result. Has properties: `query`, `page`, `workType`, `_queryType`, `position`
* `relevance_rating`
  * `Rate Result Relevance` : someone gave us a rating on relevance. Has Properties: `query`, `page`, `workType`, `_queryType`, `position`, `id`, `rating`

In elastic search it will create a document with these fields with `anonymousId`, `toggles`, `event`, `network`, and `data` as the above fields.

__TODO__
* Example

**Comment by jtweed** [comment]
Looks mostly good to me. Two things that I want to check:

* Is the `network` there to allow us to distinguish internal requests? What are the possible values? Ie, I'm assuming we're not recording user's WiFi network names?
* Should the search result selected doc have the position of the result in the result list?

**Comment by jamesgorrie** [comment]
At the moment the only two we specify are `StaffCorporateDevices` and `Wellcome-WiFi`.

We could just say something like `internal` but the separation seems useful. We could also rename them to things like `WellcomeInternal` and `WellcomeWifi`, but also feels like an unnecessary step away from what we are actually measuring.

**Comment by jamesgorrie** [comment]
> Should the search result selected doc have the position of the result in the result list?

Yip, sorry, just omitted it.

**Comment by jtweed** [comment]
Thanks - makes sense to keep the networks split. Wellcome-Wifi is used for both staff personal and public devices. So I can see us wanting to look at that separately.
