### ISSUE TITLE
Set up routing connections to Sierra using the transit VPC

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/platform#3570]
D&T will restrict access to the Sierra API endpoint. In advance of that we need to set up using the transit VPC

TODO:
- [x] Add Endpoint Service in experience account.

**Comment by kenoir** [comment]
This should now be done:

The libsys endpoint should be reachable at `libsys.experience.internal` from private subnets a & b in the experience team VPC. 

In order to talk with it, your services will need to include the `interservice` security group `libsys_interservice`.

**Comment by kenoir** [comment]
Will wait until tested by @gestchild & @davidpmccormick to close this ticket.
