### ISSUE TITLE
Add years to production dates for all 260 and 264

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3577]
This is for subfield `$c`: Date of publication, distribution, etc for both MARC fields.

https://www.loc.gov/marc/bibliographic/bd260.html
https://www.loc.gov/marc/bibliographic/bd264.html

**Comment by jamesgorrie** [comment]
Interestingly when I search the `production.dates.label` for `[0-9]{4}` I get `1039991` of `1262588`(82%).
