### ISSUE TITLE
Add contents (505) for audiovisual works

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3582]

**Comment by jamesgorrie** [comment]
@jtweed just wondering - are we only doing this for audio visual?

If so, are we happy to be using the root field of `contents`, which will inevitably be used for other things as it's a pretty broad term.

And if it is - what other info are we going to put in there?

[The PR for this](https://github.com/wellcometrust/catalogue/pull/186/files) is extracting it for all works, so just trying to ensure we capture as much semantics as we can, if ew can.

**Comment by jtweed** [comment]
I believe it's only used for audiovisual works. So in practice, the distinction doesn't matter.

**Comment by jtweed** [comment]
Actually I think it's mostly used on AV, but can exist on others, so that it is correct:

http://scope.whatsinthelibrary.com/fields/505

It's this:

https://www.loc.gov/marc/bibliographic/bd505.html

**Comment by jamesgorrie** [comment]
For works generally, `credits` and `durations` seem like universal concepts that you can apply to anything, and we could probably pull other metadata into these for different works.

`contents` however feels less so, if I saw contents, I might expect it to be the contents of a book, a box, or anything really - is it worth looking at other marc fields we might think fir the `contents` description, or be more specific with this one in the case of audio?

Ping @warrd
