### ISSUE TITLE
Merge dimensions (300 c) and extent (300 a) into physicalDescription (300)

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3585]
We're currently splitting MARC 300 Physical Description into three properties:

* 300a: `extent`
* 300b: `physicalDescription`
* 300c: `dimensions`

However in the spirit of getting the data out accurately, then adding structure later where we can, let's acknowledge that the catalogue intends these three to be combined into a single human-readable string and concatenate subfields `a`, `b` and `c` into `physicalDescription`.

We should also remove extent and dimensions as separate properties for now. We will revisit this later when we're able to put the time into properly trying to extract these, including understanding embedded measurement units.

**Comment by jamesgorrie** [comment]
As a point, removing these properties would technically be a breaking change... what are we thinking URL versions wise?

We could stick to `v2` but we'd have to coordinate between us and @wellcometrust/experience-devs

**Comment by alexwlchan** [comment]
They are optional fields on any given work, so clients should be able to cope with their absence already.

**Comment by jamesgorrie** [comment]
> should be able to cope with their absence already.

But it will break rendering if this is what they rely on to render, which we do.
