### ISSUE TITLE
Add associated dates (subfield $d) to contributors

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3592]
Rather than add the associated dates (subfield `d`) to contributor labels, we should add them as a separate `date` property, that is a `Period` object.

To start, this should just have a `label` with the contents of subfield `d`.

This should be added for all contributors (100, 110, 700 and 710) where available.

**Comment by warrd** [comment]
Here is some sample dates from these fields:

https://gist.github.com/warrd/903e57d5d166ae1ff336a086409491d0
