### ISSUE TITLE
Parse varfields in sierra reporting lambda

### ISSUE THREAD

**Issue by harrisonpim** [wellcometrust/platform#3608]
to start seeing dates in the reporting cluster's sierra index, we need to add the sierra varfields - currently we're only looking at fixed fields

**Comment by jamesgorrie** [comment]
I am currently storing the results in the `reporting_sierra_varfields` index in the following format:

```JSON
{
	"id": "129038",
	"varfields": {
		"260": {
			"label": "London : Faber and Faber limited, [1938]",
			"a": "London : ",
			"b": "Faber and Faber limited,",
			"c": "[1938]"
		},
		"245": {
			"label": "Poems on various subjects, Divine, Moral and Entertaining: the posthumous works of Mr. Jacob Axford, of the city of Bath, late surgeon of his Majesty's ship, Scipio; written for his own amusement.",
			"a": "Poems on various subjects,",
			"b": "Divine, Moral and Entertaining: the posthumous works of Mr. Jacob Axford, of the city of Bath, late surgeon of his Majesty's ship, Scipio; written for his own amusement."
		}
	}
}
```

All fields are stored as `text` and `keyword` (under a `.raw` field e.g. `varfields.245.a.raw`) types to allow exact and partial matching.

[You can see the mapping here](https://github.com/wellcometrust/reporting/blob/master/lambdas/sierra_varFields/elastic_mapping.json).
