### ISSUE TITLE
Move to federated User Roles (remove IAM Users)

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/platform#3612]
This is follow up from the March 2019 security incident.

- [x] Provide terraform modules for federated login
- [x] Enable use of federated login for users
- [x] Provide for cross account assume role for all accounts
- [x] Remove existing IAM Users

**Comment by kenoir** [comment]
This is now substantially done. Removal of old accounts will take place when I return from annual leave giving developers a chance to try out the new login method.
