### ISSUE TITLE
Work linking through to wrong library record

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/platform#3626]
Works page: https://wellcomecollection.org/works/mnygpdkg
which links to non-digitised Sierra record: http://search.wellcomelibrary.org/iii/encore/record/C__Rb1658983?lang=eng

The digitised record for the same is at http://search.wellcomelibrary.org/iii/encore/record/C__Rb3047923?lang=eng

**Comment by jamesgorrie** [comment]
@pollecuttn While working on this, it seems like we have done this on purpose.

I am starting to remember a discussion around why we do this.

As far as @gestchild and I can remember, it was to do with the fact that we only surface results that we can show the digitised version of.

To this end, we should be rendering it, and don't want to send people off to another digital version, but the physical version might be useful.

Granted, this logic is hidden in or heads and not made clear on the interface, but I imagine we'll be approaching this more thoroughly when looking at access information.

**Comment by jamesgorrie** [comment]
Ping @jennpb to make sure I'm not completely making this up.

**Comment by jennpb** [comment]
Ah yes, now I remember. Thank you for clarifying!

I must've been thrown off the scent by e-books where we don't have a physical copy. Those do link to a record with the digitised item. As you say, we should pick this up again in the access information.
