### ISSUE TITLE
Add notes (many MARC fields)

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3631]
Combine the following MARC fields into a single notes property:

* 500, 501, 504, 518, 536, 545, 547, 562

**Comment by jamesgorrie** [comment]
FYI for what the data looks like:
https://reporting.wellcomecollection.org/app/kibana#/discover?_g=()&_a=(columns:!(varfields.500.a,varfields.500.label,varfields.504.a,varfields.504.label,varfields.545.a,varfields.545.label),index:'3eea68f0-af8d-11e9-8c11-11fbc4852f39',interval:auto,query:(language:kuery,query:''),sort:!(_score,desc))
