### ISSUE TITLE
Add 111 and 711 to contributors as Meeting

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3632]

**Comment by jamesgorrie** [comment]
@jtweed judging from what I can see in the data, the meeting is where a work was produced.

If that's the case does it sit closer to `production`?

**Comment by jtweed** [comment]
I think it’s more correct to say the meeting participants created the work, by having the meeting.

**Comment by jtweed** [comment]
It kind of feels more like the work is an output of the meeting, rather than produced by it. But certainly in MARC it’s a contributor relationship, not a production/publication/imprint one. I was following that.

**Comment by jamesgorrie** [comment]
Ah, sorry, I didn't see that info in the spec - where do you see that?

**Comment by jtweed** [comment]
"Fields 100, 110, 111 and 130 contain a name or a uniform title heading used as main entry."

https://www.loc.gov/marc/bibliographic/bd1xx.html
https://www.loc.gov/marc/bibliographic/bd111.html

Which maps to creator in RDA, but in MARC literally means which of these names would you put on the main index card for the work.
