### ISSUE TITLE
Explore and find date patterns in 260/264 to cover more of the collection.

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/platform#3664]
So far we have covered:

* `yyyy`
* `[yyyy]`

Let's find some more to get more coverage 

Current coverage is `_____`% 

Awaiting the reindex to fill :point_up: in.

**Comment by warrd** [comment]
I have analysed the current dates in python using some regex: https://gist.github.com/warrd/40da143a3e3476733e755a165aa69096

If we updated the parser to handle the formats outlined we would have coverage of 70%.

**Comment by warrd** [comment]
https://github.com/wellcometrust/catalogue/pull/70

**Comment by warrd** [comment]
Leaving this open as still much more patterns in the gist to implement
