### ISSUE TITLE
Upgrade catalogue elasticsearch to v7

### ISSUE THREAD

**Issue by harrisonpim** [wellcometrust/platform#3692]
To regain the query string logic for our new candidate query types (#3684), we need to switch them from MultiMatchQueries to SimpleStringQueries. SimpleStringQueries still support boosting and minimumshouldmatch, so we shouldn't lose anything by doing this. 

However, [Elastic4s v6's SimpleStringQuery](https://github.com/sksamuel/elastic4s/blob/v6.5.1/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/searches/queries/SimpleStringQuery.scala) only accepts an int as input to the minimumshouldmatch option, while [v7](https://github.com/sksamuel/elastic4s/blob/master/elastic4s-core/src/main/scala/com/sksamuel/elastic4s/requests/searches/queries/SimpleStringQuery.scala) accepts a string. Inputting a string allows us to play with the [full complexity of minimumshouldmatch](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-minimum-should-match.html), like requiring that a percentage of query tokens be present in a result, rather than a fixed number. 

To get this functionality in our queries, we need to bump the prod version of elasticsearch

**Comment by jamesgorrie** [comment]
Plan:

- [x] Create new elastic index with v7
- [ ] Upgrade app to use elastic4s 7 https://github.com/wellcometrust/catalogue/pull/69
- [ ] Point non-prod (romulus) to new parameter with `catalogue_v7` hostname
- [ ] Test!

**Comment by jamesgorrie** [comment]
Plan:

- [x] Create new elastic index with v7
- [ ] Upgrade app to use elastic4s 7 https://github.com/wellcometrust/catalogue/pull/69
- [ ] Point non-prod (romulus) to new parameter with `catalogue_v7` hostname
- [ ] Test!
