### ISSUE TITLE
Build selective sync mechanism

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/platform#3710]

**Comment by tomcrane** [comment]
@alexwlchan maybe this could use the migration status DynamoDB table, which records the status of all-the-things (bagged, ingested, registered with DLCS, text working). Could be extended with additional facts.

**Comment by alexwlchan** [comment]
For working out what METS has changed:

- [ ] Can we get exports from Goobi?
- [ ] Set up an S3 trigger for new uploads

**Comment by tomcrane** [comment]
Goobi already tells the DDS about b number changes so maybe this could be hooked into?
http://wt-havana:85/Dash/Recent

This is for the old workflow though.

**Comment by alexwlchan** [comment]
The second half of this work is a script that takes the list of unbagged b-numbers and runs them through the bagger again.
