### ISSUE TITLE
 Bag contents in wrong path

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/platform#3743]
Bag contents are getting put under . when unpacked, but get replicated correctly, this is ok but might make debugging failed bags harder

**Comment by alexwlchan** [comment]
Adding some tracing to the unpacker, and this is what I see:

```
11:53:58.808 [ScalaTest-run-running-S3UnpackerTest] DEBUG u.a.w.p.a.b.services.s3.S3Unpacker - Processing archive entry b21000633/._fetch.txt
11:53:58.808 [ScalaTest-run-running-S3UnpackerTest] DEBUG u.a.w.p.a.b.services.s3.S3Unpacker - Uploading archive entry b21000633/._fetch.txt to wellcomecollection-storage-staging-ingests/alex-unpacker-testing/b21000633/._fetch.txt
11:53:58.942 [ScalaTest-run-running-S3UnpackerTest] DEBUG u.a.w.p.a.b.services.s3.S3Unpacker - Processing archive entry b21000633/fetch.txt
11:53:58.943 [ScalaTest-run-running-S3UnpackerTest] DEBUG u.a.w.p.a.b.services.s3.S3Unpacker - Uploading archive entry b21000633/fetch.txt to wellcomecollection-storage-staging-ingests/alex-unpacker-testing/b21000633/fetch.txt
```

Ah, but this doesn't happen with the Intranda bags!

I think this might be something that the macOS tar command is doing.

**Comment by alexwlchan** [comment]
Ah, I think this is it: https://stackoverflow.com/a/8766757/1558022

**Comment by alexwlchan** [comment]
This is an S3 console bug caused by the macOS `tar` command being annoying. I’m inclined to ignore, as uploading bags from macOS isn’t a common use case.
