### ISSUE TITLE
Validation of fetch files broken

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/platform#3744]
There is definitely something up with validation of bags with fetch.txt - see f625d5b7-2ba5-45d3-acd9-c85a373e4011 and c271e0b6-89be-4da8-baf7-068246fd2d20

**Comment by alexwlchan** [comment]
Note to self: the bag in question is `s3:///wellcomecollection-storage-staging-bagger-drop/b21000633-mets.tar.gz`

**Comment by alexwlchan** [comment]
Per Robert, the other bag is `b2227683x`

**Comment by alexwlchan** [comment]
`b21000633` is complaining about a missing Payload-Oxum.

`b2227683x` is complaining about a bad checksum on the `fetch.txt`:

```
https://wellcomecollection-storage-staging-ingests.s3.eu-west-1.amazonaws.com/unpacked/alex-testing/04438ce4-21ec-4000-ab2e-1b655e088eac/b2227683x/fetch.txt: Checksum values do not match! Expected: sha256:ada213f9ed885fafdd2c1faf48c8b3182fafb59e6dae84eeffc045aca90d1435, saw: sha256:aae34cb7e92493c6f71da185132d54905a49dbce8cf349b72c4cb67dc6777ca9
```

**Comment by alexwlchan** [comment]
b21000633 is ingesting correctly!

See https://api-stage.wellcomecollection.org/storage/v1/ingests/0ef48d22-655f-481c-bf10-40c00a942f25

**Comment by alexwlchan** [comment]
As is b2227683x!

https://api-stage.wellcomecollection.org/storage/v1/ingests/f074492d-40c3-4b30-8f4b-89f4de5b64c3
