### ISSUE TITLE
Strategise about how we're indexing data

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/platform#3754]
As we're stratified to want to create more complex queries i.e. Using boosting, msm etc, it's proving to be a litlle fiddly.

I'd like to explore how we structure data with a starting point of
* we have display data
* we have queriable free text e.g. Description, genres, subjects, title
* we have exact text matching e.g.title, genres, ids
* we have structured data e.g. Instant ranges

It would be good to get the index more typey with less types.

**Comment by jtweed** [comment]
This is interesting. We started with serving as close to the API as possible from ES, but now is a good time to revisit that.
