### ISSUE TITLE
Use specific users to logging ES deployment

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/platform#3804]
We currently use `elastic` which is going to cause problems.

**Comment by alexwlchan** [comment]
Active Directory? https://www.elastic.co/blog/saml-based-single-sign-on-with-elasticsearch-and-azure-active-directory

**Comment by jamesgorrie** [comment]
@alexwlchan for services? e.g. lambdas, apps etc?

This is specifically the logstash-transit services that will need to write to this.

**Comment by jamesgorrie** [comment]
But that would be nice for things like dashboards.

**Comment by alexwlchan** [comment]
Ah sorry, I thought you mean for people to *read* the logs.
