### ISSUE TITLE
Don't hang on to storage service oauth sessions for too long

### ISSUE THREAD

**Issue by helenst** [wellcometrust/platform#3809]
`TokenExpiredError` will be raised if Archivematica is polling storage service for more than an hour. This shouldn't normally happen (?) but should still be more cleanly handled, i.e. don't keep reusing the same oauth session :)

**Comment by alexwlchan** [comment]
> This shouldn't normally happen 

Depends – the length of time an ingest takes is proportional to the number of files in the bag. The more files in the bag, the longer it takes to replicate and verify! Also, when we’re running it for real, the services will scale down when they're not in use – so a large ingest sent while the pipeline is cold could hit the one hour mark.

This is a bug in the Python client for the storage service, I think?

**Comment by helenst** [comment]
Good point, I think it's probably best handled in the storage client, I'll raise an issue there.
