### ISSUE TITLE
Investigate why recorder and ingestor get reapplied every time you run terraform apply

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/platform#3811]
Seems like something to do with:
`module.catalogue_pipeline_20190723.module.recorder.module.service.module.task.module.task_definition.aws_ecs_task_definition.task`

`module.catalogue_pipeline_20190723.module.recorder.module.service.module.service.module.service.aws_ecs_service.service`

and 

`id:                                  "catalogue-20190723_recorder" => <computed> (forces new resource)`

**Comment by alexwlchan** [comment]
Pretty sure this was fixed in #104.
