### ISSUE TITLE
Move Goobi/Archivematica/External upload buckets to digitisation account

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/platform#3813]
Names to be confirmed:

* [ ] wellcomecollection-external-transfer
* [ ] wellcomecollection-goobi-upload
* [x] wellcomecollection-archivematica-upload

And allow service/user access as applicable

**Comment by alexwlchan** [comment]
Do these buckets exist already? I can't find them if they do; do they have different names?

**Comment by alexwlchan** [comment]
Create new buckets in the Digitisation account, and set up triggers for Goobi and Archivematica.

**Comment by alexwlchan** [comment]
The existing buckets are in the Workflow account.

**Comment by alexwlchan** [comment]
The Archivematica buckets have been moved; I'm still not clear which other buckets need moving or where they're defined.
