### ISSUE TITLE
Finalise date range filtering in the API

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3846]
We need to finalise the interface for date filtering in the API, then remove the temporary query params once the site has been moved over.

Suggestion is something like:

```
?production.dates.from
?production.dates.to
```

With an open question:

- Do we want to add the range start and end to the response? What about other similar structured additions to `Period`?

**Comment by warrd** [comment]
https://github.com/wellcometrust/catalogue/pull/170
