### ISSUE TITLE
Refine deployment for catalogue API

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/platform#3859]
Bring it in line with the release tool, and probably parameterise the `production_api`.

**Comment by warrd** [comment]
Currently terraform apply creates new task definitions (and thus causes a service to restart) even if the  hash pointed to has not changed, would be great if we could rectify this as part of the updates!

**Comment by alexwlchan** [comment]
> Currently terraform apply creates new task definitions (and thus causes a service to restart) even if the hash pointed to has not changed, would be great if we could rectify this as part of the updates!

This is a bug and I know what's causing it; fix landing imminently.
