### ISSUE TITLE
Modify NERD tokenisation for prodigy

### ISSUE THREAD

**Issue by harrisonpim** [wellcometrust/platform#3861]
[Prodigy](https://prodi.gy/) is a data annotation tool which we'll use to validate the performance of the **N**amed **E**ntity **R**ecognition and **D**isambiguation model. It has accepts data in a particular format, which we can't currently provide without some tweaks to core parts of the model.

Currently, the NERD model uses an arbitrarily chosen tokenisation scheme, and doesn't store input data in a consistent, useful format. It's a bit of a mess, but it's worked well enough so far to prove that the model is capable of producing meaningful outputs. 

Updating the way that the model tokenises text will allow us to match the formats of input and output, get intermediate states more reliably, and, most importantly in the short term, push outputs seamlessly to prodigy.

**Comment by kenoir** [comment]
@harrisonpim Can you break down the acronyms here? Some links to what NERD is and "prodigy" would be really helpful.
