### ISSUE TITLE
Updates to workType labels

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3863]
Whilst we wait for the @wellcometrust/weco-experience team to finalise the research and requirements around work types, we want to make a smaller change to try to improve the existing labels.

- v: E-books -> Books
- j: E-journals -> Journals
- g: Videorecordings -> Videos
- f: E-videos -> Videos
- s: E-sound -> Audio
- n: Cinefilm -> Film

We should keep the existing set of work types, with the current ids based on Sierra material types, just update the labels.

**Comment by jamesgorrie** [comment]
As a point and after a discussion with @jennpb - we will need to fully merge these `workType`s, ID and all.

e.g.
```
{
  "workType": {
    "id": "v",
    "label": "E-books"
  }
}
```

should be:
```
{
  "workType": {
    "id": "a",
    "label": "Books"
  }
}
```

We can then use the information later to add more structured to the Work.
