### ISSUE TITLE
Add workType aggregation

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3864]
This should return all work types with results in doc count descending order.

Request:

```
?aggregations=workType
```

Response:

```
{
  "results": [...],
  "aggregations": {
    "type": "AggregationSet",
    "workType": {
      "type": "Aggregation",
      "buckets": [
        {
          "type": "AggregationBucket",
          "workType": {
            "type": "WorkType",
            "id": "a",
            "label": "Books"
          },
          "count": 100
        },
        ...
      ]
    } 
  }
}
```

## Acceptance criteria
- [x] Response is finalised
- [x] URL 
- [ ] ☝️ is documented along with any other API docs

**Comment by jamesgorrie** [comment]
I'd suggest using a key to specify the aggregation, making it way easier for clients. It's small but generally annoying.

It's not really a list of aggregations, it's a set of known aggregations that we will offer.

example client code:
```JS
const workTypeAggregation = `aggregations.find(agg => agg.id === 'workType')`
// vs
const workTypeAggregation = `aggregations.workTypes`
```


```JSON
{
  "results": [...],
  "aggregations": {
    "workTypes": {
      "type": "Aggregation",
      "id": "workType",
      "buckets": [
        {
          "type": "AggregationBucket",
          "key": {
            "type": "WorkType",
            "id": "a",
            "label": "Books"
          },
          "count": 100
        },
        ...
      ]
    }   
  }
}
```

**Comment by jamesgorrie** [comment]
Question - do we want to say `aggregations=workType` or `aggregations=workTypes`?

**Comment by jtweed** [comment]
> I'd suggest using a key to specify the aggregation, making it way easier for clients. It's small but generally annoying.

Agreed - will update the description to reflect.

**Comment by jtweed** [comment]
> Question - do we want to say `aggregations=workType` or `aggregations=workTypes`?

I think `aggregations` is plural and the aggregate "type" is singular. So the first one.

**Comment by jamesgorrie** [comment]
@jtweed existential question, but why do we put type on everything?

**Comment by jtweed** [comment]
> @jtweed existential question, but why do we put type on everything?

To make it JSON-LD. Whether or not it should be JSON-LD, well, that's a valid question.

**Comment by jamesgorrie** [comment]
@jtweed what do we think about when there is no request for aggregations? Do we return `{}`, or nothing?

**Comment by jamesgorrie** [comment]
@jtweed 

To generify the bucket type, should we be abstract the property name containing the data?
```JS
{
  "type": "AggregationBucket",
  "data": {
    "type": "WorkType",
     "id": "a",
     "label": "Books"
    },
    "count": 100
}
```

**Comment by jamesgorrie** [comment]
I also wonder if we could potentially start to capture the query structure of how to get to the results that an aggregate is talking about.

e.g.
```JS
{
  "aggregations": {
    "workType": {
      "label": "Books",
      "count": 100,
      "query": "?query=things&workType=b",
      "data": {
        "type": "WorkType",
        "label": "Books",
        "id": "b"
      }
    }
  }
}
```
