### ISSUE TITLE
Aggregations

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/platform#3895]
A few questions as to how aggregations should work to be most useful to clients.

## What to do when we have a filter and aggregation on the same field?

An example of this would be workType. 

### Currently
__Query:__ https://api.wellcomecollection.org/catalogue/v2/works?query=hogs&aggregations=workType

__Result:__ Works with hogs. Aggregation with all the workTypes in that set

__Query:__ https://api.wellcomecollection.org/catalogue/v2/works?query=hogs&workType=a&aggregations=workType

__Result:__ Works with hogs. An aggregation with just the workType we're filtering on.

__Question:__ Is this useful, or should the aggregations be relative to the query pre-filter?

---

**Comment by jtweed** [comment]
In the past (elsewhere), we've always found that the aggregations need to be pre-filter for that aggregation. Ie, users want it to have all values, not just the one selected.
