### ISSUE TITLE
Reindex to add Sierra data (notes etc)

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/platform#3904]
Reindex to make this Sierra data available in the API:

- citeAs (524)
- locationOfOriginal (535)
- dissertation (502)
- bindingInformation (563) added to physicalDescription (300)
- dimensions (300 c) and extent (300 a) merged into physicalDescription (300)
- contributors as Meeting (111, 711)
- add to subjects as Meeting (611)
- add to subjects as Concept (652)
- contents for audiovisual works (505)
- duration for audiovisual works (306)
- credits for audiovisual works (508, 511)
- alternativeTitle (246 a+b) when 246 not lettering (ind 6)
- edition (250)

**Comment by pollecuttn** [comment]
@jamesgorrie @warrd Are the fields listed above the correct ones that will become available after a reindex? There are others in the milestone but I don't know if they've already been reindexed.

Please add to the list above if more data will be made available after reindexing so we've got the full list for the Experience team.

**Comment by warrd** [comment]
@pollecuttn yes that looks correct to me

**Comment by warrd** [comment]
@pollecuttn there is also `alternativeTitles` and `edition`: these were added a while back and have already been reindexed, but not showing in the API yet (which it turns out is a separate process). I have added an issue for this: https://github.com/wellcometrust/platform/issues/3905

**Comment by pollecuttn** [comment]
@warrd Should this ticket be altered, then, to reindex *and* get these showing in the API? I thought reindexing would be enough but it sounds like it won't be

**Comment by warrd** [comment]
@pollecuttn the other ticket is for getting them showing in the API, so no need to alter this ticket (I am working on that one first, so when this is marked done everything should be available here)
