### ISSUE TITLE
Merge METS license info onto Sierra works

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3925]

**Comment by jamesgorrie** [comment]
@warrd @alicefuzier For visibility - could we please fill out what the plan for this is?

From what I gather the link is the B number from the METS file.
But the license, as it stands, is on items - for which we don't have a type of item 

Are we going to create a new type of item, that has the source identifier of the B number? And what would it's location be?

**Comment by warrd** [comment]
@jamesgorrie this is how the current implementation of the transformer creates a work from the METS XML data:

https://github.com/wellcometrust/catalogue/blob/master/pipeline/transformer/transformer_mets/src/main/scala/uk/ac/wellcome/platform/transformer/mets/transformer/Mets.scala

So it looks like we are creating a new item with a digital location containing the license, with the source identifier being the B number.

This will be merged onto the sierra  work down the line.

Does that answer your question?

**Comment by jamesgorrie** [comment]
@warrd - great! Just trying to keep up to date.

Do we know what the rules for the merging are going to be? Will this override the current Sierra item?

e.g.

__Before__
```JS
{
	"identifiers": [{
			"identifierType": {
				"id": "sierra-system-number",
				"label": "Sierra system number",
				"type": "IdentifierType"
			},
			"value": "b21053613",
			"type": "Identifier"
		},
		{
			"identifierType": {
				"id": "sierra-identifier",
				"label": "Sierra identifier",
				"type": "IdentifierType"
			},
			"value": "2105361",
			"type": "Identifier"
		}
	],
	"items": [{
		"locations": [{
			"locationType": {
				"id": "iiif-presentation",
				"label": "IIIF Presentation API",
				"type": "LocationType"
			},
			"url": "https://wellcomelibrary.org/iiif/b21053613/manifest",
			"type": "DigitalLocation"
		}],
		"type": "Item"
	}]
}
```

__after__

```js
{
	"identifiers": [{
			"identifierType": {
				"id": "sierra-system-number",
				"label": "Sierra system number",
				"type": "IdentifierType"
			},
			"value": "b21053613",
			"type": "Identifier"
		},
		{
			"identifierType": {
				"id": "sierra-identifier",
				"label": "Sierra identifier",
				"type": "IdentifierType"
			},
			"value": "2105361",
			"type": "Identifier"
		},
		{
			"identifierType": {
				"id": "mets-identifier",
				"label": "METS identifier",
				"type": "IdentifierType"
			},
			"value": "b21053613",
			"type": "Identifier"
		}
	],
	"items": [{
		"locations": [{
			"locationType": {
				"id": "iiif-presentation",
				"label": "IIIF Presentation API",
				"type": "LocationType"
			},
			"url": "https://wellcomelibrary.org/iiif/b21053613/manifest",
			"type": "DigitalLocation"
		}],
		"type": "Item"
	}]
}
```

**Comment by alicefuzier** [comment]
This is a good question, I need to speak with @jtweed about this. From what I remember - for _reasons_ - at least some digitised works are catalogued in sierra as separate bibs with one digital item. They reference the physical sierra bib (which has a different bnumber) in the MARC record, so we merge them to the physical sierra bib in the merger. 

The digital location in these works has no license 'cause that's only in the METS. The digital location that we create from METS is exactly the same, except that it will also have a license.
So I assume that we do want to replace the digital location with the one with the license, but we don't want to replace physical location or other digital locations (MIro).

The way we merge the physical and digital works is: we take a sierra work with one item with a physical location (physical work) and another sierra work with one item with a digital location (digital work) and we add the digital location to the list of locations on the item of the physical work. The digital work gets redirected.
If any of the two works have more than one item or more than one item, we skip the merge.

I assume we want to do something very similar for METS, except that we want to trump the digital location created by the merging with digital works if it exists
