### ISSUE TITLE
Add availability filter to Catalogue API

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3929]
Add a `items.location.type` filter to allow filtering for items with physical or digital locations.

**Comment by jtweed** [comment]
Already exists as filter for locationType.

**Comment by jamieparkinson** [comment]
@jtweed this already exists (as the `items.locations.locationType` query param), is there something I'm missing here?

**Comment by jamieparkinson** [comment]
There is - this is for `items.locations.type` as originally stated 🙃 . Needs discussion as to how it relates to https://github.com/wellcometrust/platform/issues/3930

**Comment by jtweed** [comment]
Superseded
