### ISSUE TITLE
Add availability aggregation to Catalogue API

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3930]
Add a `items.locations.type` aggregation to show whether things are available physically or digitally.

**Comment by jamesgorrie** [comment]
Just leaving a little tidbit here to think about in relating this to the workType filter.

Currently we filter on `workType.id` from query string parameter `workType`.

These IDs will inevitably become redundant. 

[From this comment on how we might model labelled, arbitrarily-string-IDed objects](https://github.com/wellcometrust/catalogue/pull/335#discussion_r363360860) (e.g. `WorkType`) I wonder if we could start to form some consistency.

## e.g. 1 use `.type`
We could add the filter `workType.type=Books` and `items.locations.type=DigitalLocation`.

The benefit of this, bar consistency is that we could implement a filter that doesn't use the Sierra workType IDs without having to reversion to API.

## e.g. 2 infer that if query path is to an object, we are querying on `.type`
This would then mean we could have:
* `workType=Books`
* `items.locations=DigitalLocation`

This feels a little to infer-y and reads a bit weird

## e.g. 3 we create and query on API generated IDs
In this case we don't use the ontologies and what has been, until this point, system like properties.

So we would have:
```JS
{
  "workType": {
    "type": "Books",
    "id": "books"
  },
  "items": [
    {
      "locations": [
        {
          "type": "DigitalLocation",
          "id": "digital-location"
        },
        {
          "type": "PhysicalLocation",
          "id": "physical-location"
        }
      ]
    }
  ]
}
```

and use either of the strategies above to either infer `.id`.

We're in the process of creating [ADT][adt]s for most labelled type data, and if we could think of a way of how we can query ADTs universally, that would be great.

We've got the the point now of when changing the model we need to think of storing and querying - hence brining this up.

PIng @alicefuzier and @warrd as they've been talking about it.

[adt]: https://en.wikipedia.org/wiki/Algebraic_data_type

**Comment by jtweed** [comment]
Superseded
