### ISSUE TITLE
AB relevance testing for notes fields

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3933]

**Comment by jamesgorrie** [comment]
[This has been made available to the client here](https://github.com/wellcometrust/catalogue/pull/191)

**Comment by harrisonpim** [comment]
![download-1](https://user-images.githubusercontent.com/11006680/67676260-0151ae00-f979-11e9-9027-167bef011f64.png)
No discernible difference in the distribution of clicks - I'm happy to close this and fold notes into the list of fields we query. Will be worth coming back to this when we run another set of tests on how we boost fields, but for now, it doesn't look like it's having an adverse affect.

@jtweed @taceybadgerbrook @jamesgorrie

**Comment by pollecuttn** [comment]
@jennpb fyi for the relevance testing of notes fields in search

**Comment by jamieparkinson** [comment]
No longer considered resolved https://github.com/wellcometrust/platform/issues/4019

**Comment by jamieparkinson** [comment]
Closed for now as per resolution of #4019
