### ISSUE TITLE
Per-manifestation (per IIIF Manifest) annotation list needs to be processed

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/platform#3935]
This was cut out of the processing to speed up the migration of digitized objects.

https://wellcome.slack.com/archives/CBT40CMKQ/p1570532531269100

@tomcrane Roughly when (time, or where in the migration) can this be deferred to?

**Comment by tomcrane** [comment]
It could happen after going live with the new storage. The Item page on wl.org does not use this data, but it is linked to from IIIF Manifests. If someone asks for one of these annotation lists, it will be generated on the fly - which will be slow.

The workflow processor can be run with different flags set:

* **RegisterImages**  (sync with DLCS)
* **RefreshFlatManifestations** (update DDS' summary info, used to power https://wellcomelibrary.org/service/collections/ and https://wellcomelibrary.org/collections/browse/genres/Gouaches/ and a few other things)
* **RebuildPackageCaches** (rebuild data that is used to build IIIF Manifests and item pages)
* **RebuildTextCaches** (full text maps for search, annotaiton lists etc)
* **RebuildAllAnnoPageCaches** (this is the thing I turned off - example https://wellcomelibrary.org/iiif/b28047345/images, identifies all the pictures in a book)

Later on, we can re-run it with only **RebuildAllAnnoPageCaches** set.

**Comment by pollecuttn** [comment]
@tomcrane Now that we've switched over are you able to do this now?

**Comment by pollecuttn** [comment]
This can be done once we have a staging DDS

**Comment by tomcrane** [comment]
This is now running on pl-santiago. It will just chug away in the background.

**Comment by tomcrane** [comment]
@pollecuttn ^

**Comment by pollecuttn** [comment]
Thanks, @tomcrane . How will I know when it's done and this issue is ready to be closed?

**Comment by tomcrane** [comment]
After 2 days it's done about 70,000 - so about 1/4 of the way through. It's doing them in b-number order (b100... .. b3....) which might make my estimate wrong though. But, a week or so.

**Comment by pollecuttn** [comment]
@tomcrane Has this finished yet? It's been a week.

**Comment by tomcrane** [comment]
No, it's still running. It had stopped due to the network issues but I restarted it last night.

**Comment by pollecuttn** [comment]
@tomcrane Has this finished? And if not, how much longer do you think it will take?

**Comment by tomcrane** [comment]
No, it's still running, has done about 116,000 b numbers (maybe 10m S3 requests?) so not half way through yet. It's only running one process - I could scale it up but I'm happy to just let it run through all the b numbers slowly and make these assets.

NB this sort of thing would be much easier with the DDS on AWS and tasks like this in scaling containers!

**Comment by jtweed** [comment]
Closing this so I can close the milestone and it looks like @tomcrane is well on top of it.

**Comment by pollecuttn** [comment]
Info from Tom C 19/12/19: 

"looks like it has nearly finished, it has churned through about 250,000 works, not too many more to go."

**Comment by pollecuttn** [comment]
@tomcrane Has this finished yet? Sounds like it might have done over the break.

**Comment by tomcrane** [comment]
@pollecuttn You can crack open the champagne, break out the nibbles and roll back the carpets for some dancing, because it has **_finished_**... On 20 Dec, no less.

**Comment by pollecuttn** [comment]
@tomcrane Hurrah! Thanks for letting me know :-)
