### ISSUE TITLE
Return more than 10 aggregations

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/platform#3944]
In order that we can return comprehensive data when responding to requests for aggregations we should be able to return greater than 10.

This means when using language aggregations [we have no english works](https://api.wellcomecollection.org/catalogue/v2/works?aggregations=language). That's probably wrong.

**Comment by jamesgorrie** [comment]
@jtweed @jennpb  Looking through the data we might need to think about how we do this.

Here's some numbers with some common queries:

| Field     | With no query | Botany | Paintings | Skeleton |
|-----------|---------------|--------|-----------|----------|
| Languages | 173           | 33     | 30        | 16       |
| Genres    | 3042          | 180    | 200       | 135      |
| Subjects  | 261694        | 4314   | 3161      | 438      |

__Languages__: I can see the interface as it stands being able to handle this information
__Genres__: This seems to get a little harder, 100-200 genres on any UI is tricky.
__Subjects__: I can't really see how any of these numbers would scale.

What @jamieparkinson and I have spoke about is finding a way to return all of them (although we will definitely be hit with a 10000 bucket size limit) - allowing us to work out what to do next.

Another choice would be to allow us to text search the subjects themselves and attach subjects to the query - the only thing is this doesn't give you the information up front about what subjects there are. Arguably 4314 subjects up front doesn't give an idea of it either.

Languages and workTypes however seem to work well.

**Comment by jtweed** [comment]
This is exactly why I suggested #3975, answering your question there. It's not feasible to desirable to return all for certain aggregations, but it is for others.

**Comment by jamesgorrie** [comment]
Assuming thought that frequency is the most important thing - surfacing outliers feels really important especially for researchers looking for such a thing.

Another use case where this would be useful would is people who aren't using our interface, or analysing data with a machine.

Maybe at first we supply all to allow for testing and also have an `aggregationsSort` parameter, which could be useful in a few instances (and easy to implement)?

When working with the performance on this we might need to see if pagination is something we do, but by releasing this we allow for the client to chose what they want without offering infinite flexibility.

**Comment by jamieparkinson** [comment]
Resolved by https://github.com/wellcometrust/catalogue/pull/233 (for now)
