### ISSUE TITLE
Upgrade Reporting Elasticsearch & Kibana to 7.4.1

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/platform#3951]
In order to provide improved data aggregation and pivot features coming up, we should upgrade to ES 7.4.1 (latest) - current version is v6.8.0.

See [release notes](https://www.elastic.co/guide/en/elasticsearch/reference/current/es-release-notes.html).

**Comment by jtweed** [comment]
Yes please!

**Comment by kenoir** [comment]
This is waiting on some changes to the reporting code - is there a referencing ticket @jamesgorrie @harrisonpim ?
