### ISSUE TITLE
Do we still need the "look up ingests by bag ID" endpoint?

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#3966]
- [x] Stop the ingests API serving this endpoint
- [x] Stop the ingests worker updating the database
- [ ] Delete the database

This is marked as a temporary route in the ingests API:

https://github.com/wellcometrust/storage-service/blob/70788ca91d7c88ba3e5e816dc0ebe99bd96f6ee9/api/ingests_api/src/main/scala/uk/ac/wellcome/platform/storage/ingests/api/IngestsApi.scala#L99-L116

Can we ditch it now? There's a lot of inconsistent/bad data in that database, so if you query it you'll get pointers to ingests that don't exist.

(If we do need it, we should tidy it up before we do https://github.com/wellcometrust/platform/issues/3948)

**Comment by tomcrane** [comment]
Is this a useful thing to have?

![image](https://user-images.githubusercontent.com/1443575/67479106-372f2380-f655-11e9-93e4-1b82f28476ee.png)

Obviously it was very useful in migration. But is it useful to have at other times, not necessarily in this dashboard but in other things too?

Its purpose in the above is diagnostic. "What happened to my ingest? Why did it fail?"

**Comment by alexwlchan** [comment]
We are tracking the ingest ID in the storage manifests (but not externally).

**Comment by tomcrane** [comment]
Maybe reframe "What happened to my ingest?" to

"What happened to the ingest that System X made? It never got to a successful storage manifest, I have no way of finding it to diagnose by inspecting its events."

That API gives you a view of activity for a bag identifier, independent of the client that initiated the activity. Any one client can keep a record of the ingests it has attempted, but do you need a non-client-specific view? We did in migration, where the clients are dashboard, or multiple python processes ingesting at scale. Would that kind of thing be required again? E.g., inspect what Goobi has been sending, independent of Goobi.

(I don't know..)

**Comment by alexwlchan** [comment]
Chatted to @jtweed about this, and yeah this endpoint is going away. Will update the ticket with individual tasks.
