### ISSUE TITLE
Investigate if it's worth having tests to make sure parameters are documented automatically from AKKA

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/platform#3967]
https://github.com/wellcometrust/catalogue/pull/192#discussion_r338918532

**Comment by warrd** [comment]
I already introduced tests here for this: https://github.com/wellcometrust/catalogue/pull/192/commits/ef7fbe76743d45d5da5ae85305ea85a5e50211d4

Though could probably be built upon.
