### ISSUE TITLE
Redirecting pre-migration image services

### ISSUE THREAD

**Issue by tomcrane** [wellcometrust/platform#3986]
Consider this use of a "naked" Image API endpoint (not in the context of a Manifest):

![image](https://user-images.githubusercontent.com/1443575/67633841-efa2d480-f8ac-11e9-9096-078dad1664bb.png)

(at http://palette.davidnewbury.com/)

This will continue to work, because the old images are still in the DLCS. But we probably don't want to maintain 40m rows in the old DB. That's a lot of rows, not to mention ~160m thumbnails in S3. We want to redirect them to their storage-service equivalents, which in this case is this image service:

https://dlcs.io/iiif-img/wellcome/5/b16728312_L0067099.jp2/info.json

How do I know that? because it has the same metadata, but in space 5. It's the 0th image of the 0th manifestation of b16728312.

We could add in something that intercepts image requests to .../wellcome/1/<guid>(.*) and redirects them to .../wellcome/5/<new-id>{0}. This could run straight of the PostgreSQL data, but that would mean keeping the rows. Instead, a one-off exercise could map all the current images to their new ones, and store the mapping in Dynamo (or equivalent), and the redirector can look up the new location in there.

This is not a dependency for migration, as we don't need to delete the old rows for a long time. But there will be an awful lot of refs to Wellcome image services out there, whether direct like this or because someone is working off an old manifest.

**Comment by alexwlchan** [comment]
Additionally, it would be nice to 301 all those old requests to the new URLs.

Gradually the pool of pages pointing at old URLs will shrink. I can't imagine us ever turning off the redirect service, but it should get less and less traffic over time.

**Comment by alexwlchan** [comment]
Discussed with @jtweed – we're not going to do this redirect, but we are going to record the asset ID ~> new ID mapping somewhere. (Which is now easy to obtain, since we have all the Preservica code.)

**Comment by alexwlchan** [comment]
There's an initial version of this map at `s3://wellcomecollection-storage-infra/preservica_ids.db`. It's got ~95% of the Preservica GUIDs, and I think I can backfill the rest from the Preservica SQL database tomorrow.

I'm going to write a quick README around it, then bung a copy in the storage service.

**Comment by alexwlchan** [comment]
Okay, this has proven sufficiently fiddly that it's not worth doing. Closing as WONTFIX.
