### ISSUE TITLE
Move dissertation, citeAs and locationOfOriginal into notes

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3996]
Rather than have separate properties for `dissertation`, `citeAs` and `locationOfOriginal`, I think now that we have settled on a more structured approach to other notes we should follow that scheme here too.

So each of these should be added a separate kind of note, as in MARC.

**Comment by jamesgorrie** [comment]
With these three fields, we seem to be making this mistake:
https://github.com/wellcometrust/platform/issues/3998

We're going to ditch that functionality and draw from all subfields (i.e. `content`).
