### ISSUE TITLE
locationOfOriginal is not pulling all data

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#3999]
Data is not being joined from all subfields in MARC 535 locationOfOriginal.

We're also currently only taking the first value when we should be taking all. There is a separate ticket to make this a type of note, which will allow us to take all values - we should make sure to do this.

Example: b20061304

**Comment by warrd** [comment]
With https://github.com/wellcometrust/catalogue/pull/216 and https://github.com/wellcometrust/catalogue/pull/228 this may have been addressed,

The current behaviour is to create a separate `location-of-original-note` for each varfield 535, which contains all subfields concatenated together with a space (this is the same for all notes fields currently, as per [this comment](https://github.com/wellcometrust/catalogue/pull/216#issuecomment-547522683)). Does this sound correct?

**Comment by warrd** [comment]
@jtweed ping about the above :point_up:

**Comment by jtweed** [comment]
I think we want one note, with multiple entries in contents?
