### ISSUE TITLE
AB test changing the default querying operator from OR to AND

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/platform#4010]

**Comment by jamieparkinson** [comment]
It is easier to do this and https://github.com/wellcometrust/platform/issues/4017 simultaneously than to do each separately

**Comment by jamieparkinson** [comment]
Because of the above this is kind of blocked by https://github.com/wellcometrust/platform/issues/4019

**Comment by jamieparkinson** [comment]
Required changes:

- [x] API changes
- [ ] wellcomecollection.org Lambda changes

**Comment by harrisonpim** [comment]
Looks like the switch to AND is increasing the skew towards clicks at the top end of results, without reducing the overall number of clicks further down, which is exactly what we wanted to see. This tracks across both 'discerning' and 'non-discerning' users. Happy to make the switch to AND as default and begin another test.

![download](https://user-images.githubusercontent.com/11006680/68960502-2db65880-07c8-11ea-8aa0-83aaa9988325.png)

**Comment by kenoir** [comment]
Nice.

![nickelgraph](https://user-images.githubusercontent.com/953792/69046884-e4e1e800-09f1-11ea-855e-59b7772a1dba.gif)
