### ISSUE TITLE
Our AWS cold replica should use DEEP_ARCHIVE

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#4013]
I remember @jtweed discussing this a while back.

Right now we lifecycle everything to Glacier after 90 days, so I don't think anything has landed there yet. Would be good to sort that out before it starts falling off the end.

~We'll need to merge https://github.com/wellcometrust/storage-service/pull/397 first.~

**Comment by pollecuttn** [comment]
Decided to use Deep Archive

**Comment by alexwlchan** [comment]
Ah, so this isn't as simple as it looks – it requires v2.4.0 of the AWS Terraform provider:

https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#240-march-29-2019

Possibly tied to https://github.com/wellcometrust/platform/issues/3820
