### ISSUE TITLE
Add logging to scheduled search metric calculations in ECS

### ISSUE THREAD

**Issue by harrisonpim** [wellcometrust/platform#4051]
#3942 added a set of scheduled ECS tasks which calculate search relevance metrics that couldn't be produced in kibana alone. These calculated metrics are pushed into a set of new indexes in the reporting cluster, from which we report the metrics.

The current setup doesn't include logging, so we can't tell if/how the tasks are breaking. We should add the ability to log errors etc from the containers into cloudwatch or APM?

**Comment by jamieparkinson** [comment]
Is this still relevant?
