### ISSUE TITLE
Image search prototype

### ISSUE THREAD

**Issue by jamieparkinson** [wellcometrust/platform#4070]
We want to prototype a frontend for image-first searching in order to inform possible work on images as first class objects - this will involve:

- Resurrection of the grid view for search (on a new page).
- Filtering out everything but works with the IIIF locationType.
- Allow images to be clicked -> expanded -> linked to the works to which they belong.
- _bonus_: show/link some relevant images in the expanded view.

**Comment by jamieparkinson** [comment]
@jtweed ^ as discussed

**Comment by pollecuttn** [comment]
26 November 2019

Get behind a toggle, using the current URL.

Use c) scoped filters example

Filters:
ALL IMAGES
Date

- Images only in search results
- No titles in search results

Click image to open panel which has:
- image
- title
- description
- licence

# Measurement

## More engagement
- works viewed
-  works downloaded

Track both in Kibana (@taceybadgerbrook @jamieparkinson @jamesgorrie @harrisonpim )

## Search relevance
- already being tracked; @jamesgorrie / @taceybadgerbrook to discuss

**Comment by harrisonpim** [comment]
A majority of works in the palette API are 404ing as a result of the problems described in #4078.

**Comment by jamieparkinson** [comment]
The first pass of this is contained in https://github.com/wellcometrust/wellcomecollection.org/pull/4898, the work will be continued in https://github.com/wellcometrust/platform/issues/4079
