### ISSUE TITLE
Refine image search prototype

### ISSUE THREAD

**Issue by jamieparkinson** [wellcometrust/platform#4079]
The image search prototype of https://github.com/wellcometrust/wellcomecollection.org/pull/4898 is a first pass, next we need to:

- ~Add related images to the panel~
- Ensure copy and link to work/item is correct in panel
- Add tracking for panel expansion etc
- ~Remove the separate image search page~ ~and toggle~ ~and add an "opt-in" to the works search to go to an images-only search.~
- ~Open in same tab and remember search position on back to results~

**Comment by jamieparkinson** [comment]
cc @jennpb

**Comment by jennpb** [comment]
Before we make this available to everyone, I'd like to:
- change preview panel background to charcoal / use white for text
- Change primary CTA button label to `View image`
- Change secondary CTA to `LinkLabels` style; label text reads `About this work`
- Change `Related images` to `Visually similar`

Further refinements can be made later.

cc @GarethOrmerod @davidpmccormick @gestchild
