### ISSUE TITLE
APM is filling the logs with warnings

### ISSUE THREAD

**Issue by jamieparkinson** [wellcometrust/platform#4098]
![image](https://user-images.githubusercontent.com/4429247/70251948-68ccfb80-1778-11ea-9c60-8f21229891e5.png)

**Comment by jamesgorrie** [comment]
Love it - another thing to think about here then is retention and Index lifecycle management - the joy 🎄

**Comment by jamieparkinson** [comment]
Thankfully I think APM does that for us - https://www.elastic.co/guide/en/apm/server/current/ilm.html#ilm-default
