### ISSUE TITLE
Extract items in order in the Sierra transformer

### ISSUE THREAD

**Issue by alicefuzier** [wellcometrust/platform#4102]
Part of #4082

**Comment by pollecuttn** [comment]
From III:
Like the SDA, the API returns attached items in the order that they are stored in the database. Often, as in the record shown below, that's the order in which the items were entered and attached to the bib record.
  
Request URL
https://libsys.wellcomelibrary.org:443/iii/sierra-api/v5/items/?fields=id&deleted=false&bibIds=1265686&suppressed=false
Response Body
{
  "total": 9,
  "entries": [
    {
      "id": "1258398"
    },
    {
      "id": "1258399"
    },
    {
      "id": "1258400"
    },
    {
      "id": "1258401"
    },
    {
      "id": "1258402"
    },
    {
      "id": "1258403"
    },
    {
      "id": "1258404"
    },
    {
      "id": "1258405"
    },
    {
      "id": "1258406"
    }
  ]
}

**Comment by alicefuzier** [comment]
Uhmm it would be good to see an example of a bib where items have been re-ordered when catalogued (ie. where the order is not sequential by item id).

If this gives us items in the same order as they appear when they get digitised in goobi, this is good cause at least we know where to get that information. 
It is a bit bad in that it requires a significant rehauling of the sierra-adapter and a resync of the sierra VHS.

**Comment by alicefuzier** [comment]
Ok, this doesn't seem to return the right order for b29753247:
https://libsys.wellcomelibrary.org/iii/sierra-api/v5/items/?deleted=false&bibIds=2975324&suppressed=false&fields=id,varFields gives 
```
{
    "total": 17,
    "entries": [
        {
            "id": "1908302",
            "varFields": [
                ...
                {
                    "fieldTag": "v",
                    "content": "Envelope"
                }
            ]
        },
        {
            "id": "1908303",
            "varFields": [
                ...
                {
                    "fieldTag": "v",
                    "content": "1"
                }
            ]
        },
        {
            "id": "1908304",
            "varFields": [
                ...
                {
                    "fieldTag": "v",
                    "content": "2"
                }
            ]
        },
        ...
        {
            "id": "1908316",
            "varFields": [
                ...
                {
                    "fieldTag": "v",
                    "content": "14"
                }
            ]
        },
        {
            "id": "1908317",
            "varFields": [
                ...
                {
                    "fieldTag": "v",
                    "content": "0"
                }
            ]
        }
    ]
}
```
but `1908317` with title 0 appears second, not last in Encore: http://search.wellcomelibrary.org/iii/encore/record/C__Rb2975324?lang=eng

**Comment by pollecuttn** [comment]
Question to III:  We need the SDA/Encore sequence, but are getting something else in the json. How do we get the SDA/Encore sequence of items from the Sierra REST API?

Answer: This would be an Idea Lab enhancement request. There is no setting in the API to return the items in a different order.

**Comment by alicefuzier** [comment]
I guess a question to ask would be: if the SDA returns the items in the correct order and the API doesn't, how does the SDA figure the order out? Is it something that we can replicate? Does it not make an API request?

**Comment by pollecuttn** [comment]
@alicefuzier I've added your questions to III's ticket

**Comment by pollecuttn** [comment]
Answer from III:
Sierra's default mode of storing records is in the order in which items are attached to bibs. That's the order you get from the API. In the SDA, you can reorder the display and save that - I think this is what you refer to as the "correct" order (I think of this as "preferred"). The API does not check for how items are listed in the SDA and does not retrieve the saved order, which I believe may be stored in a different table. We have in the past made changes to which table the API fetches data from when we find that the data in one table better fits the needs of our API users. We have also included additional fields from tables when the data already exists, but was just not being fetched.

There is currently no way to include a preferred sort order in an API request, but maybe there should be. Our API development team is very responsive to suggestions from Idea Lab. They really are always looking for way to make the APIs more useful. Including a use case scenario helps our team understand why your request is important to you and how it might help other users as well.

**Comment by pollecuttn** [comment]
Added to III idea lab https://idealab.iii.com/alwaysopen/Page/ViewIdea?ideaid=13996

**Comment by alicefuzier** [comment]
We don't have enough information to do this, so we are not doing it for the time being

**Comment by pollecuttn** [comment]
III Idea Lab above was closed in favour of the earlier https://idealab.iii.com/alwaysopen/Page/ViewIdea?ideaid=13552

**Comment by pollecuttn** [comment]
From IdeaLab: 

> Returning items in specified order or returning, e.g., the sierra_view.bib_record_item_record_link.items_dipslay_order data in the API response will allow applications to display the attached records in the correct order.

See https://techdocs.iii.com/sierradna/Home.html?viewGroupName=Item#bib_record_item_record_link
