### ISSUE TITLE
update identifiers generation script for feature-similarity

### ISSUE THREAD

**Issue by harrisonpim** [wellcometrust/platform#4111]
Currently, a `generate_identifiers.py` script generates the `identifiers.pkl` file used for the `palette-similarity` API. This has been modified slightly for the `feature-similarity` API but the script is no longer coherent as a result. Additionally, the use of a `.pkl` file doesn't make it easy to update the data dynamically based on updates to the catalogue.

**Comment by harrisonpim** [comment]
https://github.com/wellcomecollection/reporting/pull/29 
> adds a reporting lambda which subscribes to miro sourcedata updates and reindexes, querying the miro migration and source data for relevant identifiers and indexes of corresponding feature vectors for the palette- and feature-similarity APIs

**Comment by jamieparkinson** [comment]
It looks like the naming & scope of this issue and the associated PR no longer really encapsulate the work (eg there will need to be a separate ticket for the similarity APIs to consume the new index, right?)
