### ISSUE TITLE
Tidy up IAM keys for production access

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#4115]
Noting the issue Ashley was facing this morning: by default, Filezilla Pro will try to list all buckets/directories. In **Site Manager** > **My Sites** > **S3 - IHA Goobi Transfer** > **Advanced** tab >> **Default remote directory**.

@kenoir I couldn't find the Terraform defining these users, so I did it in the console. Notes below so you can copy it to the terraform.

* Delete the second key on in_house_archives

* Create an access key pair for digitisation_services

* Add this policy to the three IAM roles:

    ```json
    {
        "Sid": "",
        "Effect": "Allow",
        "Action": "s3:List*",
        "Resource": "arn:aws:s3:::wellcomecollection-workflow-upload"
    }
    ```

* Add this policy to the editorial_photography user:

    ```son
    {
        "Sid": "",
        "Effect": "Allow",
        "Action": "s3:*",
        "Resource": "arn:aws:s3:::wellcomecollection-workflow-upload/editorial/*"
    },
    ```

**Comment by pollecuttn** [comment]
Following on from https://github.com/wellcometrust/platform/issues/4076

**Comment by alexwlchan** [comment]
Copying message from [Ashley in Slack](https://wellcome.slack.com/archives/CN56BRQ5B/p1576495610004700?thread_ts=1576145176.010000&cid=CN56BRQ5B):

> I've had to move the folders to make the lambda work again and it's caused an issue with permissions. I've moved
> 1. `digitisation_services`
> 2. `in_house_archives`
> 3. `in_house_photography`
> Underneath `digitised` in `wellcomecollection-workflow-upload`

**Comment by kenoir** [comment]
Reminder to myself we could use PMP.

**Comment by pollecuttn** [comment]
Terraform this
