### ISSUE TITLE
Add access conditions from Sierra to physical locations

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#4125]
In addition to the access conditions for digitised content (#3946), we need to add access conditions for physical locations from Sierra.

This will require one addition to the model, to represent the date the condition is valid until:

```
accessConditions: [
    {
        "type": "AccessCondition",
        "terms": "Usage terms go here",
        "status": {
            "type": "AccessStatus",
            "id": "closed",
            "label": "Closed"
        },
        "to": "2030-01-01",
    }
]
```

- `terms` comes from `506 $a`
- `status` comes from `506 $f` or is `open` if `ind1` is `0`
- `to` comes from `506 $g`

Statuses should mapped to the same list as for digitised content. This may require a mapping, but we don't have a comprehensive list of the values in Sierra, so we will need to create that first.

**Comment by jamesgorrie** [comment]
> we don't have a comprehensive list of the values in Sierra, so we will need to create that first.

[From conversations elsewhere](https://github.com/wellcometrust/platform/issues/4063), [this policy](https://wellcomelibrary.org/content/documents/policy-documents/access-to-personal-data.pdf) is what we should be following for this as it's what they have been using for cataloguing and is very comprehensive. 

Section 3.2:
- Open
- Open with advisory
- Restricted
- Closed

There seems to be a whole load of contexts which this model ncely caters for, but we should be keeping an 👁 out for standardisation if there is any (cultural sensitivity / data protection etc).
