### ISSUE TITLE
Redirect www.wellcomecollection.org to wellcomecollection.org

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#4165]
Right now, if you visit <https://www.wellcomecollection.org/>, you get a Code Enigma error page:

![Screenshot 2020-01-14 at 16 26 31](https://user-images.githubusercontent.com/301220/72362214-a95e5400-36ea-11ea-9482-dfa02348f09f.png)

There's an A record in Route53 pointing a Code Enigma server: https://console.aws.amazon.com/route53/home?#resource-record-sets:Z3THRVQ5VDYDMC

We should:

- [x] Check with Kate what this server is doing, and if it's anything important
- [ ] If not, remove this A record, and replace it with a redirect to wellcomecollection.org

**Comment by jamesgorrie** [comment]
Re: code enigma, nothing should be pointing to their servers. We can point to the cloudfront distro, and redirect from there

**Comment by alexwlchan** [comment]
Follow-up question: if nothing should be pointing to those servers, should those servers exist, or should we be asking them to decommission something?

**Comment by jamesgorrie** [comment]
They don't exist, I am assuming this might be a catch all on their side. I will flag it with them as I am working with turning off all those things now making sure we're not paying for anything.
