### ISSUE TITLE
Sierra adapter doesn't delete records that were edited the same day they were deleted

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#4173]
Jenn has noticed a bug in the pipeline where some deleted Sierra records aren't being suppressed on the website (for an example, see [messages in Slack](https://wellcome.slack.com/archives/C8X9YKM5X/p1579106005008700]).

My theory is that this is caused when a record is edited on the same day it was deleted. If we look in VHS for this record, it has an updated timestamp `2019-09-14T11:39:54Z`. If we look at the Sierra API response, it says `"deleted": "2019-09-14"`. Depending on how we do the date comparisons in the adapter, we might be ignoring the deletion as older.

The rule should be:

    (deletions on day X) > (edits on day X) > (edits or deletions on day X–1)

Once we've fixed the adapter, we can either reharvest all of Sierra, or get a list of deleted bibs with this API harness:

<details>
<summary>sierra_api.py</summary>

```python
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
import json
from pprint import pprint
import sys

import requests

oauthkey = "<API_KEY>"
oauthsec = "<API_SECRET>"

BASE = "https://libsys.wellcomelibrary.org/iii"
API_VERSION = "sierra-api/v3"

# Change this URL to whatever resource you want to retrieve
#
# Useful options:
#
#   - /bibs?id=1234567 will look up an individual bib
#   - /bibs?deleted=true will get you all the deleted bibs
#
URL = BASE + "/" + API_VERSION + "/bibs?deleted=true"

# Get an access token
# https://sandbox.iii.com/docs/Content/zReference/authClient.htm
resp = requests.post(f"{BASE}/{API_VERSION}/token", auth=(oauthkey, oauthsec))
access_token = resp.json()["access_token"]

# https://sandbox.iii.com/docs/Content/zReference/authClient.htm
# https://sandbox.iii.com/docs/Content/zReference/operations.htm#XML,
headers = {
    "Authorization": f"Bearer {access_token}",
    "Accept": "application/json",
}
print(f"*** Fetching contents of {URL}")
r = requests.get(URL, headers=headers)

try:
    pprint(r.json())
except json.decoder.JSONDecodeError:
    if r.status_code == 404:
        print(r)
        print("*** 404 error: URL not found")
        sys.exit(1)
    elif r.status_code == 405:
        print(r)
        print("*** 405 error: Method not allowed")
        sys.exit(1)
    else:
        print(r)
        raise
```
</details>

h/t @kenoir for debugging help

Steps to fix:

- [ ] Fix the bug in the Sierra adapter
- [ ] Go back and suppress any deleted records that were missed by this bug

**Comment by alexwlchan** [comment]
Yep, this checks out.

Look at https://github.com/wellcometrust/catalogue/blob/e778279812f5b36bb8bb301ad87ff5e959a4c93d/sierra_adapter/sierra_reader/src/main/scala/uk/ac/wellcome/platform/sierra_reader/flow/SierraRecordWrapperFlow.scala

We'd create the deleted date like so:

```
scala> import java.time.{Instant, LocalDate, ZoneOffset}
import java.time.{Instant, LocalDate, ZoneOffset}

scala> import java.time.format.DateTimeFormatter
import java.time.format.DateTimeFormatter

scala> val formatter = DateTimeFormatter.ISO_DATE
formatter: java.time.format.DateTimeFormatter = ParseCaseSensitive(false)(Value(Year,4,10,EXCEEDS_PAD)'-'Value(MonthOfYear,2)'-'Value(DayOfMonth,2))[Offset(+HH:MM:ss,'Z')]

scala> val deletedDate = LocalDate.parse("2019-09-14", formatter).atStartOfDay().toInstant(ZoneOffset.UTC)
deletedDate: java.time.Instant = 2019-09-14T00:00:00Z
```

We'd create the modified date like so:

```
scala> val modifiedDate = Instant.parse("2019-09-14T11:39:54Z")
modifiedDate: java.time.Instant = 2019-09-14T11:39:54Z
```

Later on, in the bib merger (https://github.com/wellcometrust/catalogue/blob/aac5b505fec6419159f6a643e6c0ff356d414d4e/sierra_adapter/sierra_bib_merger/src/main/scala/uk/ac/wellcome/platform/sierra_bib_merger/merger/BibMerger.scala#L20), we'd do this comparison:

```
scala>
scala> deletedDate.isAfter(modifiedDate)
res2: Boolean = false
```

And the pipeline would quietly drop the deletion event, on the basis that it's "older" than the update event.

**Comment by alexwlchan** [comment]
I’ve got a script running that’s dumping a complete list of every record ever deleted from Sierra.

**Comment by pollecuttn** [comment]
@alexwlchan Is this going to impact Sierra's performance?

**Comment by alexwlchan** [comment]
@pollecuttn shouldn’t do, it’s a simple query
