### ISSUE TITLE
Create an items filter in the catalogue API

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#4180]
For the stacks service, we need to be able to query the API for works with a particular item ID, e.g.

```http
GET /works?items=vphnmzg9,kjvkk3vx
```

**Comment by jamesgorrie** [comment]
You can currently use the `query` for this - but it isn't really what we're looking for.
We might change the url param name too.

**Comment by alexwlchan** [comment]
> You can currently use the `query` for this - but it isn't really what we're looking for.

Yeah, that does an ES query? For the item requesting, all our use would be a plain filter, so kinder to the cluster.

> We might change the url param name too.

Which URL param name? `?items=`?

I discussed this with Jonathan last week – the full path is `items.id`, but we truncate the `.id` if so.

**Comment by jamesgorrie** [comment]
> so kinder to the cluster.

We're not really concerned with this due to our minute scale.

It is however a more "pure" query as if something had the item ID in the description for example, it would also be returned via the query.

> but we truncate the .id if so.

Nice to - this was suggested a while back but never "decided" - but glad it is.

**Comment by alexwlchan** [comment]
Just discussed with Robert! I remember now:

Right now the stacks API takes a work ID as a parameter; it would be nicer if it took an item ID as a parameter instead (or a list of item IDs), and then we query the `/works` API for something with that item.

**Comment by alexwlchan** [comment]
Discussed with Robert; we don't actually need this.
