### ISSUE TITLE
What is the bucket wellcomecollection-assets-archive-storage?

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#4200]
It's in the platform account, and looks like an early prototype of the storage service. Can we delete it?

**Comment by tomcrane** [comment]
@alexwlchan FWIW, there is no reference to this bucket in either the DDS or the DLCS configuration/tf/etc.

**Comment by alexwlchan** [comment]
@tomcrane Yeah, it's a very incomplete copy of the archive which shouldn't be in use anywhere.

**Comment by alexwlchan** [comment]
Per Jonathan in Slack, this is a test for the storage service, and can most likely be deleted.

**Comment by alexwlchan** [comment]
It's gone!
