### ISSUE TITLE
Zero count workType aggregations not returned from the API

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/platform#4223]
If a call to the API with the `aggregations` query parameter set doesn't have any results in a particular `workType` (i.e. if the `count` is `0`), the bucket isn't returned at all, rather than it being returned with `count: 0`.

This is causing a problem on the frontend of wellcomecollection.org where if you have filtered a search by `workType` that _did_ return results, then perform a subsequent search (with the same filter applied) that doesn't return any results, we aren't able to show you that in the UI without storing our own reference of what the various `workType` buckets could be.

Storing [our own hard-coded object](https://github.com/wellcometrust/wellcomecollection.org/blob/4226c2d616d9a81a9b90977f9434cc4335d68c36/common/services/data/work-type-aggregations.js) is almost certainly a Bad Idea and this problem would go away if all buckets were always returned regardless of count.

Is this feasible? If not, do you have alternative suggestions of how to circumvent our frontend issue ideally without 1. doing another http request or 2. hard-coding anything that's liable to change?

**Comment by jamieparkinson** [comment]
Hmmm, we do have the option of setting `min_doc_count` to `0` for our aggregations, although the docs do mention some caveats there - https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_minimum_document_count_4

I feel like there are probably some scenarios where we don't want to surface buckets with a 0 count - I guess we'd be saying that responsibility moves to the frontend?

**Comment by jamieparkinson** [comment]
cc @jamesgorrie know any issues with using `min_doc_count`?

**Comment by davidpmccormick** [comment]
Yeah, I think it would be on the frontend to hide zero count buckets (with the exception of whichever workTypes a user had selected before the count was 0).

**Comment by jamesgorrie** [comment]
we couldn't use it because we were using compound aggs. Otherwise, 🚀 with it!

**Comment by jamesgorrie** [comment]
> I feel like there are probably some scenarios where we don't want to surface buckets with a 0 count - I guess we'd be saying that responsibility moves to the frontend?

Yes.
