### ISSUE TITLE
Comment on Sierra_film json example

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/platform#454]
@ChristopherHilton 

https://github.com/wellcometrust/platform-api/blob/master/ontologies/Sierra_film.md#L3

```md
Comment at line 117 and subsequent occurrences of "authority": "MeSH"
```
MeSH terms come from 650.2

```md
Comment at lines 144-163: These general notes are differentiated by slightly different MARC codes. Do we want to reproduce these differences?
```
I would think we do want to preserve these as they usefully indicate e.g. different roles for agents such as director, presenter

**Comment by kenoir** [comment]
Pinging @silveroliver to review or close.
