### ISSUE TITLE
Comment on Sierra_book.json example

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/platform#455]
@ChristopherHilton 

https://github.com/wellcometrust/platform-api/blob/master/ontologies/Sierra_book.md#L5

FAST is LCSH for linked data, not just a simplified recasting.

5xx notes would be useful to stay distinguished - not sure why we would want to squash the nuance down into just "notes".

**Comment by ChristopherHilton** [comment]
Fair point re FAST, I’ll tweak.
RE the 5xx notes: we don’t surface those differences to the readers, do we (unless they ask for the MARC view: I doubt anyone does)?  So I suppose the question is that they’ll certainly be distinguished in the native Sierra metadata but to what extent we want that distinction to swim up further.  Maybe the key decider is thinking what other people might want from our data using the API – maybe that makes the case for retaining the distinctions?  For our own users I doubt that they’re significant.
C

**Comment by pollecuttn** [comment]
5xx notes: yes, we do, e.g. 
502 is labelled to users as 'Thesis' http://search.wellcomelibrary.org/iii/encore/record/C__Rb1000624
505 is labelled to users as 'Content' http://search.wellcomelibrary.org/iii/encore/record/C__Rb1000116
5051. is labelled to users as 'Incomplete contents' http://search.wellcomelibrary.org/iii/encore/record/C__Rb1016580
510 is labelled to users as 'References' http://search.wellcomelibrary.org/iii/encore/record/C__Rb1000624

There's lots of different labels we use to distinguish the notes in public displays.

**Comment by ChristopherHilton** [comment]
OK!

**Comment by pollecuttn** [comment]
@ChristopherHilton There's lots of different labels we use on lots of different MARC fields/groups in various public displays (e.g. default, MISC, Art, etc), and not just for notes.

I'm not sure how much you need to know but I can show you all of it so that you're aware of them.

**Comment by pollecuttn** [comment]
Also re FAST: I got that wrong. It's available as linked data but not only linked data. I'm not sure that describing it as a simplified recasting of LCSH is quite correct as it retains the same vocabulary of LCSH but facets them (see "Details" at http://www.oclc.org/research/themes/data-science/fast.html)
