### ISSUE TITLE
Weird API results dirt doc

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#667]
Issue to track anywhere the API is spitting out weird data, or there’s a suggestion the transformation pipeline has screwed up. These can be spun out into proper issues if/when we decide to fix them properly.

---

"Awaiting Description"

- https://api.wellcomecollection.org/catalogue/v0/works/a4a9xgrj
- https://api.wellcomecollection.org/catalogue/v0/works/a6vxfspv
- https://api.wellcomecollection.org/catalogue/v0/works/a6vxfspv

"--"

- ~https://api.wellcomecollection.org/catalogue/v0/works/a4aged89~
- ~https://api.wellcomecollection.org/catalogue/v0/works/a6vtydty~
- ~https://api.wellcomecollection.org/catalogue/v0/works/easjckxn~

"-"

- ~https://api.wellcomecollection.org/catalogue/v0/works/a9a22w88~

Other places where label/description is a bit iffy:

- https://api.wellcomecollection.org/catalogue/v0/works/a9a5vrbv
- https://api.wellcomecollection.org/catalogue/v0/works/a82jcsyr
- https://api.wellcomecollection.org/catalogue/v0/works/acmseadm

**Comment by alexwlchan** [comment]
Encoding issues:

* https://api.wellcomecollection.org/catalogue/v0/works/d2bqfj9j
* https://api.wellcomecollection.org/catalogue/v0/works/f3uxeebk
* https://api.wellcomecollection.org/catalogue/v0/works/urpej5mt
* https://api.wellcomecollection.org/catalogue/v0/works/kkxk5hq6

**Comment by alexwlchan** [comment]
Another encoding issue, seems different to the last one: https://api.wellcomecollection.org/catalogue/v0/works/a3ns6ss3

**Comment by jennpb** [comment]
Here's one where the date is definitely not the correct date - may be a mistake in the source, not the transformation pipeline
https://api.wellcomecollection.org/catalogue/v0/works/fnsfc5mu / https://next.wellcomecollection.org/works/fnsfc5mu

**Comment by alexwlchan** [comment]
Encoding issues abound: https://api.wellcomecollection.org/catalogue/v0/works/a24kd96u (broken on stage, not prod)

**Comment by alexwlchan** [comment]
All the ones with funky descriptions are going to be purged in the Miro preprocessor pipeline. Closing for now, we can open new issues for new errors spotted.
