### ISSUE TITLE
Problematic licences in MIRO V images

### ISSUE THREAD

**Issue by ChristopherHilton** [wellcometrust/platform#711]
Specific examples:
Numerous images are marked as having the licence "Academics" but are not copyright cleared so do not appear on the website.  One is "Academics" but copyright cleared - no. V0048812.  CH to pursue if we can just change this to a CC licence.

**Comment by ChristopherHilton** [comment]
On further searching MIRO served up five V images that were "Restrictions on use" = "Academics" and "Copyright Cleared" = "Yes".  Summarising email and Slack discussions on these here, to bring information into one place:

Christopher Hilton [12:15] 
Here's William S's feedback on the five (it turns out) V images in MIRO that are flagged as "Copyright cleared" but Restrictions on Use (ie licence) as "Academics" only, ie not CC:

"The three Sicilian ones are out of copyright.  Presumably they were withheld from the web for reasons of possible indecency, though similar ones are on the web.
The Johnston Saint one is in copyright.  The Countess of Harrowby (copyright holder; deceased 1997) in 1991 authorised the taking of the copy photo and reproduction on the videodisc, but that's as far as the permission goes, unless you want to open negotiations with her son, the 8th Earl.
De Broglie: the photographer Henri Manuel died on 11 September 1947, so his copyrights will expire on 31 December this year."

So, in the case of Johnston Saint on a camel "Copyright cleared" is being used as a proxy for "OK to display on the web" - copyright cleared for this use only
The de Broglie portrait is still in copyright and it's not clear from what W says if we actually got this cleared before displaying - I'll pursue
"The three Sicilian ones" open up a whole new can of worms - it seems clear that we can display these as CC if we want, being out of copyright, but they're 19th century pictures of naked children in a quasi-classical setting which frankly make me a bit uneasy about the photographer's intent.  So here "Academics" indicates that we're not sure if we want to distribute these widely on the web.  You can get a flavour from the thumbnails above.
Bottom line, I suppose, there are going to be all manner of combinations of statuses that apply for individual reasons - and what we need to be able to do is, pro tem, filter and just display the things that are flagged as Copyright Cleared and "Restrictions on Use" = some form of CC status.

Tom Scott [12:27] 
we might licence those as -nc but restrict access because of sensitivity
similar to how we might treat the physical items

Christopher Hilton [12:29] 
Yes - indication, isn't it, of how the "Restrictions on use" field (= licensing what you can do with it) ends up flagging issues that really belong in "Restrictions on access" (= who can see it at all), as we were talking about last week
William suggests we have a chat with him about the V images and issues that may arise with them - sounds sensible.  I 'll certainly do that but might well be an idea to involve someone else too to ensure continuity in view of my impending departure

Tom Scott [12:33] 
would be sensible to involve @chenshaw in that conversation

**Comment by alexwlchan** [comment]
For anybody following up on this, the relevant Slack conversation (and the image IDs) is here: https://wellcome.slack.com/archives/C3TQSF63C/p1501240505998566
