### ISSUE TITLE
Loris is screwing with colour profiles in images

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#734]
https://iiif.wellcomecollection.org/image/V0000003.jpg/full/full/0/default.jpg

Left is the JPEG from miro-images-public; right is the image served by Loris. They don’t look the same. 😢 

![screen shot 2017-08-01 at 11 36 14](https://user-images.githubusercontent.com/301220/28821537-b351062e-76ad-11e7-9c80-2854ba6d8ee7.png)

**Comment by jtweed** [comment]
Loris should be transforming to sRGB if necessary. There is some support colour management support in Loris already, we may need extend on that if it doesn't do what we need.

**Comment by alexwlchan** [comment]
```
emb_profile = io.BytesIO(im2.info['icc_profile'])
im3 = profileToProfile(im2alt, emb_profile, '/System/Library/ColorSync/Profiles/sRGB Profile.icc')
im3.save('V0000003_srgb_sys.jpg')
```

**Comment by alexwlchan** [comment]
I managed to get a WIP PR against Loris tonight. Still missing the necessary tests, and a bit messy, but basically works. \o/

**Comment by alexwlchan** [comment]
I’m waiting for green CI and a review on https://github.com/loris-imageserver/loris/pull/351, then I should be able to finish the Loris PR and get it merged.

**Comment by alexwlchan** [comment]
Okay, Loris patch is merged. We’ll need a config change and new Docker image on our side, then this should be good to go.

**Comment by alexwlchan** [comment]
Patch is done and merged, we just need to deploy it. The Travis build failed, which I’m fixing in #907, meanwhile I’m just going to deploy from local, as Docker means it doesn’t make a difference!

**Comment by alexwlchan** [comment]
Doing this uncovered _another_ Loris patch we needed to get this working with rotation, but I’ve deployed from my fork to get this done. We’ll need to flip back to Loris proper when it gets merged, but it should be the same code.

I’ve also flushed the CloudFront cache, so all (library) images now appear with their correct colour profiles!

Example URLs:

https://iiif-origin.wellcomecollection.org/image/V0000003.jpg/full/full/0/default.jpg
https://iiif-origin.wellcomecollection.org/image/V0000003-broken.jpg/full/full/0/default.jpg
https://iiif-origin.wellcomecollection.org/image/V0000003.jpg/full/full/45/default.jpg
