### ISSUE TITLE
Discard results that only say "Awaiting description"

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#760]

**Comment by pollecuttn** [comment]
@alexwlchan Is this something the Experience team need to be aware of either because it helps them or in case they don't get the results they expect?

**Comment by alexwlchan** [comment]
As with #759, this is just improving the signal-to-noise ratio of results, but with no change required for them.

**Comment by alexwlchan** [comment]
Duplicate of #882.

The rules from Christy have us putting these images in cold store.
