### ISSUE TITLE
Expose workType in the Catalogue API

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#787]
Add a workType to MIRO records.

As we don't have a reliable source of work type for a MIRO record will make them all Digital Images.

Example JSON:

```
"workType" : {
    "id" : "digital-image",
    "type": "WorkType",
    "label" : "Digital Images" 
},
```

Drawing from the id and label from this file:
https://github.com/wellcometrust/platform-api/blob/master/ontologies/Reference%20data/work-types.csv

@jennpb has mentioned wanting to change labels so we have to think about where labels live. In the file discussed for storing enumerated types or somewhere else. Or leave out the label and move the mapping to the client.

**Comment by alexwlchan** [comment]
Going to park this until @silveroliver and @jennpb have had a chance to discuss work types more fully; as Miro is always returning the same thing putting this in the API doesn’t feel like a high priority.

**Comment by silveroliver** [comment]
Following meeting with @jennpb we have agreed to continue to use this worktypes as found at source for now. 
These can be mapped to their own labels on the front end.
But there is a larger piece of work to consolidate, split, merge the existing list of work types to something more useful. This will take time but when the business logic is available for it we can discuss exposing an additional property for the new mapped typed and run parallel.

For example e-manuscripts-asian conflates country of origin, work type and a delivery format. This will need to be unpicked at a later date.

**Comment by silveroliver** [comment]
@alexwlchan Jonathan has suggested we park this until we are working with real work types from a source like Sierra.

**Comment by alexwlchan** [comment]
When we do this properly, we’ll likely want to use #817 (or whatever method ends up replacing it) for defining the workType objects.
