### ISSUE TITLE
💥 Let’s break up the Miro adapter, and decide where images should live 💥

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#882]
This is a tracking ticket for our conversations this morning, and all the bits that need to happen for this to be done:

- [x] Write an XML-to-JSON converter service, which takes XML Miro exports and breaks them up into individual JSON files
- [x] Write a sorter that spots changes to those files, and decides the final category for each Miro record
- [x] Write a Catalogue adapter that spots the category assignment, and copies metadata and assets accordingly

**Comment by alexwlchan** [comment]
Ah, I remembered why it’s useful to have a single file with all the JSON blobs!

When you want to do analysis of the entire set (e.g. “if I make this change, how many records will be dropped”?) that’s _much_ easier if you can download a single file and work locally than iterate over thousands of files that you’ve had to fetch from S3.

**Comment by alexwlchan** [comment]
The WI selection rules document is on SharePoint: https://wellcomecloud-my.sharepoint.com/personal/c_henshaw_wellcome_ac_uk/_layouts/15/onedrive.aspx?id=%2fpersonal%2fc_henshaw_wellcome_ac_uk%2fDocuments%2fShared+stuff+-+internal%2fWI+migration&FolderCTID=0x012000C157F1E960030E429A435A8C372025FF

Also, feedback from Christy:

> In the same folder as the WI selection rules document is a text file with a list of image numbers. These are images with the phrase “title page” in the description, slightly edited to remove a few images that we might want to keep for whatever reason.
>
> This list is for total obliteration – don’t need the images, don’t need the MIRO records, even.

**Comment by alexwlchan** [comment]
Relevant: #711

**Comment by kenoir** [comment]
Done

**Comment by kenoir** [comment]
Closing as done.
