### ISSUE TITLE
Expose INNOPAC IDs as one of the source identifiers in the API for library content

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#887]
Pages on wellcomeimages.org that correspond to library records have a “Link to Wellcome Library Catalogue”. e.g. https://wellcomeimages.org/indexplus/image/V0000003.html links to http://catalogue.wellcomelibrary.org/record=b1166865

Currently the API (and so next.wc.org) don’t have a way to jump from a Miro record in the API to the associated Sierra catalogue record. This is one of the last gaps in functionality compared to the old site.

We do have the b-numbers, via the `image_innopac_id` field in the Miro exports. We could expose them as an additional source identifier in the API, thus allowing the Experience team to construct links to the Sierra records. That alone is a fairly small patch to the Miro transformer.

There may be more interesting interactions with the ID minter.

We’re not committed to this – but @jennpb has asked for it (preferably by September 25th), as it’s something we anticipate staff asking about as a loss of functionality compared to the old site.

**Comment by alexwlchan** [comment]
Question for @jtweed and @pollecuttn: what should the format of IDs in the API be?

I’m guessing something like (if the image_innopac_id was `1161183`):

```json
{
    "identifierScheme": "sierra-system-number",
    "value": "1161183",
    "type": "Identifier"
}
```

In particular:

* Is that the right identifierScheme?
* I’m dropping the final check digit, because I think that’s only a check digit and can be discarded for our purposes. Correct?
* The Miro data doesn’t have a b-prefix. Happy to leave that off?

**Comment by pollecuttn** [comment]
> The Miro data doesn’t have a b-prefix. Happy to leave that off?

I don't know why these don't have a b-prefix in Miro but I think it should be there. The b denotes that it's a bibliographic record. As there are other record types in Sierra (e.g. item, holding) we should be able to know that it's referring to a bibliographic record. There has been an item record in Sierra with the same 1161183 record number so it could easily happen again that the number bit of a bib number also matches the number bit of an item, holding or other Sierra record type.

**Comment by jtweed** [comment]
It should definitely have a `b` at the start, but dropping the check digit seems to be the done thing elsewhere, including Encore.

I think from my poking at Sierra that `sierra-system-number` is the most appropriate naming. Would you agree @pollecuttn?

**Comment by pollecuttn** [comment]
> I think from my poking at Sierra that sierra-system-number is the most appropriate naming. Would you agree @pollecuttn?

Yup.

**Comment by alexwlchan** [comment]
These now appear in the API, with the b-prefix, without the check digit, and named "sierra-system-number".
