### ISSUE TITLE
Zero-pad corporate photography shoot IDs

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#898]
In the shoot.csv files, the numeric portion of the Reference column should be zero-padded to six digits to match the length they will be in Light Blue.

So `CP 3483` would become `CP 003483`

We'll need to regenerate all the shoot.csv to do this. The folder names don't need to change.

**Comment by alexwlchan** [comment]
Tiny patch, running the script now.

**Comment by alexwlchan** [comment]
This is now done. Two shoots failed processing: `258/A` and `M003`. What should we do with those?

**Comment by jtweed** [comment]
Are you sure? I just looked at a couple in S3 and they haven't changed...

**Comment by alexwlchan** [comment]
Blergh. I’ve run the script at least, and I checked a couple and they were changed.

Which ones are you looking at?

**Comment by jtweed** [comment]
You wrote it into the wrong bucket 😂

**Comment by alexwlchan** [comment]
> You wrote it into the wrong bucket 😂

🤦‍♂️

Okay, I think it’s fixed now?

**Comment by alexwlchan** [comment]
I’m going to call these `CP 000258/A` and `CP M000003`. Okay @jtweed?

**Comment by jtweed** [comment]
For the record, neither of those have images. So we can exclude both from this process. The data will carry over when the shoot data is migrated.
