### ISSUE TITLE
Review MIRO images filtering rules for Catalogue API

### ISSUE THREAD

**Issue by alicefuzier** [wellcometrust/platform#983]
As part of the work on the miro preprocessor pipeline, we have implemented some rules to classify images into 5 categories: cold storage, tandem vault, digital library, catalogue API and undecided.

The digital library and catalogue API categories at the moment are distinct because there are some discrepancies between the rules we have been given to sort these images and the filtering rules already implemented in the transformer (which have been migrated to the miro preprocessor pipeline). 

Main differences are:
- images for the digital library have to have a valid innopac_id whereas the ones for catalogue API don't. I guess we want to keep doing this.
- images for catalogue API have to have the `image_cleared` field set to `Y` whereas the value of the field is irrelevant for the digital library. According to Christy checking this field might not be necessary, but we use it to filter out images with no `image_title`as per #356 so we would need some extra logic, possibly checking in `image_pub_title` and `image_pub_periodical` if a title exists before discarding the image.
- images for the digital library can have "None" as a value of `image_use_restrictions` whereas for the catalogue API this field must contain a valid CC licence code. This is needed for the experience team as they need to expose licenses. On the other hand a value of "None" means no restriction in using this image, so there is no reason why we shouldn't expose in the API. To check with @jtweed and @jennpb what we want to do with those.

We should review these rules and decide how/if we want to change them

**Comment by alexwlchan** [comment]
> On the other hand a value of "None" means no restriction in using this image, so there is no reason why we shouldn't expose in the API.

Does it actually mean that, or does it just mean nobody’s filled in this field yet? Might be one to check with Christy or Hannah.

**Comment by jennpb** [comment]
If 'none' means 'no restrictions', could we apply a blanket CC0 licence to them? I guess that's one for Christy.

**Comment by alicefuzier** [comment]
> Does it actually mean that, or does it just mean nobody’s filled in this field yet? Might be one to check with Christy or Hannah.

Yeah, it does, I checked with Christy. These are not empty, they actually have the string "None", which someone filled in.

**Comment by jtweed** [comment]
We will have to handle these as exceptions, writing in a PDM license, as PDM is not available as a license in Miro.
